// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/dynamodbstreams"
	"github.com/aws/aws-sdk-go-v2/service/dynamodbstreams/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newDynamoDBStreamsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "dynamodbstreams",
		Short: "DynamoDBStreams commands",
	}

	cmd.AddCommand(
		newDynamoDBStreamsDescribeStreamCmd(),
		newDynamoDBStreamsGetRecordsCmd(),
		newDynamoDBStreamsGetShardIteratorCmd(),
	)

	return cmd
}

func newDynamoDBStreamsDescribeStreamCmd() *cobra.Command {
	var streamArn string
	var exclusiveStartShardId string
	var limit int32
	var shardFilter string

	cmd := &cobra.Command{
		Use:   "describe-stream",
		Short: "DescribeStream",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodbstreams.NewFromConfig(cfg, func(o *dynamodbstreams.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodbstreams.DescribeStreamInput{}

			if streamArn != "" {
				input.StreamArn = aws.String(streamArn)
			}

			if exclusiveStartShardId != "" {
				input.ExclusiveStartShardId = aws.String(exclusiveStartShardId)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			if shardFilter != "" {
				var val types.ShardFilter
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), shardFilter); err != nil {
					return fmt.Errorf("describe-stream: parse --shard-filter: %w", err)
				}
				input.ShardFilter = &val
			}

			out, err := client.DescribeStream(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-stream failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&streamArn, "stream-arn", "", "Stream arn")

	cmd.Flags().StringVar(&exclusiveStartShardId, "exclusive-start-shard-id", "", "Exclusive start shard id")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().StringVar(&shardFilter, "shard-filter", "", "Shard filter (key=value,key2=value2)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBStreamsGetRecordsCmd() *cobra.Command {
	var shardIterator string
	var limit int32

	cmd := &cobra.Command{
		Use:   "get-records",
		Short: "GetRecords",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodbstreams.NewFromConfig(cfg, func(o *dynamodbstreams.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodbstreams.GetRecordsInput{}

			if shardIterator != "" {
				input.ShardIterator = aws.String(shardIterator)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			out, err := client.GetRecords(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-records failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&shardIterator, "shard-iterator", "", "Shard iterator")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBStreamsGetShardIteratorCmd() *cobra.Command {
	var shardId string
	var shardIteratorType string
	var streamArn string
	var sequenceNumber string

	cmd := &cobra.Command{
		Use:   "get-shard-iterator",
		Short: "GetShardIterator",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodbstreams.NewFromConfig(cfg, func(o *dynamodbstreams.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodbstreams.GetShardIteratorInput{}

			if shardId != "" {
				input.ShardId = aws.String(shardId)
			}

			if shardIteratorType != "" {
				input.ShardIteratorType = types.ShardIteratorType(shardIteratorType)
			}

			if streamArn != "" {
				input.StreamArn = aws.String(streamArn)
			}

			if sequenceNumber != "" {
				input.SequenceNumber = aws.String(sequenceNumber)
			}

			out, err := client.GetShardIterator(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-shard-iterator failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&shardId, "shard-id", "", "Shard id")

	cmd.Flags().StringVar(&shardIteratorType, "shard-iterator-type", "", "Shard iterator type")

	cmd.Flags().StringVar(&streamArn, "stream-arn", "", "Stream arn")

	cmd.Flags().StringVar(&sequenceNumber, "sequence-number", "", "Sequence number")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
