// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudformation"
	"github.com/aws/aws-sdk-go-v2/service/cloudformation/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newCloudFormationCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cloudformation",
		Short: "CloudFormation commands",
	}

	cmd.AddCommand(
		newCloudFormationCreateStackCmd(),
		newCloudFormationDeleteStackCmd(),
		newCloudFormationDescribeStackResourcesCmd(),
		newCloudFormationDescribeStacksCmd(),
		newCloudFormationGetTemplateCmd(),
		newCloudFormationListStacksCmd(),
		newCloudFormationUpdateStackCmd(),
		newCloudFormationValidateTemplateCmd(),
	)

	return cmd
}

func newCloudFormationCreateStackCmd() *cobra.Command {
	var stackName string
	var capabilities []string
	var clientRequestToken string
	var deploymentConfig string
	var disableRollback bool
	var disableValidation bool
	var enableTerminationProtection bool
	var notificationARNs []string
	var onFailure string
	var parameters []string
	var resourceTypes []string
	var retainExceptOnCreate bool
	var roleARN string
	var rollbackConfiguration string
	var stackPolicyBody string
	var stackPolicyURL string
	var tags []string
	var templateBody string
	var templateURL string
	var timeoutInMinutes int32

	cmd := &cobra.Command{
		Use:   "create-stack",
		Short: "CreateStack",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudformation.NewFromConfig(cfg, func(o *cloudformation.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudformation.CreateStackInput{}

			if stackName != "" {
				input.StackName = aws.String(stackName)
			}

			for _, s := range capabilities {
				input.Capabilities = append(input.Capabilities, types.Capability(s))
			}

			if clientRequestToken != "" {
				input.ClientRequestToken = aws.String(clientRequestToken)
			}

			if deploymentConfig != "" {
				var val types.DeploymentConfig
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), deploymentConfig); err != nil {
					return fmt.Errorf("create-stack: parse --deployment-config: %w", err)
				}
				input.DeploymentConfig = &val
			}

			if disableRollback {
				input.DisableRollback = aws.Bool(disableRollback)
			}

			if disableValidation {
				input.DisableValidation = aws.Bool(disableValidation)
			}

			if enableTerminationProtection {
				input.EnableTerminationProtection = aws.Bool(enableTerminationProtection)
			}

			if len(notificationARNs) > 0 {
				input.NotificationARNs = notificationARNs
			}

			if onFailure != "" {
				input.OnFailure = types.OnFailure(onFailure)
			}

			for _, raw := range parameters {
				var val types.Parameter
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-stack: parse --parameters: %w", err)
				}
				input.Parameters = append(input.Parameters, val)
			}

			if len(resourceTypes) > 0 {
				input.ResourceTypes = resourceTypes
			}

			if retainExceptOnCreate {
				input.RetainExceptOnCreate = aws.Bool(retainExceptOnCreate)
			}

			if roleARN != "" {
				input.RoleARN = aws.String(roleARN)
			}

			if rollbackConfiguration != "" {
				if err := json.Unmarshal([]byte(rollbackConfiguration), &input.RollbackConfiguration); err != nil {
					return fmt.Errorf("create-stack: parse --rollback-configuration: %w", err)
				}
			}

			if stackPolicyBody != "" {
				input.StackPolicyBody = aws.String(stackPolicyBody)
			}

			if stackPolicyURL != "" {
				input.StackPolicyURL = aws.String(stackPolicyURL)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-stack: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			if templateBody != "" {
				input.TemplateBody = aws.String(templateBody)
			}

			if templateURL != "" {
				input.TemplateURL = aws.String(templateURL)
			}

			if timeoutInMinutes != 0 {
				input.TimeoutInMinutes = aws.Int32(timeoutInMinutes)
			}

			out, err := client.CreateStack(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-stack failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&stackName, "stack-name", "", "Stack name")

	cmd.Flags().StringArrayVar(&capabilities, "capabilities", nil, "Capabilities")

	cmd.Flags().StringVar(&clientRequestToken, "client-request-token", "", "Client request token")

	cmd.Flags().StringVar(&deploymentConfig, "deployment-config", "", "Deployment config (key=value,key2=value2)")

	cmd.Flags().BoolVar(&disableRollback, "disable-rollback", false, "Disable rollback")

	cmd.Flags().BoolVar(&disableValidation, "disable-validation", false, "Disable validation")

	cmd.Flags().BoolVar(&enableTerminationProtection, "enable-termination-protection", false, "Enable termination protection")

	cmd.Flags().StringArrayVar(&notificationARNs, "notification-a-r-ns", nil, "Notification a r ns")

	cmd.Flags().StringVar(&onFailure, "on-failure", "", "On failure")

	cmd.Flags().StringArrayVar(&parameters, "parameters", nil, "Parameters (key=value,key2=value2, repeatable)")

	cmd.Flags().StringArrayVar(&resourceTypes, "resource-types", nil, "Resource types")

	cmd.Flags().BoolVar(&retainExceptOnCreate, "retain-except-on-create", false, "Retain except on create")

	cmd.Flags().StringVar(&roleARN, "role-arn", "", "Role arn")

	cmd.Flags().StringVar(&rollbackConfiguration, "rollback-configuration", "", "Rollback configuration (JSON)")

	cmd.Flags().StringVar(&stackPolicyBody, "stack-policy-body", "", "Stack policy body")

	cmd.Flags().StringVar(&stackPolicyURL, "stack-policy-url", "", "Stack policy url")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&templateBody, "template-body", "", "Template body")

	cmd.Flags().StringVar(&templateURL, "template-url", "", "Template url")

	cmd.Flags().Int32Var(&timeoutInMinutes, "timeout-in-minutes", 0, "Timeout in minutes")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudFormationDeleteStackCmd() *cobra.Command {
	var stackName string
	var clientRequestToken string
	var deletionMode string
	var deploymentConfig string
	var retainResources []string
	var roleARN string

	cmd := &cobra.Command{
		Use:   "delete-stack",
		Short: "DeleteStack",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudformation.NewFromConfig(cfg, func(o *cloudformation.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudformation.DeleteStackInput{}

			if stackName != "" {
				input.StackName = aws.String(stackName)
			}

			if clientRequestToken != "" {
				input.ClientRequestToken = aws.String(clientRequestToken)
			}

			if deletionMode != "" {
				input.DeletionMode = types.DeletionMode(deletionMode)
			}

			if deploymentConfig != "" {
				var val types.DeploymentConfig
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), deploymentConfig); err != nil {
					return fmt.Errorf("delete-stack: parse --deployment-config: %w", err)
				}
				input.DeploymentConfig = &val
			}

			if len(retainResources) > 0 {
				input.RetainResources = retainResources
			}

			if roleARN != "" {
				input.RoleARN = aws.String(roleARN)
			}

			_, err = client.DeleteStack(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-stack failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&stackName, "stack-name", "", "Stack name")

	cmd.Flags().StringVar(&clientRequestToken, "client-request-token", "", "Client request token")

	cmd.Flags().StringVar(&deletionMode, "deletion-mode", "", "Deletion mode")

	cmd.Flags().StringVar(&deploymentConfig, "deployment-config", "", "Deployment config (key=value,key2=value2)")

	cmd.Flags().StringArrayVar(&retainResources, "retain-resources", nil, "Retain resources")

	cmd.Flags().StringVar(&roleARN, "role-arn", "", "Role arn")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudFormationDescribeStackResourcesCmd() *cobra.Command {
	var logicalResourceId string
	var physicalResourceId string
	var stackName string

	cmd := &cobra.Command{
		Use:   "describe-stack-resources",
		Short: "DescribeStackResources",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudformation.NewFromConfig(cfg, func(o *cloudformation.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudformation.DescribeStackResourcesInput{}

			if logicalResourceId != "" {
				input.LogicalResourceId = aws.String(logicalResourceId)
			}

			if physicalResourceId != "" {
				input.PhysicalResourceId = aws.String(physicalResourceId)
			}

			if stackName != "" {
				input.StackName = aws.String(stackName)
			}

			out, err := client.DescribeStackResources(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-stack-resources failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&logicalResourceId, "logical-resource-id", "", "Logical resource id")

	cmd.Flags().StringVar(&physicalResourceId, "physical-resource-id", "", "Physical resource id")

	cmd.Flags().StringVar(&stackName, "stack-name", "", "Stack name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudFormationDescribeStacksCmd() *cobra.Command {
	var nextToken string
	var stackName string

	cmd := &cobra.Command{
		Use:   "describe-stacks",
		Short: "DescribeStacks",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudformation.NewFromConfig(cfg, func(o *cloudformation.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudformation.DescribeStacksInput{}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if stackName != "" {
				input.StackName = aws.String(stackName)
			}

			out, err := client.DescribeStacks(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-stacks failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&stackName, "stack-name", "", "Stack name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudFormationGetTemplateCmd() *cobra.Command {
	var changeSetName string
	var stackName string
	var templateStage string

	cmd := &cobra.Command{
		Use:   "get-template",
		Short: "GetTemplate",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudformation.NewFromConfig(cfg, func(o *cloudformation.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudformation.GetTemplateInput{}

			if changeSetName != "" {
				input.ChangeSetName = aws.String(changeSetName)
			}

			if stackName != "" {
				input.StackName = aws.String(stackName)
			}

			if templateStage != "" {
				input.TemplateStage = types.TemplateStage(templateStage)
			}

			out, err := client.GetTemplate(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-template failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&changeSetName, "change-set-name", "", "Change set name")

	cmd.Flags().StringVar(&stackName, "stack-name", "", "Stack name")

	cmd.Flags().StringVar(&templateStage, "template-stage", "", "Template stage")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudFormationListStacksCmd() *cobra.Command {
	var nextToken string
	var stackStatusFilter []string

	cmd := &cobra.Command{
		Use:   "list-stacks",
		Short: "ListStacks",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudformation.NewFromConfig(cfg, func(o *cloudformation.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudformation.ListStacksInput{}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			for _, s := range stackStatusFilter {
				input.StackStatusFilter = append(input.StackStatusFilter, types.StackStatus(s))
			}

			out, err := client.ListStacks(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-stacks failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringArrayVar(&stackStatusFilter, "stack-status-filter", nil, "Stack status filter")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudFormationUpdateStackCmd() *cobra.Command {
	var stackName string
	var capabilities []string
	var clientRequestToken string
	var deploymentConfig string
	var disableRollback bool
	var disableValidation bool
	var notificationARNs []string
	var parameters []string
	var resourceTypes []string
	var retainExceptOnCreate bool
	var roleARN string
	var rollbackConfiguration string
	var stackPolicyBody string
	var stackPolicyDuringUpdateBody string
	var stackPolicyDuringUpdateURL string
	var stackPolicyURL string
	var tags []string
	var templateBody string
	var templateURL string
	var usePreviousTemplate bool

	cmd := &cobra.Command{
		Use:   "update-stack",
		Short: "UpdateStack",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudformation.NewFromConfig(cfg, func(o *cloudformation.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudformation.UpdateStackInput{}

			if stackName != "" {
				input.StackName = aws.String(stackName)
			}

			for _, s := range capabilities {
				input.Capabilities = append(input.Capabilities, types.Capability(s))
			}

			if clientRequestToken != "" {
				input.ClientRequestToken = aws.String(clientRequestToken)
			}

			if deploymentConfig != "" {
				var val types.DeploymentConfig
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), deploymentConfig); err != nil {
					return fmt.Errorf("update-stack: parse --deployment-config: %w", err)
				}
				input.DeploymentConfig = &val
			}

			if disableRollback {
				input.DisableRollback = aws.Bool(disableRollback)
			}

			if disableValidation {
				input.DisableValidation = aws.Bool(disableValidation)
			}

			if len(notificationARNs) > 0 {
				input.NotificationARNs = notificationARNs
			}

			for _, raw := range parameters {
				var val types.Parameter
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("update-stack: parse --parameters: %w", err)
				}
				input.Parameters = append(input.Parameters, val)
			}

			if len(resourceTypes) > 0 {
				input.ResourceTypes = resourceTypes
			}

			if retainExceptOnCreate {
				input.RetainExceptOnCreate = aws.Bool(retainExceptOnCreate)
			}

			if roleARN != "" {
				input.RoleARN = aws.String(roleARN)
			}

			if rollbackConfiguration != "" {
				if err := json.Unmarshal([]byte(rollbackConfiguration), &input.RollbackConfiguration); err != nil {
					return fmt.Errorf("update-stack: parse --rollback-configuration: %w", err)
				}
			}

			if stackPolicyBody != "" {
				input.StackPolicyBody = aws.String(stackPolicyBody)
			}

			if stackPolicyDuringUpdateBody != "" {
				input.StackPolicyDuringUpdateBody = aws.String(stackPolicyDuringUpdateBody)
			}

			if stackPolicyDuringUpdateURL != "" {
				input.StackPolicyDuringUpdateURL = aws.String(stackPolicyDuringUpdateURL)
			}

			if stackPolicyURL != "" {
				input.StackPolicyURL = aws.String(stackPolicyURL)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("update-stack: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			if templateBody != "" {
				input.TemplateBody = aws.String(templateBody)
			}

			if templateURL != "" {
				input.TemplateURL = aws.String(templateURL)
			}

			if usePreviousTemplate {
				input.UsePreviousTemplate = aws.Bool(usePreviousTemplate)
			}

			out, err := client.UpdateStack(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-stack failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&stackName, "stack-name", "", "Stack name")

	cmd.Flags().StringArrayVar(&capabilities, "capabilities", nil, "Capabilities")

	cmd.Flags().StringVar(&clientRequestToken, "client-request-token", "", "Client request token")

	cmd.Flags().StringVar(&deploymentConfig, "deployment-config", "", "Deployment config (key=value,key2=value2)")

	cmd.Flags().BoolVar(&disableRollback, "disable-rollback", false, "Disable rollback")

	cmd.Flags().BoolVar(&disableValidation, "disable-validation", false, "Disable validation")

	cmd.Flags().StringArrayVar(&notificationARNs, "notification-a-r-ns", nil, "Notification a r ns")

	cmd.Flags().StringArrayVar(&parameters, "parameters", nil, "Parameters (key=value,key2=value2, repeatable)")

	cmd.Flags().StringArrayVar(&resourceTypes, "resource-types", nil, "Resource types")

	cmd.Flags().BoolVar(&retainExceptOnCreate, "retain-except-on-create", false, "Retain except on create")

	cmd.Flags().StringVar(&roleARN, "role-arn", "", "Role arn")

	cmd.Flags().StringVar(&rollbackConfiguration, "rollback-configuration", "", "Rollback configuration (JSON)")

	cmd.Flags().StringVar(&stackPolicyBody, "stack-policy-body", "", "Stack policy body")

	cmd.Flags().StringVar(&stackPolicyDuringUpdateBody, "stack-policy-during-update-body", "", "Stack policy during update body")

	cmd.Flags().StringVar(&stackPolicyDuringUpdateURL, "stack-policy-during-update-url", "", "Stack policy during update url")

	cmd.Flags().StringVar(&stackPolicyURL, "stack-policy-url", "", "Stack policy url")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&templateBody, "template-body", "", "Template body")

	cmd.Flags().StringVar(&templateURL, "template-url", "", "Template url")

	cmd.Flags().BoolVar(&usePreviousTemplate, "use-previous-template", false, "Use previous template")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudFormationValidateTemplateCmd() *cobra.Command {
	var templateBody string
	var templateURL string

	cmd := &cobra.Command{
		Use:   "validate-template",
		Short: "ValidateTemplate",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudformation.NewFromConfig(cfg, func(o *cloudformation.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudformation.ValidateTemplateInput{}

			if templateBody != "" {
				input.TemplateBody = aws.String(templateBody)
			}

			if templateURL != "" {
				input.TemplateURL = aws.String(templateURL)
			}

			out, err := client.ValidateTemplate(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("validate-template failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&templateBody, "template-body", "", "Template body")

	cmd.Flags().StringVar(&templateURL, "template-url", "", "Template url")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
