// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	"github.com/aws/aws-sdk-go-v2/service/secretsmanager/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newSecretsManagerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "secretsmanager",
		Short: "SecretsManager commands",
	}

	cmd.AddCommand(
		newSecretsManagerCreateSecretCmd(),
		newSecretsManagerDeleteResourcePolicyCmd(),
		newSecretsManagerDeleteSecretCmd(),
		newSecretsManagerDescribeSecretCmd(),
		newSecretsManagerGetRandomPasswordCmd(),
		newSecretsManagerGetResourcePolicyCmd(),
		newSecretsManagerGetSecretValueCmd(),
		newSecretsManagerListSecretsCmd(),
		newSecretsManagerPutResourcePolicyCmd(),
		newSecretsManagerPutSecretValueCmd(),
		newSecretsManagerUpdateSecretCmd(),
	)

	return cmd
}

func newSecretsManagerCreateSecretCmd() *cobra.Command {
	var name string
	var addReplicaRegions []string
	var clientRequestToken string
	var description string
	var forceOverwriteReplicaSecret bool
	var kmsKeyId string
	var secretBinary string
	var secretString string
	var tags []string
	var typeValue string

	cmd := &cobra.Command{
		Use:   "create-secret",
		Short: "CreateSecret",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.CreateSecretInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			for _, raw := range addReplicaRegions {
				var val types.ReplicaRegionType
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-secret: parse --add-replica-regions: %w", err)
				}
				input.AddReplicaRegions = append(input.AddReplicaRegions, val)
			}

			if clientRequestToken != "" {
				input.ClientRequestToken = aws.String(clientRequestToken)
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			if forceOverwriteReplicaSecret {
				input.ForceOverwriteReplicaSecret = forceOverwriteReplicaSecret
			}

			if kmsKeyId != "" {
				input.KmsKeyId = aws.String(kmsKeyId)
			}

			if secretBinary != "" {
				decoded, err := base64.StdEncoding.DecodeString(secretBinary)
				if err != nil {
					return fmt.Errorf("create-secret: decode --secret-binary: %w", err)
				}
				input.SecretBinary = decoded
			}

			if secretString != "" {
				input.SecretString = aws.String(secretString)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-secret: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			if typeValue != "" {
				input.Type = aws.String(typeValue)
			}

			out, err := client.CreateSecret(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-secret failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().StringArrayVar(&addReplicaRegions, "add-replica-regions", nil, "Add replica regions (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&clientRequestToken, "client-request-token", "", "Client request token")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().BoolVar(&forceOverwriteReplicaSecret, "force-overwrite-replica-secret", false, "Force overwrite replica secret")

	cmd.Flags().StringVar(&kmsKeyId, "kms-key-id", "", "Kms key id")

	cmd.Flags().StringVar(&secretBinary, "secret-binary", "", "Secret binary (base64-encoded)")

	cmd.Flags().StringVar(&secretString, "secret-string", "", "Secret string")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&typeValue, "type", "", "Type")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSecretsManagerDeleteResourcePolicyCmd() *cobra.Command {
	var secretId string

	cmd := &cobra.Command{
		Use:   "delete-resource-policy",
		Short: "DeleteResourcePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.DeleteResourcePolicyInput{}

			if secretId != "" {
				input.SecretId = aws.String(secretId)
			}

			out, err := client.DeleteResourcePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-resource-policy failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&secretId, "secret-id", "", "Secret id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSecretsManagerDeleteSecretCmd() *cobra.Command {
	var secretId string
	var forceDeleteWithoutRecovery bool
	var recoveryWindowInDays int64

	cmd := &cobra.Command{
		Use:   "delete-secret",
		Short: "DeleteSecret",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.DeleteSecretInput{}

			if secretId != "" {
				input.SecretId = aws.String(secretId)
			}

			if forceDeleteWithoutRecovery {
				input.ForceDeleteWithoutRecovery = aws.Bool(forceDeleteWithoutRecovery)
			}

			if recoveryWindowInDays != 0 {
				input.RecoveryWindowInDays = aws.Int64(recoveryWindowInDays)
			}

			out, err := client.DeleteSecret(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-secret failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&secretId, "secret-id", "", "Secret id")

	cmd.Flags().BoolVar(&forceDeleteWithoutRecovery, "force-delete-without-recovery", false, "Force delete without recovery")

	cmd.Flags().Int64Var(&recoveryWindowInDays, "recovery-window-in-days", 0, "Recovery window in days")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSecretsManagerDescribeSecretCmd() *cobra.Command {
	var secretId string

	cmd := &cobra.Command{
		Use:   "describe-secret",
		Short: "DescribeSecret",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.DescribeSecretInput{}

			if secretId != "" {
				input.SecretId = aws.String(secretId)
			}

			out, err := client.DescribeSecret(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-secret failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&secretId, "secret-id", "", "Secret id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSecretsManagerGetRandomPasswordCmd() *cobra.Command {
	var excludeCharacters string
	var excludeLowercase bool
	var excludeNumbers bool
	var excludePunctuation bool
	var excludeUppercase bool
	var includeSpace bool
	var passwordLength int64
	var requireEachIncludedType bool

	cmd := &cobra.Command{
		Use:   "get-random-password",
		Short: "GetRandomPassword",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.GetRandomPasswordInput{}

			if excludeCharacters != "" {
				input.ExcludeCharacters = aws.String(excludeCharacters)
			}

			if excludeLowercase {
				input.ExcludeLowercase = aws.Bool(excludeLowercase)
			}

			if excludeNumbers {
				input.ExcludeNumbers = aws.Bool(excludeNumbers)
			}

			if excludePunctuation {
				input.ExcludePunctuation = aws.Bool(excludePunctuation)
			}

			if excludeUppercase {
				input.ExcludeUppercase = aws.Bool(excludeUppercase)
			}

			if includeSpace {
				input.IncludeSpace = aws.Bool(includeSpace)
			}

			if passwordLength != 0 {
				input.PasswordLength = aws.Int64(passwordLength)
			}

			if requireEachIncludedType {
				input.RequireEachIncludedType = aws.Bool(requireEachIncludedType)
			}

			out, err := client.GetRandomPassword(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-random-password failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&excludeCharacters, "exclude-characters", "", "Exclude characters")

	cmd.Flags().BoolVar(&excludeLowercase, "exclude-lowercase", false, "Exclude lowercase")

	cmd.Flags().BoolVar(&excludeNumbers, "exclude-numbers", false, "Exclude numbers")

	cmd.Flags().BoolVar(&excludePunctuation, "exclude-punctuation", false, "Exclude punctuation")

	cmd.Flags().BoolVar(&excludeUppercase, "exclude-uppercase", false, "Exclude uppercase")

	cmd.Flags().BoolVar(&includeSpace, "include-space", false, "Include space")

	cmd.Flags().Int64Var(&passwordLength, "password-length", 0, "Password length")

	cmd.Flags().BoolVar(&requireEachIncludedType, "require-each-included-type", false, "Require each included type")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSecretsManagerGetResourcePolicyCmd() *cobra.Command {
	var secretId string

	cmd := &cobra.Command{
		Use:   "get-resource-policy",
		Short: "GetResourcePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.GetResourcePolicyInput{}

			if secretId != "" {
				input.SecretId = aws.String(secretId)
			}

			out, err := client.GetResourcePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-resource-policy failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&secretId, "secret-id", "", "Secret id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSecretsManagerGetSecretValueCmd() *cobra.Command {
	var secretId string
	var versionId string
	var versionStage string

	cmd := &cobra.Command{
		Use:   "get-secret-value",
		Short: "GetSecretValue",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.GetSecretValueInput{}

			if secretId != "" {
				input.SecretId = aws.String(secretId)
			}

			if versionId != "" {
				input.VersionId = aws.String(versionId)
			}

			if versionStage != "" {
				input.VersionStage = aws.String(versionStage)
			}

			out, err := client.GetSecretValue(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-secret-value failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&secretId, "secret-id", "", "Secret id")

	cmd.Flags().StringVar(&versionId, "version-id", "", "Version id")

	cmd.Flags().StringVar(&versionStage, "version-stage", "", "Version stage")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSecretsManagerListSecretsCmd() *cobra.Command {
	var filters string
	var includePlannedDeletion bool
	var maxResults int32
	var nextToken string
	var sortBy string
	var sortOrder string

	cmd := &cobra.Command{
		Use:   "list-secrets",
		Short: "ListSecrets",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.ListSecretsInput{}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("list-secrets: parse --filters: %w", err)
				}
			}

			if includePlannedDeletion {
				input.IncludePlannedDeletion = aws.Bool(includePlannedDeletion)
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if sortBy != "" {
				input.SortBy = types.SortByType(sortBy)
			}

			if sortOrder != "" {
				input.SortOrder = types.SortOrderType(sortOrder)
			}

			out, err := client.ListSecrets(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-secrets failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().BoolVar(&includePlannedDeletion, "include-planned-deletion", false, "Include planned deletion")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&sortBy, "sort-by", "", "Sort by")

	cmd.Flags().StringVar(&sortOrder, "sort-order", "", "Sort order")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSecretsManagerPutResourcePolicyCmd() *cobra.Command {
	var resourcePolicy string
	var secretId string
	var blockPublicPolicy bool

	cmd := &cobra.Command{
		Use:   "put-resource-policy",
		Short: "PutResourcePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.PutResourcePolicyInput{}

			if resourcePolicy != "" {
				input.ResourcePolicy = aws.String(resourcePolicy)
			}

			if secretId != "" {
				input.SecretId = aws.String(secretId)
			}

			if blockPublicPolicy {
				input.BlockPublicPolicy = aws.Bool(blockPublicPolicy)
			}

			out, err := client.PutResourcePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-resource-policy failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourcePolicy, "resource-policy", "", "Resource policy")

	cmd.Flags().StringVar(&secretId, "secret-id", "", "Secret id")

	cmd.Flags().BoolVar(&blockPublicPolicy, "block-public-policy", false, "Block public policy")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSecretsManagerPutSecretValueCmd() *cobra.Command {
	var secretId string
	var clientRequestToken string
	var rotationToken string
	var secretBinary string
	var secretString string
	var versionStages []string

	cmd := &cobra.Command{
		Use:   "put-secret-value",
		Short: "PutSecretValue",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.PutSecretValueInput{}

			if secretId != "" {
				input.SecretId = aws.String(secretId)
			}

			if clientRequestToken != "" {
				input.ClientRequestToken = aws.String(clientRequestToken)
			}

			if rotationToken != "" {
				input.RotationToken = aws.String(rotationToken)
			}

			if secretBinary != "" {
				decoded, err := base64.StdEncoding.DecodeString(secretBinary)
				if err != nil {
					return fmt.Errorf("put-secret-value: decode --secret-binary: %w", err)
				}
				input.SecretBinary = decoded
			}

			if secretString != "" {
				input.SecretString = aws.String(secretString)
			}

			if len(versionStages) > 0 {
				input.VersionStages = versionStages
			}

			out, err := client.PutSecretValue(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-secret-value failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&secretId, "secret-id", "", "Secret id")

	cmd.Flags().StringVar(&clientRequestToken, "client-request-token", "", "Client request token")

	cmd.Flags().StringVar(&rotationToken, "rotation-token", "", "Rotation token")

	cmd.Flags().StringVar(&secretBinary, "secret-binary", "", "Secret binary (base64-encoded)")

	cmd.Flags().StringVar(&secretString, "secret-string", "", "Secret string")

	cmd.Flags().StringArrayVar(&versionStages, "version-stages", nil, "Version stages")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSecretsManagerUpdateSecretCmd() *cobra.Command {
	var secretId string
	var clientRequestToken string
	var description string
	var kmsKeyId string
	var secretBinary string
	var secretString string
	var typeValue string

	cmd := &cobra.Command{
		Use:   "update-secret",
		Short: "UpdateSecret",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := secretsmanager.NewFromConfig(cfg, func(o *secretsmanager.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &secretsmanager.UpdateSecretInput{}

			if secretId != "" {
				input.SecretId = aws.String(secretId)
			}

			if clientRequestToken != "" {
				input.ClientRequestToken = aws.String(clientRequestToken)
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			if kmsKeyId != "" {
				input.KmsKeyId = aws.String(kmsKeyId)
			}

			if secretBinary != "" {
				decoded, err := base64.StdEncoding.DecodeString(secretBinary)
				if err != nil {
					return fmt.Errorf("update-secret: decode --secret-binary: %w", err)
				}
				input.SecretBinary = decoded
			}

			if secretString != "" {
				input.SecretString = aws.String(secretString)
			}

			if typeValue != "" {
				input.Type = aws.String(typeValue)
			}

			out, err := client.UpdateSecret(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-secret failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&secretId, "secret-id", "", "Secret id")

	cmd.Flags().StringVar(&clientRequestToken, "client-request-token", "", "Client request token")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().StringVar(&kmsKeyId, "kms-key-id", "", "Kms key id")

	cmd.Flags().StringVar(&secretBinary, "secret-binary", "", "Secret binary (base64-encoded)")

	cmd.Flags().StringVar(&secretString, "secret-string", "", "Secret string")

	cmd.Flags().StringVar(&typeValue, "type", "", "Type")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
