// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
	"time"
)

func newCloudWatchCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cloudwatch",
		Short: "CloudWatch commands",
	}

	cmd.AddCommand(
		newCloudWatchDeleteAlarmsCmd(),
		newCloudWatchDescribeAlarmsCmd(),
		newCloudWatchGetMetricDataCmd(),
		newCloudWatchGetMetricStatisticsCmd(),
		newCloudWatchListMetricsCmd(),
		newCloudWatchListTagsForResourceCmd(),
		newCloudWatchPutMetricDataCmd(),
		newCloudWatchSetAlarmStateCmd(),
		newCloudWatchTagResourceCmd(),
		newCloudWatchUntagResourceCmd(),
	)

	return cmd
}

func newCloudWatchDeleteAlarmsCmd() *cobra.Command {
	var alarmNames []string

	cmd := &cobra.Command{
		Use:   "delete-alarms",
		Short: "DeleteAlarms",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudwatch.NewFromConfig(cfg, func(o *cloudwatch.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudwatch.DeleteAlarmsInput{}

			if len(alarmNames) > 0 {
				input.AlarmNames = alarmNames
			}

			_, err = client.DeleteAlarms(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-alarms failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&alarmNames, "alarm-names", nil, "Alarm names")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudWatchDescribeAlarmsCmd() *cobra.Command {
	var actionPrefix string
	var alarmNamePrefix string
	var alarmNames []string
	var alarmTypes []string
	var childrenOfAlarmName string
	var maxRecords int32
	var nextToken string
	var parentsOfAlarmName string
	var stateValue string

	cmd := &cobra.Command{
		Use:   "describe-alarms",
		Short: "DescribeAlarms",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudwatch.NewFromConfig(cfg, func(o *cloudwatch.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudwatch.DescribeAlarmsInput{}

			if actionPrefix != "" {
				input.ActionPrefix = aws.String(actionPrefix)
			}

			if alarmNamePrefix != "" {
				input.AlarmNamePrefix = aws.String(alarmNamePrefix)
			}

			if len(alarmNames) > 0 {
				input.AlarmNames = alarmNames
			}

			for _, s := range alarmTypes {
				input.AlarmTypes = append(input.AlarmTypes, types.AlarmType(s))
			}

			if childrenOfAlarmName != "" {
				input.ChildrenOfAlarmName = aws.String(childrenOfAlarmName)
			}

			if maxRecords != 0 {
				input.MaxRecords = aws.Int32(maxRecords)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if parentsOfAlarmName != "" {
				input.ParentsOfAlarmName = aws.String(parentsOfAlarmName)
			}

			if stateValue != "" {
				input.StateValue = types.StateValue(stateValue)
			}

			out, err := client.DescribeAlarms(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-alarms failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&actionPrefix, "action-prefix", "", "Action prefix")

	cmd.Flags().StringVar(&alarmNamePrefix, "alarm-name-prefix", "", "Alarm name prefix")

	cmd.Flags().StringArrayVar(&alarmNames, "alarm-names", nil, "Alarm names")

	cmd.Flags().StringArrayVar(&alarmTypes, "alarm-types", nil, "Alarm types")

	cmd.Flags().StringVar(&childrenOfAlarmName, "children-of-alarm-name", "", "Children of alarm name")

	cmd.Flags().Int32Var(&maxRecords, "max-records", 0, "Max records")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&parentsOfAlarmName, "parents-of-alarm-name", "", "Parents of alarm name")

	cmd.Flags().StringVar(&stateValue, "state-value", "", "State value")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudWatchGetMetricDataCmd() *cobra.Command {
	var endTime string
	var metricDataQueries string
	var startTime string
	var labelOptions string
	var maxDatapoints int32
	var nextToken string
	var scanBy string

	cmd := &cobra.Command{
		Use:   "get-metric-data",
		Short: "GetMetricData",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudwatch.NewFromConfig(cfg, func(o *cloudwatch.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudwatch.GetMetricDataInput{}

			if endTime != "" {
				parsed, err := time.Parse(time.RFC3339, endTime)
				if err != nil {
					return fmt.Errorf("get-metric-data: parse --end-time: %w", err)
				}
				input.EndTime = &parsed
			}

			if metricDataQueries != "" {
				if err := json.Unmarshal([]byte(metricDataQueries), &input.MetricDataQueries); err != nil {
					return fmt.Errorf("get-metric-data: parse --metric-data-queries: %w", err)
				}
			}

			if startTime != "" {
				parsed, err := time.Parse(time.RFC3339, startTime)
				if err != nil {
					return fmt.Errorf("get-metric-data: parse --start-time: %w", err)
				}
				input.StartTime = &parsed
			}

			if labelOptions != "" {
				var val types.LabelOptions
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), labelOptions); err != nil {
					return fmt.Errorf("get-metric-data: parse --label-options: %w", err)
				}
				input.LabelOptions = &val
			}

			if maxDatapoints != 0 {
				input.MaxDatapoints = aws.Int32(maxDatapoints)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if scanBy != "" {
				input.ScanBy = types.ScanBy(scanBy)
			}

			out, err := client.GetMetricData(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-metric-data failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&endTime, "end-time", "", "End time (RFC3339)")

	cmd.Flags().StringVar(&metricDataQueries, "metric-data-queries", "", "Metric data queries (JSON)")

	cmd.Flags().StringVar(&startTime, "start-time", "", "Start time (RFC3339)")

	cmd.Flags().StringVar(&labelOptions, "label-options", "", "Label options (key=value,key2=value2)")

	cmd.Flags().Int32Var(&maxDatapoints, "max-datapoints", 0, "Max datapoints")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&scanBy, "scan-by", "", "Scan by")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudWatchGetMetricStatisticsCmd() *cobra.Command {
	var endTime string
	var metricName string
	var namespace string
	var period int32
	var startTime string
	var dimensions []string
	var extendedStatistics []string
	var statistics []string
	var unit string

	cmd := &cobra.Command{
		Use:   "get-metric-statistics",
		Short: "GetMetricStatistics",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudwatch.NewFromConfig(cfg, func(o *cloudwatch.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudwatch.GetMetricStatisticsInput{}

			if endTime != "" {
				parsed, err := time.Parse(time.RFC3339, endTime)
				if err != nil {
					return fmt.Errorf("get-metric-statistics: parse --end-time: %w", err)
				}
				input.EndTime = &parsed
			}

			if metricName != "" {
				input.MetricName = aws.String(metricName)
			}

			if namespace != "" {
				input.Namespace = aws.String(namespace)
			}

			if period != 0 {
				input.Period = aws.Int32(period)
			}

			if startTime != "" {
				parsed, err := time.Parse(time.RFC3339, startTime)
				if err != nil {
					return fmt.Errorf("get-metric-statistics: parse --start-time: %w", err)
				}
				input.StartTime = &parsed
			}

			for _, raw := range dimensions {
				var val types.Dimension
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("get-metric-statistics: parse --dimensions: %w", err)
				}
				input.Dimensions = append(input.Dimensions, val)
			}

			if len(extendedStatistics) > 0 {
				input.ExtendedStatistics = extendedStatistics
			}

			for _, s := range statistics {
				input.Statistics = append(input.Statistics, types.Statistic(s))
			}

			if unit != "" {
				input.Unit = types.StandardUnit(unit)
			}

			out, err := client.GetMetricStatistics(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-metric-statistics failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&endTime, "end-time", "", "End time (RFC3339)")

	cmd.Flags().StringVar(&metricName, "metric-name", "", "Metric name")

	cmd.Flags().StringVar(&namespace, "namespace", "", "Namespace")

	cmd.Flags().Int32Var(&period, "period", 0, "Period")

	cmd.Flags().StringVar(&startTime, "start-time", "", "Start time (RFC3339)")

	cmd.Flags().StringArrayVar(&dimensions, "dimensions", nil, "Dimensions (key=value,key2=value2, repeatable)")

	cmd.Flags().StringArrayVar(&extendedStatistics, "extended-statistics", nil, "Extended statistics")

	cmd.Flags().StringArrayVar(&statistics, "statistics", nil, "Statistics")

	cmd.Flags().StringVar(&unit, "unit", "", "Unit")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudWatchListMetricsCmd() *cobra.Command {
	var dimensions []string
	var includeLinkedAccounts bool
	var metricName string
	var namespace string
	var nextToken string
	var owningAccount string
	var recentlyActive string

	cmd := &cobra.Command{
		Use:   "list-metrics",
		Short: "ListMetrics",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudwatch.NewFromConfig(cfg, func(o *cloudwatch.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudwatch.ListMetricsInput{}

			for _, raw := range dimensions {
				var val types.DimensionFilter
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("list-metrics: parse --dimensions: %w", err)
				}
				input.Dimensions = append(input.Dimensions, val)
			}

			if includeLinkedAccounts {
				input.IncludeLinkedAccounts = aws.Bool(includeLinkedAccounts)
			}

			if metricName != "" {
				input.MetricName = aws.String(metricName)
			}

			if namespace != "" {
				input.Namespace = aws.String(namespace)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if owningAccount != "" {
				input.OwningAccount = aws.String(owningAccount)
			}

			if recentlyActive != "" {
				input.RecentlyActive = types.RecentlyActive(recentlyActive)
			}

			out, err := client.ListMetrics(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-metrics failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&dimensions, "dimensions", nil, "Dimensions (key=value,key2=value2, repeatable)")

	cmd.Flags().BoolVar(&includeLinkedAccounts, "include-linked-accounts", false, "Include linked accounts")

	cmd.Flags().StringVar(&metricName, "metric-name", "", "Metric name")

	cmd.Flags().StringVar(&namespace, "namespace", "", "Namespace")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&owningAccount, "owning-account", "", "Owning account")

	cmd.Flags().StringVar(&recentlyActive, "recently-active", "", "Recently active")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudWatchListTagsForResourceCmd() *cobra.Command {
	var resourceARN string

	cmd := &cobra.Command{
		Use:   "list-tags-for-resource",
		Short: "ListTagsForResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudwatch.NewFromConfig(cfg, func(o *cloudwatch.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudwatch.ListTagsForResourceInput{}

			if resourceARN != "" {
				input.ResourceARN = aws.String(resourceARN)
			}

			out, err := client.ListTagsForResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-tags-for-resource failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceARN, "resource-arn", "", "Resource arn")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudWatchPutMetricDataCmd() *cobra.Command {
	var namespace string
	var entityMetricData string
	var metricData string
	var strictEntityValidation bool

	cmd := &cobra.Command{
		Use:   "put-metric-data",
		Short: "PutMetricData",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudwatch.NewFromConfig(cfg, func(o *cloudwatch.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudwatch.PutMetricDataInput{}

			if namespace != "" {
				input.Namespace = aws.String(namespace)
			}

			if entityMetricData != "" {
				if err := json.Unmarshal([]byte(entityMetricData), &input.EntityMetricData); err != nil {
					return fmt.Errorf("put-metric-data: parse --entity-metric-data: %w", err)
				}
			}

			if metricData != "" {
				if err := json.Unmarshal([]byte(metricData), &input.MetricData); err != nil {
					return fmt.Errorf("put-metric-data: parse --metric-data: %w", err)
				}
			}

			if strictEntityValidation {
				input.StrictEntityValidation = aws.Bool(strictEntityValidation)
			}

			_, err = client.PutMetricData(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-metric-data failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&namespace, "namespace", "", "Namespace")

	cmd.Flags().StringVar(&entityMetricData, "entity-metric-data", "", "Entity metric data (JSON)")

	cmd.Flags().StringVar(&metricData, "metric-data", "", "Metric data (JSON)")

	cmd.Flags().BoolVar(&strictEntityValidation, "strict-entity-validation", false, "Strict entity validation")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudWatchSetAlarmStateCmd() *cobra.Command {
	var alarmName string
	var stateReason string
	var stateValue string
	var stateReasonData string

	cmd := &cobra.Command{
		Use:   "set-alarm-state",
		Short: "SetAlarmState",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudwatch.NewFromConfig(cfg, func(o *cloudwatch.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudwatch.SetAlarmStateInput{}

			if alarmName != "" {
				input.AlarmName = aws.String(alarmName)
			}

			if stateReason != "" {
				input.StateReason = aws.String(stateReason)
			}

			if stateValue != "" {
				input.StateValue = types.StateValue(stateValue)
			}

			if stateReasonData != "" {
				input.StateReasonData = aws.String(stateReasonData)
			}

			_, err = client.SetAlarmState(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("set-alarm-state failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&alarmName, "alarm-name", "", "Alarm name")

	cmd.Flags().StringVar(&stateReason, "state-reason", "", "State reason")

	cmd.Flags().StringVar(&stateValue, "state-value", "", "State value")

	cmd.Flags().StringVar(&stateReasonData, "state-reason-data", "", "State reason data")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudWatchTagResourceCmd() *cobra.Command {
	var resourceARN string
	var tags []string

	cmd := &cobra.Command{
		Use:   "tag-resource",
		Short: "TagResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudwatch.NewFromConfig(cfg, func(o *cloudwatch.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudwatch.TagResourceInput{}

			if resourceARN != "" {
				input.ResourceARN = aws.String(resourceARN)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("tag-resource: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			_, err = client.TagResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("tag-resource failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceARN, "resource-arn", "", "Resource arn")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newCloudWatchUntagResourceCmd() *cobra.Command {
	var resourceARN string
	var tagKeys []string

	cmd := &cobra.Command{
		Use:   "untag-resource",
		Short: "UntagResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := cloudwatch.NewFromConfig(cfg, func(o *cloudwatch.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &cloudwatch.UntagResourceInput{}

			if resourceARN != "" {
				input.ResourceARN = aws.String(resourceARN)
			}

			if len(tagKeys) > 0 {
				input.TagKeys = tagKeys
			}

			_, err = client.UntagResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("untag-resource failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceARN, "resource-arn", "", "Resource arn")

	cmd.Flags().StringArrayVar(&tagKeys, "tag-keys", nil, "Tag keys")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
