// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/athena"
	"github.com/aws/aws-sdk-go-v2/service/athena/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newAthenaCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "athena",
		Short: "Athena commands",
	}

	cmd.AddCommand(
		newAthenaCreateWorkGroupCmd(),
		newAthenaDeleteWorkGroupCmd(),
		newAthenaGetQueryExecutionCmd(),
		newAthenaGetQueryResultsCmd(),
		newAthenaListQueryExecutionsCmd(),
		newAthenaStartQueryExecutionCmd(),
		newAthenaStopQueryExecutionCmd(),
	)

	return cmd
}

func newAthenaCreateWorkGroupCmd() *cobra.Command {
	var name string
	var configuration string
	var description string
	var tags []string

	cmd := &cobra.Command{
		Use:   "create-work-group",
		Short: "CreateWorkGroup",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := athena.NewFromConfig(cfg, func(o *athena.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &athena.CreateWorkGroupInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			if configuration != "" {
				if err := json.Unmarshal([]byte(configuration), &input.Configuration); err != nil {
					return fmt.Errorf("create-work-group: parse --configuration: %w", err)
				}
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-work-group: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			_, err = client.CreateWorkGroup(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-work-group failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().StringVar(&configuration, "configuration", "", "Configuration (JSON)")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newAthenaDeleteWorkGroupCmd() *cobra.Command {
	var workGroup string
	var recursiveDeleteOption bool

	cmd := &cobra.Command{
		Use:   "delete-work-group",
		Short: "DeleteWorkGroup",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := athena.NewFromConfig(cfg, func(o *athena.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &athena.DeleteWorkGroupInput{}

			if workGroup != "" {
				input.WorkGroup = aws.String(workGroup)
			}

			if recursiveDeleteOption {
				input.RecursiveDeleteOption = aws.Bool(recursiveDeleteOption)
			}

			_, err = client.DeleteWorkGroup(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-work-group failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&workGroup, "work-group", "", "Work group")

	cmd.Flags().BoolVar(&recursiveDeleteOption, "recursive-delete-option", false, "Recursive delete option")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newAthenaGetQueryExecutionCmd() *cobra.Command {
	var queryExecutionId string

	cmd := &cobra.Command{
		Use:   "get-query-execution",
		Short: "GetQueryExecution",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := athena.NewFromConfig(cfg, func(o *athena.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &athena.GetQueryExecutionInput{}

			if queryExecutionId != "" {
				input.QueryExecutionId = aws.String(queryExecutionId)
			}

			out, err := client.GetQueryExecution(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-query-execution failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queryExecutionId, "query-execution-id", "", "Query execution id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newAthenaGetQueryResultsCmd() *cobra.Command {
	var queryExecutionId string
	var maxResults int32
	var nextToken string
	var queryResultType string

	cmd := &cobra.Command{
		Use:   "get-query-results",
		Short: "GetQueryResults",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := athena.NewFromConfig(cfg, func(o *athena.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &athena.GetQueryResultsInput{}

			if queryExecutionId != "" {
				input.QueryExecutionId = aws.String(queryExecutionId)
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if queryResultType != "" {
				input.QueryResultType = types.QueryResultType(queryResultType)
			}

			out, err := client.GetQueryResults(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-query-results failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queryExecutionId, "query-execution-id", "", "Query execution id")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&queryResultType, "query-result-type", "", "Query result type")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newAthenaListQueryExecutionsCmd() *cobra.Command {
	var maxResults int32
	var nextToken string
	var workGroup string

	cmd := &cobra.Command{
		Use:   "list-query-executions",
		Short: "ListQueryExecutions",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := athena.NewFromConfig(cfg, func(o *athena.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &athena.ListQueryExecutionsInput{}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if workGroup != "" {
				input.WorkGroup = aws.String(workGroup)
			}

			out, err := client.ListQueryExecutions(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-query-executions failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&workGroup, "work-group", "", "Work group")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newAthenaStartQueryExecutionCmd() *cobra.Command {
	var queryString string
	var clientRequestToken string
	var engineConfiguration string
	var executionParameters []string
	var queryExecutionContext string
	var resultConfiguration string
	var resultReuseConfiguration string
	var workGroup string

	cmd := &cobra.Command{
		Use:   "start-query-execution",
		Short: "StartQueryExecution",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := athena.NewFromConfig(cfg, func(o *athena.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &athena.StartQueryExecutionInput{}

			if queryString != "" {
				input.QueryString = aws.String(queryString)
			}

			if clientRequestToken != "" {
				input.ClientRequestToken = aws.String(clientRequestToken)
			}

			if engineConfiguration != "" {
				if err := json.Unmarshal([]byte(engineConfiguration), &input.EngineConfiguration); err != nil {
					return fmt.Errorf("start-query-execution: parse --engine-configuration: %w", err)
				}
			}

			if len(executionParameters) > 0 {
				input.ExecutionParameters = executionParameters
			}

			if queryExecutionContext != "" {
				var val types.QueryExecutionContext
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), queryExecutionContext); err != nil {
					return fmt.Errorf("start-query-execution: parse --query-execution-context: %w", err)
				}
				input.QueryExecutionContext = &val
			}

			if resultConfiguration != "" {
				if err := json.Unmarshal([]byte(resultConfiguration), &input.ResultConfiguration); err != nil {
					return fmt.Errorf("start-query-execution: parse --result-configuration: %w", err)
				}
			}

			if resultReuseConfiguration != "" {
				if err := json.Unmarshal([]byte(resultReuseConfiguration), &input.ResultReuseConfiguration); err != nil {
					return fmt.Errorf("start-query-execution: parse --result-reuse-configuration: %w", err)
				}
			}

			if workGroup != "" {
				input.WorkGroup = aws.String(workGroup)
			}

			out, err := client.StartQueryExecution(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("start-query-execution failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queryString, "query-string", "", "Query string")

	cmd.Flags().StringVar(&clientRequestToken, "client-request-token", "", "Client request token")

	cmd.Flags().StringVar(&engineConfiguration, "engine-configuration", "", "Engine configuration (JSON)")

	cmd.Flags().StringArrayVar(&executionParameters, "execution-parameters", nil, "Execution parameters")

	cmd.Flags().StringVar(&queryExecutionContext, "query-execution-context", "", "Query execution context (key=value,key2=value2)")

	cmd.Flags().StringVar(&resultConfiguration, "result-configuration", "", "Result configuration (JSON)")

	cmd.Flags().StringVar(&resultReuseConfiguration, "result-reuse-configuration", "", "Result reuse configuration (JSON)")

	cmd.Flags().StringVar(&workGroup, "work-group", "", "Work group")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newAthenaStopQueryExecutionCmd() *cobra.Command {
	var queryExecutionId string

	cmd := &cobra.Command{
		Use:   "stop-query-execution",
		Short: "StopQueryExecution",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := athena.NewFromConfig(cfg, func(o *athena.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &athena.StopQueryExecutionInput{}

			if queryExecutionId != "" {
				input.QueryExecutionId = aws.String(queryExecutionId)
			}

			_, err = client.StopQueryExecution(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("stop-query-execution failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queryExecutionId, "query-execution-id", "", "Query execution id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
