// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/ssm"
	"github.com/aws/aws-sdk-go-v2/service/ssm/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newSSMCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "ssm",
		Short: "SSM commands",
	}

	cmd.AddCommand(
		newSSMAddTagsToResourceCmd(),
		newSSMDeleteParameterCmd(),
		newSSMDeleteParametersCmd(),
		newSSMDescribeParametersCmd(),
		newSSMGetParameterCmd(),
		newSSMGetParametersCmd(),
		newSSMGetParametersByPathCmd(),
		newSSMListTagsForResourceCmd(),
		newSSMPutParameterCmd(),
		newSSMRemoveTagsFromResourceCmd(),
	)

	return cmd
}

func newSSMAddTagsToResourceCmd() *cobra.Command {
	var resourceId string
	var resourceType string
	var tags []string

	cmd := &cobra.Command{
		Use:   "add-tags-to-resource",
		Short: "AddTagsToResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ssm.NewFromConfig(cfg, func(o *ssm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ssm.AddTagsToResourceInput{}

			if resourceId != "" {
				input.ResourceId = aws.String(resourceId)
			}

			if resourceType != "" {
				input.ResourceType = types.ResourceTypeForTagging(resourceType)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("add-tags-to-resource: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			_, err = client.AddTagsToResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("add-tags-to-resource failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceId, "resource-id", "", "Resource id")

	cmd.Flags().StringVar(&resourceType, "resource-type", "", "Resource type")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSSMDeleteParameterCmd() *cobra.Command {
	var name string

	cmd := &cobra.Command{
		Use:   "delete-parameter",
		Short: "DeleteParameter",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ssm.NewFromConfig(cfg, func(o *ssm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ssm.DeleteParameterInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			_, err = client.DeleteParameter(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-parameter failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSSMDeleteParametersCmd() *cobra.Command {
	var names []string

	cmd := &cobra.Command{
		Use:   "delete-parameters",
		Short: "DeleteParameters",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ssm.NewFromConfig(cfg, func(o *ssm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ssm.DeleteParametersInput{}

			if len(names) > 0 {
				input.Names = names
			}

			out, err := client.DeleteParameters(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-parameters failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&names, "names", nil, "Names")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSSMDescribeParametersCmd() *cobra.Command {
	var filters string
	var maxResults int32
	var nextToken string
	var parameterFilters string
	var shared bool

	cmd := &cobra.Command{
		Use:   "describe-parameters",
		Short: "DescribeParameters",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ssm.NewFromConfig(cfg, func(o *ssm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ssm.DescribeParametersInput{}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("describe-parameters: parse --filters: %w", err)
				}
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if parameterFilters != "" {
				if err := json.Unmarshal([]byte(parameterFilters), &input.ParameterFilters); err != nil {
					return fmt.Errorf("describe-parameters: parse --parameter-filters: %w", err)
				}
			}

			if shared {
				input.Shared = aws.Bool(shared)
			}

			out, err := client.DescribeParameters(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-parameters failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&parameterFilters, "parameter-filters", "", "Parameter filters (JSON)")

	cmd.Flags().BoolVar(&shared, "shared", false, "Shared")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSSMGetParameterCmd() *cobra.Command {
	var name string
	var withDecryption bool

	cmd := &cobra.Command{
		Use:   "get-parameter",
		Short: "GetParameter",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ssm.NewFromConfig(cfg, func(o *ssm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ssm.GetParameterInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			if withDecryption {
				input.WithDecryption = aws.Bool(withDecryption)
			}

			out, err := client.GetParameter(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-parameter failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().BoolVar(&withDecryption, "with-decryption", false, "With decryption")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSSMGetParametersCmd() *cobra.Command {
	var names []string
	var withDecryption bool

	cmd := &cobra.Command{
		Use:   "get-parameters",
		Short: "GetParameters",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ssm.NewFromConfig(cfg, func(o *ssm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ssm.GetParametersInput{}

			if len(names) > 0 {
				input.Names = names
			}

			if withDecryption {
				input.WithDecryption = aws.Bool(withDecryption)
			}

			out, err := client.GetParameters(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-parameters failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&names, "names", nil, "Names")

	cmd.Flags().BoolVar(&withDecryption, "with-decryption", false, "With decryption")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSSMGetParametersByPathCmd() *cobra.Command {
	var path string
	var maxResults int32
	var nextToken string
	var parameterFilters string
	var recursive bool
	var withDecryption bool

	cmd := &cobra.Command{
		Use:   "get-parameters-by-path",
		Short: "GetParametersByPath",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ssm.NewFromConfig(cfg, func(o *ssm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ssm.GetParametersByPathInput{}

			if path != "" {
				input.Path = aws.String(path)
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if parameterFilters != "" {
				if err := json.Unmarshal([]byte(parameterFilters), &input.ParameterFilters); err != nil {
					return fmt.Errorf("get-parameters-by-path: parse --parameter-filters: %w", err)
				}
			}

			if recursive {
				input.Recursive = aws.Bool(recursive)
			}

			if withDecryption {
				input.WithDecryption = aws.Bool(withDecryption)
			}

			out, err := client.GetParametersByPath(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-parameters-by-path failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&path, "path", "", "Path")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&parameterFilters, "parameter-filters", "", "Parameter filters (JSON)")

	cmd.Flags().BoolVar(&recursive, "recursive", false, "Recursive")

	cmd.Flags().BoolVar(&withDecryption, "with-decryption", false, "With decryption")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSSMListTagsForResourceCmd() *cobra.Command {
	var resourceId string
	var resourceType string

	cmd := &cobra.Command{
		Use:   "list-tags-for-resource",
		Short: "ListTagsForResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ssm.NewFromConfig(cfg, func(o *ssm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ssm.ListTagsForResourceInput{}

			if resourceId != "" {
				input.ResourceId = aws.String(resourceId)
			}

			if resourceType != "" {
				input.ResourceType = types.ResourceTypeForTagging(resourceType)
			}

			out, err := client.ListTagsForResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-tags-for-resource failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceId, "resource-id", "", "Resource id")

	cmd.Flags().StringVar(&resourceType, "resource-type", "", "Resource type")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSSMPutParameterCmd() *cobra.Command {
	var name string
	var value string
	var allowedPattern string
	var dataType string
	var description string
	var keyId string
	var overwrite bool
	var policies string
	var tags []string
	var tier string
	var typeValue string

	cmd := &cobra.Command{
		Use:   "put-parameter",
		Short: "PutParameter",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ssm.NewFromConfig(cfg, func(o *ssm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ssm.PutParameterInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			if value != "" {
				input.Value = aws.String(value)
			}

			if allowedPattern != "" {
				input.AllowedPattern = aws.String(allowedPattern)
			}

			if dataType != "" {
				input.DataType = aws.String(dataType)
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			if keyId != "" {
				input.KeyId = aws.String(keyId)
			}

			if overwrite {
				input.Overwrite = aws.Bool(overwrite)
			}

			if policies != "" {
				input.Policies = aws.String(policies)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("put-parameter: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			if tier != "" {
				input.Tier = types.ParameterTier(tier)
			}

			if typeValue != "" {
				input.Type = types.ParameterType(typeValue)
			}

			out, err := client.PutParameter(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-parameter failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().StringVar(&value, "value", "", "Value")

	cmd.Flags().StringVar(&allowedPattern, "allowed-pattern", "", "Allowed pattern")

	cmd.Flags().StringVar(&dataType, "data-type", "", "Data type")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().StringVar(&keyId, "key-id", "", "Key id")

	cmd.Flags().BoolVar(&overwrite, "overwrite", false, "Overwrite")

	cmd.Flags().StringVar(&policies, "policies", "", "Policies")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&tier, "tier", "", "Tier")

	cmd.Flags().StringVar(&typeValue, "type", "", "Type")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSSMRemoveTagsFromResourceCmd() *cobra.Command {
	var resourceId string
	var resourceType string
	var tagKeys []string

	cmd := &cobra.Command{
		Use:   "remove-tags-from-resource",
		Short: "RemoveTagsFromResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ssm.NewFromConfig(cfg, func(o *ssm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ssm.RemoveTagsFromResourceInput{}

			if resourceId != "" {
				input.ResourceId = aws.String(resourceId)
			}

			if resourceType != "" {
				input.ResourceType = types.ResourceTypeForTagging(resourceType)
			}

			if len(tagKeys) > 0 {
				input.TagKeys = tagKeys
			}

			_, err = client.RemoveTagsFromResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("remove-tags-from-resource failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceId, "resource-id", "", "Resource id")

	cmd.Flags().StringVar(&resourceType, "resource-type", "", "Resource type")

	cmd.Flags().StringArrayVar(&tagKeys, "tag-keys", nil, "Tag keys")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
