// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"github.com/aws/aws-sdk-go-v2/service/ec2/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newEC2Cmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "ec2",
		Short: "EC2 commands",
	}

	cmd.AddCommand(
		newEC2AssociateRouteTableCmd(),
		newEC2AttachInternetGatewayCmd(),
		newEC2AuthorizeSecurityGroupEgressCmd(),
		newEC2AuthorizeSecurityGroupIngressCmd(),
		newEC2CreateInternetGatewayCmd(),
		newEC2CreateKeyPairCmd(),
		newEC2CreateNatGatewayCmd(),
		newEC2CreateRouteCmd(),
		newEC2CreateRouteTableCmd(),
		newEC2CreateSecurityGroupCmd(),
		newEC2CreateSubnetCmd(),
		newEC2CreateTagsCmd(),
		newEC2CreateVpcCmd(),
		newEC2DeleteInternetGatewayCmd(),
		newEC2DeleteKeyPairCmd(),
		newEC2DeleteSecurityGroupCmd(),
		newEC2DeleteSubnetCmd(),
		newEC2DeleteTagsCmd(),
		newEC2DeleteVpcCmd(),
		newEC2DescribeInstancesCmd(),
		newEC2DescribeInternetGatewaysCmd(),
		newEC2DescribeKeyPairsCmd(),
		newEC2DescribeNatGatewaysCmd(),
		newEC2DescribeNetworkInterfacesCmd(),
		newEC2DescribeRouteTablesCmd(),
		newEC2DescribeSecurityGroupsCmd(),
		newEC2DescribeSubnetsCmd(),
		newEC2DescribeTagsCmd(),
		newEC2DescribeVpcAttributeCmd(),
		newEC2DescribeVpcsCmd(),
		newEC2DetachInternetGatewayCmd(),
		newEC2ModifySubnetAttributeCmd(),
		newEC2ModifyVpcAttributeCmd(),
		newEC2RevokeSecurityGroupEgressCmd(),
		newEC2RevokeSecurityGroupIngressCmd(),
		newEC2RunInstancesCmd(),
		newEC2StartInstancesCmd(),
		newEC2StopInstancesCmd(),
		newEC2TerminateInstancesCmd(),
	)

	return cmd
}

func newEC2AssociateRouteTableCmd() *cobra.Command {
	var routeTableId string
	var dryRun bool
	var gatewayId string
	var publicIpv4Pool string
	var subnetId string

	cmd := &cobra.Command{
		Use:   "associate-route-table",
		Short: "AssociateRouteTable",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.AssociateRouteTableInput{}

			if routeTableId != "" {
				input.RouteTableId = aws.String(routeTableId)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if gatewayId != "" {
				input.GatewayId = aws.String(gatewayId)
			}

			if publicIpv4Pool != "" {
				input.PublicIpv4Pool = aws.String(publicIpv4Pool)
			}

			if subnetId != "" {
				input.SubnetId = aws.String(subnetId)
			}

			out, err := client.AssociateRouteTable(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("associate-route-table failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&routeTableId, "route-table-id", "", "Route table id")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&gatewayId, "gateway-id", "", "Gateway id")

	cmd.Flags().StringVar(&publicIpv4Pool, "public-ipv-4-pool", "", "Public ipv 4 pool")

	cmd.Flags().StringVar(&subnetId, "subnet-id", "", "Subnet id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2AttachInternetGatewayCmd() *cobra.Command {
	var internetGatewayId string
	var vpcId string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "attach-internet-gateway",
		Short: "AttachInternetGateway",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.AttachInternetGatewayInput{}

			if internetGatewayId != "" {
				input.InternetGatewayId = aws.String(internetGatewayId)
			}

			if vpcId != "" {
				input.VpcId = aws.String(vpcId)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			_, err = client.AttachInternetGateway(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("attach-internet-gateway failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&internetGatewayId, "internet-gateway-id", "", "Internet gateway id")

	cmd.Flags().StringVar(&vpcId, "vpc-id", "", "Vpc id")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2AuthorizeSecurityGroupEgressCmd() *cobra.Command {
	var groupId string
	var cidrIp string
	var dryRun bool
	var fromPort int32
	var ipPermissions string
	var ipProtocol string
	var sourceSecurityGroupName string
	var sourceSecurityGroupOwnerId string
	var tagSpecifications string
	var toPort int32

	cmd := &cobra.Command{
		Use:   "authorize-security-group-egress",
		Short: "AuthorizeSecurityGroupEgress",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.AuthorizeSecurityGroupEgressInput{}

			if groupId != "" {
				input.GroupId = aws.String(groupId)
			}

			if cidrIp != "" {
				input.CidrIp = aws.String(cidrIp)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if fromPort != 0 {
				input.FromPort = aws.Int32(fromPort)
			}

			if ipPermissions != "" {
				if err := json.Unmarshal([]byte(ipPermissions), &input.IpPermissions); err != nil {
					return fmt.Errorf("authorize-security-group-egress: parse --ip-permissions: %w", err)
				}
			}

			if ipProtocol != "" {
				input.IpProtocol = aws.String(ipProtocol)
			}

			if sourceSecurityGroupName != "" {
				input.SourceSecurityGroupName = aws.String(sourceSecurityGroupName)
			}

			if sourceSecurityGroupOwnerId != "" {
				input.SourceSecurityGroupOwnerId = aws.String(sourceSecurityGroupOwnerId)
			}

			if tagSpecifications != "" {
				if err := json.Unmarshal([]byte(tagSpecifications), &input.TagSpecifications); err != nil {
					return fmt.Errorf("authorize-security-group-egress: parse --tag-specifications: %w", err)
				}
			}

			if toPort != 0 {
				input.ToPort = aws.Int32(toPort)
			}

			out, err := client.AuthorizeSecurityGroupEgress(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("authorize-security-group-egress failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&groupId, "group-id", "", "Group id")

	cmd.Flags().StringVar(&cidrIp, "cidr-ip", "", "Cidr ip")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().Int32Var(&fromPort, "from-port", 0, "From port")

	cmd.Flags().StringVar(&ipPermissions, "ip-permissions", "", "Ip permissions (JSON)")

	cmd.Flags().StringVar(&ipProtocol, "ip-protocol", "", "Ip protocol")

	cmd.Flags().StringVar(&sourceSecurityGroupName, "source-security-group-name", "", "Source security group name")

	cmd.Flags().StringVar(&sourceSecurityGroupOwnerId, "source-security-group-owner-id", "", "Source security group owner id")

	cmd.Flags().StringVar(&tagSpecifications, "tag-specifications", "", "Tag specifications (JSON)")

	cmd.Flags().Int32Var(&toPort, "to-port", 0, "To port")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2AuthorizeSecurityGroupIngressCmd() *cobra.Command {
	var cidrIp string
	var dryRun bool
	var fromPort int32
	var groupId string
	var groupName string
	var ipPermissions string
	var ipProtocol string
	var sourceSecurityGroupName string
	var sourceSecurityGroupOwnerId string
	var tagSpecifications string
	var toPort int32

	cmd := &cobra.Command{
		Use:   "authorize-security-group-ingress",
		Short: "AuthorizeSecurityGroupIngress",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.AuthorizeSecurityGroupIngressInput{}

			if cidrIp != "" {
				input.CidrIp = aws.String(cidrIp)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if fromPort != 0 {
				input.FromPort = aws.Int32(fromPort)
			}

			if groupId != "" {
				input.GroupId = aws.String(groupId)
			}

			if groupName != "" {
				input.GroupName = aws.String(groupName)
			}

			if ipPermissions != "" {
				if err := json.Unmarshal([]byte(ipPermissions), &input.IpPermissions); err != nil {
					return fmt.Errorf("authorize-security-group-ingress: parse --ip-permissions: %w", err)
				}
			}

			if ipProtocol != "" {
				input.IpProtocol = aws.String(ipProtocol)
			}

			if sourceSecurityGroupName != "" {
				input.SourceSecurityGroupName = aws.String(sourceSecurityGroupName)
			}

			if sourceSecurityGroupOwnerId != "" {
				input.SourceSecurityGroupOwnerId = aws.String(sourceSecurityGroupOwnerId)
			}

			if tagSpecifications != "" {
				if err := json.Unmarshal([]byte(tagSpecifications), &input.TagSpecifications); err != nil {
					return fmt.Errorf("authorize-security-group-ingress: parse --tag-specifications: %w", err)
				}
			}

			if toPort != 0 {
				input.ToPort = aws.Int32(toPort)
			}

			out, err := client.AuthorizeSecurityGroupIngress(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("authorize-security-group-ingress failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&cidrIp, "cidr-ip", "", "Cidr ip")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().Int32Var(&fromPort, "from-port", 0, "From port")

	cmd.Flags().StringVar(&groupId, "group-id", "", "Group id")

	cmd.Flags().StringVar(&groupName, "group-name", "", "Group name")

	cmd.Flags().StringVar(&ipPermissions, "ip-permissions", "", "Ip permissions (JSON)")

	cmd.Flags().StringVar(&ipProtocol, "ip-protocol", "", "Ip protocol")

	cmd.Flags().StringVar(&sourceSecurityGroupName, "source-security-group-name", "", "Source security group name")

	cmd.Flags().StringVar(&sourceSecurityGroupOwnerId, "source-security-group-owner-id", "", "Source security group owner id")

	cmd.Flags().StringVar(&tagSpecifications, "tag-specifications", "", "Tag specifications (JSON)")

	cmd.Flags().Int32Var(&toPort, "to-port", 0, "To port")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2CreateInternetGatewayCmd() *cobra.Command {
	var dryRun bool
	var tagSpecifications string

	cmd := &cobra.Command{
		Use:   "create-internet-gateway",
		Short: "CreateInternetGateway",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.CreateInternetGatewayInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if tagSpecifications != "" {
				if err := json.Unmarshal([]byte(tagSpecifications), &input.TagSpecifications); err != nil {
					return fmt.Errorf("create-internet-gateway: parse --tag-specifications: %w", err)
				}
			}

			out, err := client.CreateInternetGateway(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-internet-gateway failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&tagSpecifications, "tag-specifications", "", "Tag specifications (JSON)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2CreateKeyPairCmd() *cobra.Command {
	var keyName string
	var dryRun bool
	var keyFormat string
	var keyType string
	var tagSpecifications string

	cmd := &cobra.Command{
		Use:   "create-key-pair",
		Short: "CreateKeyPair",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.CreateKeyPairInput{}

			if keyName != "" {
				input.KeyName = aws.String(keyName)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if keyFormat != "" {
				input.KeyFormat = types.KeyFormat(keyFormat)
			}

			if keyType != "" {
				input.KeyType = types.KeyType(keyType)
			}

			if tagSpecifications != "" {
				if err := json.Unmarshal([]byte(tagSpecifications), &input.TagSpecifications); err != nil {
					return fmt.Errorf("create-key-pair: parse --tag-specifications: %w", err)
				}
			}

			out, err := client.CreateKeyPair(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-key-pair failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&keyName, "key-name", "", "Key name")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&keyFormat, "key-format", "", "Key format")

	cmd.Flags().StringVar(&keyType, "key-type", "", "Key type")

	cmd.Flags().StringVar(&tagSpecifications, "tag-specifications", "", "Tag specifications (JSON)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2CreateNatGatewayCmd() *cobra.Command {
	var allocationId string
	var availabilityMode string
	var availabilityZoneAddresses string
	var clientToken string
	var connectivityType string
	var dryRun bool
	var privateIpAddress string
	var secondaryAllocationIds []string
	var secondaryPrivateIpAddressCount int32
	var secondaryPrivateIpAddresses []string
	var subnetId string
	var tagSpecifications string
	var vpcId string

	cmd := &cobra.Command{
		Use:   "create-nat-gateway",
		Short: "CreateNatGateway",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.CreateNatGatewayInput{}

			if allocationId != "" {
				input.AllocationId = aws.String(allocationId)
			}

			if availabilityMode != "" {
				input.AvailabilityMode = types.AvailabilityMode(availabilityMode)
			}

			if availabilityZoneAddresses != "" {
				if err := json.Unmarshal([]byte(availabilityZoneAddresses), &input.AvailabilityZoneAddresses); err != nil {
					return fmt.Errorf("create-nat-gateway: parse --availability-zone-addresses: %w", err)
				}
			}

			if clientToken != "" {
				input.ClientToken = aws.String(clientToken)
			}

			if connectivityType != "" {
				input.ConnectivityType = types.ConnectivityType(connectivityType)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if privateIpAddress != "" {
				input.PrivateIpAddress = aws.String(privateIpAddress)
			}

			if len(secondaryAllocationIds) > 0 {
				input.SecondaryAllocationIds = secondaryAllocationIds
			}

			if secondaryPrivateIpAddressCount != 0 {
				input.SecondaryPrivateIpAddressCount = aws.Int32(secondaryPrivateIpAddressCount)
			}

			if len(secondaryPrivateIpAddresses) > 0 {
				input.SecondaryPrivateIpAddresses = secondaryPrivateIpAddresses
			}

			if subnetId != "" {
				input.SubnetId = aws.String(subnetId)
			}

			if tagSpecifications != "" {
				if err := json.Unmarshal([]byte(tagSpecifications), &input.TagSpecifications); err != nil {
					return fmt.Errorf("create-nat-gateway: parse --tag-specifications: %w", err)
				}
			}

			if vpcId != "" {
				input.VpcId = aws.String(vpcId)
			}

			out, err := client.CreateNatGateway(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-nat-gateway failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&allocationId, "allocation-id", "", "Allocation id")

	cmd.Flags().StringVar(&availabilityMode, "availability-mode", "", "Availability mode")

	cmd.Flags().StringVar(&availabilityZoneAddresses, "availability-zone-addresses", "", "Availability zone addresses (JSON)")

	cmd.Flags().StringVar(&clientToken, "client-token", "", "Client token")

	cmd.Flags().StringVar(&connectivityType, "connectivity-type", "", "Connectivity type")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&privateIpAddress, "private-ip-address", "", "Private ip address")

	cmd.Flags().StringArrayVar(&secondaryAllocationIds, "secondary-allocation-ids", nil, "Secondary allocation ids")

	cmd.Flags().Int32Var(&secondaryPrivateIpAddressCount, "secondary-private-ip-address-count", 0, "Secondary private ip address count")

	cmd.Flags().StringArrayVar(&secondaryPrivateIpAddresses, "secondary-private-ip-addresses", nil, "Secondary private ip addresses")

	cmd.Flags().StringVar(&subnetId, "subnet-id", "", "Subnet id")

	cmd.Flags().StringVar(&tagSpecifications, "tag-specifications", "", "Tag specifications (JSON)")

	cmd.Flags().StringVar(&vpcId, "vpc-id", "", "Vpc id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2CreateRouteCmd() *cobra.Command {
	var routeTableId string
	var carrierGatewayId string
	var coreNetworkArn string
	var destinationCidrBlock string
	var destinationIpv6CidrBlock string
	var destinationPrefixListId string
	var dryRun bool
	var egressOnlyInternetGatewayId string
	var gatewayId string
	var instanceId string
	var localGatewayId string
	var natGatewayId string
	var networkInterfaceId string
	var odbNetworkArn string
	var transitGatewayId string
	var vpcEndpointId string
	var vpcPeeringConnectionId string

	cmd := &cobra.Command{
		Use:   "create-route",
		Short: "CreateRoute",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.CreateRouteInput{}

			if routeTableId != "" {
				input.RouteTableId = aws.String(routeTableId)
			}

			if carrierGatewayId != "" {
				input.CarrierGatewayId = aws.String(carrierGatewayId)
			}

			if coreNetworkArn != "" {
				input.CoreNetworkArn = aws.String(coreNetworkArn)
			}

			if destinationCidrBlock != "" {
				input.DestinationCidrBlock = aws.String(destinationCidrBlock)
			}

			if destinationIpv6CidrBlock != "" {
				input.DestinationIpv6CidrBlock = aws.String(destinationIpv6CidrBlock)
			}

			if destinationPrefixListId != "" {
				input.DestinationPrefixListId = aws.String(destinationPrefixListId)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if egressOnlyInternetGatewayId != "" {
				input.EgressOnlyInternetGatewayId = aws.String(egressOnlyInternetGatewayId)
			}

			if gatewayId != "" {
				input.GatewayId = aws.String(gatewayId)
			}

			if instanceId != "" {
				input.InstanceId = aws.String(instanceId)
			}

			if localGatewayId != "" {
				input.LocalGatewayId = aws.String(localGatewayId)
			}

			if natGatewayId != "" {
				input.NatGatewayId = aws.String(natGatewayId)
			}

			if networkInterfaceId != "" {
				input.NetworkInterfaceId = aws.String(networkInterfaceId)
			}

			if odbNetworkArn != "" {
				input.OdbNetworkArn = aws.String(odbNetworkArn)
			}

			if transitGatewayId != "" {
				input.TransitGatewayId = aws.String(transitGatewayId)
			}

			if vpcEndpointId != "" {
				input.VpcEndpointId = aws.String(vpcEndpointId)
			}

			if vpcPeeringConnectionId != "" {
				input.VpcPeeringConnectionId = aws.String(vpcPeeringConnectionId)
			}

			out, err := client.CreateRoute(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-route failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&routeTableId, "route-table-id", "", "Route table id")

	cmd.Flags().StringVar(&carrierGatewayId, "carrier-gateway-id", "", "Carrier gateway id")

	cmd.Flags().StringVar(&coreNetworkArn, "core-network-arn", "", "Core network arn")

	cmd.Flags().StringVar(&destinationCidrBlock, "destination-cidr-block", "", "Destination cidr block")

	cmd.Flags().StringVar(&destinationIpv6CidrBlock, "destination-ipv-6-cidr-block", "", "Destination ipv 6 cidr block")

	cmd.Flags().StringVar(&destinationPrefixListId, "destination-prefix-list-id", "", "Destination prefix list id")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&egressOnlyInternetGatewayId, "egress-only-internet-gateway-id", "", "Egress only internet gateway id")

	cmd.Flags().StringVar(&gatewayId, "gateway-id", "", "Gateway id")

	cmd.Flags().StringVar(&instanceId, "instance-id", "", "Instance id")

	cmd.Flags().StringVar(&localGatewayId, "local-gateway-id", "", "Local gateway id")

	cmd.Flags().StringVar(&natGatewayId, "nat-gateway-id", "", "Nat gateway id")

	cmd.Flags().StringVar(&networkInterfaceId, "network-interface-id", "", "Network interface id")

	cmd.Flags().StringVar(&odbNetworkArn, "odb-network-arn", "", "Odb network arn")

	cmd.Flags().StringVar(&transitGatewayId, "transit-gateway-id", "", "Transit gateway id")

	cmd.Flags().StringVar(&vpcEndpointId, "vpc-endpoint-id", "", "Vpc endpoint id")

	cmd.Flags().StringVar(&vpcPeeringConnectionId, "vpc-peering-connection-id", "", "Vpc peering connection id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2CreateRouteTableCmd() *cobra.Command {
	var vpcId string
	var clientToken string
	var dryRun bool
	var tagSpecifications string

	cmd := &cobra.Command{
		Use:   "create-route-table",
		Short: "CreateRouteTable",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.CreateRouteTableInput{}

			if vpcId != "" {
				input.VpcId = aws.String(vpcId)
			}

			if clientToken != "" {
				input.ClientToken = aws.String(clientToken)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if tagSpecifications != "" {
				if err := json.Unmarshal([]byte(tagSpecifications), &input.TagSpecifications); err != nil {
					return fmt.Errorf("create-route-table: parse --tag-specifications: %w", err)
				}
			}

			out, err := client.CreateRouteTable(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-route-table failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&vpcId, "vpc-id", "", "Vpc id")

	cmd.Flags().StringVar(&clientToken, "client-token", "", "Client token")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&tagSpecifications, "tag-specifications", "", "Tag specifications (JSON)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2CreateSecurityGroupCmd() *cobra.Command {
	var description string
	var groupName string
	var dryRun bool
	var tagSpecifications string
	var vpcId string

	cmd := &cobra.Command{
		Use:   "create-security-group",
		Short: "CreateSecurityGroup",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.CreateSecurityGroupInput{}

			if description != "" {
				input.Description = aws.String(description)
			}

			if groupName != "" {
				input.GroupName = aws.String(groupName)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if tagSpecifications != "" {
				if err := json.Unmarshal([]byte(tagSpecifications), &input.TagSpecifications); err != nil {
					return fmt.Errorf("create-security-group: parse --tag-specifications: %w", err)
				}
			}

			if vpcId != "" {
				input.VpcId = aws.String(vpcId)
			}

			out, err := client.CreateSecurityGroup(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-security-group failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().StringVar(&groupName, "group-name", "", "Group name")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&tagSpecifications, "tag-specifications", "", "Tag specifications (JSON)")

	cmd.Flags().StringVar(&vpcId, "vpc-id", "", "Vpc id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2CreateSubnetCmd() *cobra.Command {
	var vpcId string
	var availabilityZone string
	var availabilityZoneId string
	var cidrBlock string
	var dryRun bool
	var ipv4IpamPoolId string
	var ipv4NetmaskLength int32
	var ipv6CidrBlock string
	var ipv6IpamPoolId string
	var ipv6Native bool
	var ipv6NetmaskLength int32
	var outpostArn string
	var tagSpecifications string

	cmd := &cobra.Command{
		Use:   "create-subnet",
		Short: "CreateSubnet",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.CreateSubnetInput{}

			if vpcId != "" {
				input.VpcId = aws.String(vpcId)
			}

			if availabilityZone != "" {
				input.AvailabilityZone = aws.String(availabilityZone)
			}

			if availabilityZoneId != "" {
				input.AvailabilityZoneId = aws.String(availabilityZoneId)
			}

			if cidrBlock != "" {
				input.CidrBlock = aws.String(cidrBlock)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if ipv4IpamPoolId != "" {
				input.Ipv4IpamPoolId = aws.String(ipv4IpamPoolId)
			}

			if ipv4NetmaskLength != 0 {
				input.Ipv4NetmaskLength = aws.Int32(ipv4NetmaskLength)
			}

			if ipv6CidrBlock != "" {
				input.Ipv6CidrBlock = aws.String(ipv6CidrBlock)
			}

			if ipv6IpamPoolId != "" {
				input.Ipv6IpamPoolId = aws.String(ipv6IpamPoolId)
			}

			if ipv6Native {
				input.Ipv6Native = aws.Bool(ipv6Native)
			}

			if ipv6NetmaskLength != 0 {
				input.Ipv6NetmaskLength = aws.Int32(ipv6NetmaskLength)
			}

			if outpostArn != "" {
				input.OutpostArn = aws.String(outpostArn)
			}

			if tagSpecifications != "" {
				if err := json.Unmarshal([]byte(tagSpecifications), &input.TagSpecifications); err != nil {
					return fmt.Errorf("create-subnet: parse --tag-specifications: %w", err)
				}
			}

			out, err := client.CreateSubnet(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-subnet failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&vpcId, "vpc-id", "", "Vpc id")

	cmd.Flags().StringVar(&availabilityZone, "availability-zone", "", "Availability zone")

	cmd.Flags().StringVar(&availabilityZoneId, "availability-zone-id", "", "Availability zone id")

	cmd.Flags().StringVar(&cidrBlock, "cidr-block", "", "Cidr block")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&ipv4IpamPoolId, "ipv-4-ipam-pool-id", "", "Ipv 4 ipam pool id")

	cmd.Flags().Int32Var(&ipv4NetmaskLength, "ipv-4-netmask-length", 0, "Ipv 4 netmask length")

	cmd.Flags().StringVar(&ipv6CidrBlock, "ipv-6-cidr-block", "", "Ipv 6 cidr block")

	cmd.Flags().StringVar(&ipv6IpamPoolId, "ipv-6-ipam-pool-id", "", "Ipv 6 ipam pool id")

	cmd.Flags().BoolVar(&ipv6Native, "ipv-6-native", false, "Ipv 6 native")

	cmd.Flags().Int32Var(&ipv6NetmaskLength, "ipv-6-netmask-length", 0, "Ipv 6 netmask length")

	cmd.Flags().StringVar(&outpostArn, "outpost-arn", "", "Outpost arn")

	cmd.Flags().StringVar(&tagSpecifications, "tag-specifications", "", "Tag specifications (JSON)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2CreateTagsCmd() *cobra.Command {
	var resources []string
	var tags []string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "create-tags",
		Short: "CreateTags",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.CreateTagsInput{}

			if len(resources) > 0 {
				input.Resources = resources
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-tags: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			_, err = client.CreateTags(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-tags failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&resources, "resources", nil, "Resources")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2CreateVpcCmd() *cobra.Command {
	var amazonProvidedIpv6CidrBlock bool
	var cidrBlock string
	var dryRun bool
	var instanceTenancy string
	var ipv4IpamPoolId string
	var ipv4NetmaskLength int32
	var ipv6CidrBlock string
	var ipv6CidrBlockNetworkBorderGroup string
	var ipv6IpamPoolId string
	var ipv6NetmaskLength int32
	var ipv6Pool string
	var tagSpecifications string
	var vpcEncryptionControl string

	cmd := &cobra.Command{
		Use:   "create-vpc",
		Short: "CreateVpc",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.CreateVpcInput{}

			if amazonProvidedIpv6CidrBlock {
				input.AmazonProvidedIpv6CidrBlock = aws.Bool(amazonProvidedIpv6CidrBlock)
			}

			if cidrBlock != "" {
				input.CidrBlock = aws.String(cidrBlock)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if instanceTenancy != "" {
				input.InstanceTenancy = types.Tenancy(instanceTenancy)
			}

			if ipv4IpamPoolId != "" {
				input.Ipv4IpamPoolId = aws.String(ipv4IpamPoolId)
			}

			if ipv4NetmaskLength != 0 {
				input.Ipv4NetmaskLength = aws.Int32(ipv4NetmaskLength)
			}

			if ipv6CidrBlock != "" {
				input.Ipv6CidrBlock = aws.String(ipv6CidrBlock)
			}

			if ipv6CidrBlockNetworkBorderGroup != "" {
				input.Ipv6CidrBlockNetworkBorderGroup = aws.String(ipv6CidrBlockNetworkBorderGroup)
			}

			if ipv6IpamPoolId != "" {
				input.Ipv6IpamPoolId = aws.String(ipv6IpamPoolId)
			}

			if ipv6NetmaskLength != 0 {
				input.Ipv6NetmaskLength = aws.Int32(ipv6NetmaskLength)
			}

			if ipv6Pool != "" {
				input.Ipv6Pool = aws.String(ipv6Pool)
			}

			if tagSpecifications != "" {
				if err := json.Unmarshal([]byte(tagSpecifications), &input.TagSpecifications); err != nil {
					return fmt.Errorf("create-vpc: parse --tag-specifications: %w", err)
				}
			}

			if vpcEncryptionControl != "" {
				var val types.VpcEncryptionControlConfiguration
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), vpcEncryptionControl); err != nil {
					return fmt.Errorf("create-vpc: parse --vpc-encryption-control: %w", err)
				}
				input.VpcEncryptionControl = &val
			}

			out, err := client.CreateVpc(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-vpc failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&amazonProvidedIpv6CidrBlock, "amazon-provided-ipv-6-cidr-block", false, "Amazon provided ipv 6 cidr block")

	cmd.Flags().StringVar(&cidrBlock, "cidr-block", "", "Cidr block")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&instanceTenancy, "instance-tenancy", "", "Instance tenancy")

	cmd.Flags().StringVar(&ipv4IpamPoolId, "ipv-4-ipam-pool-id", "", "Ipv 4 ipam pool id")

	cmd.Flags().Int32Var(&ipv4NetmaskLength, "ipv-4-netmask-length", 0, "Ipv 4 netmask length")

	cmd.Flags().StringVar(&ipv6CidrBlock, "ipv-6-cidr-block", "", "Ipv 6 cidr block")

	cmd.Flags().StringVar(&ipv6CidrBlockNetworkBorderGroup, "ipv-6-cidr-block-network-border-group", "", "Ipv 6 cidr block network border group")

	cmd.Flags().StringVar(&ipv6IpamPoolId, "ipv-6-ipam-pool-id", "", "Ipv 6 ipam pool id")

	cmd.Flags().Int32Var(&ipv6NetmaskLength, "ipv-6-netmask-length", 0, "Ipv 6 netmask length")

	cmd.Flags().StringVar(&ipv6Pool, "ipv-6-pool", "", "Ipv 6 pool")

	cmd.Flags().StringVar(&tagSpecifications, "tag-specifications", "", "Tag specifications (JSON)")

	cmd.Flags().StringVar(&vpcEncryptionControl, "vpc-encryption-control", "", "Vpc encryption control (key=value,key2=value2)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DeleteInternetGatewayCmd() *cobra.Command {
	var internetGatewayId string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "delete-internet-gateway",
		Short: "DeleteInternetGateway",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DeleteInternetGatewayInput{}

			if internetGatewayId != "" {
				input.InternetGatewayId = aws.String(internetGatewayId)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			_, err = client.DeleteInternetGateway(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-internet-gateway failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&internetGatewayId, "internet-gateway-id", "", "Internet gateway id")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DeleteKeyPairCmd() *cobra.Command {
	var dryRun bool
	var keyName string
	var keyPairId string

	cmd := &cobra.Command{
		Use:   "delete-key-pair",
		Short: "DeleteKeyPair",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DeleteKeyPairInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if keyName != "" {
				input.KeyName = aws.String(keyName)
			}

			if keyPairId != "" {
				input.KeyPairId = aws.String(keyPairId)
			}

			out, err := client.DeleteKeyPair(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-key-pair failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&keyName, "key-name", "", "Key name")

	cmd.Flags().StringVar(&keyPairId, "key-pair-id", "", "Key pair id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DeleteSecurityGroupCmd() *cobra.Command {
	var dryRun bool
	var groupId string
	var groupName string

	cmd := &cobra.Command{
		Use:   "delete-security-group",
		Short: "DeleteSecurityGroup",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DeleteSecurityGroupInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if groupId != "" {
				input.GroupId = aws.String(groupId)
			}

			if groupName != "" {
				input.GroupName = aws.String(groupName)
			}

			out, err := client.DeleteSecurityGroup(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-security-group failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&groupId, "group-id", "", "Group id")

	cmd.Flags().StringVar(&groupName, "group-name", "", "Group name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DeleteSubnetCmd() *cobra.Command {
	var subnetId string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "delete-subnet",
		Short: "DeleteSubnet",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DeleteSubnetInput{}

			if subnetId != "" {
				input.SubnetId = aws.String(subnetId)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			_, err = client.DeleteSubnet(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-subnet failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&subnetId, "subnet-id", "", "Subnet id")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DeleteTagsCmd() *cobra.Command {
	var resources []string
	var dryRun bool
	var tags []string

	cmd := &cobra.Command{
		Use:   "delete-tags",
		Short: "DeleteTags",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DeleteTagsInput{}

			if len(resources) > 0 {
				input.Resources = resources
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("delete-tags: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			_, err = client.DeleteTags(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-tags failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&resources, "resources", nil, "Resources")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DeleteVpcCmd() *cobra.Command {
	var vpcId string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "delete-vpc",
		Short: "DeleteVpc",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DeleteVpcInput{}

			if vpcId != "" {
				input.VpcId = aws.String(vpcId)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			_, err = client.DeleteVpc(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-vpc failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&vpcId, "vpc-id", "", "Vpc id")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeInstancesCmd() *cobra.Command {
	var dryRun bool
	var filters string
	var includeManagedResources bool
	var instanceIds []string
	var maxResults int32
	var nextToken string

	cmd := &cobra.Command{
		Use:   "describe-instances",
		Short: "DescribeInstances",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeInstancesInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("describe-instances: parse --filters: %w", err)
				}
			}

			if includeManagedResources {
				input.IncludeManagedResources = aws.Bool(includeManagedResources)
			}

			if len(instanceIds) > 0 {
				input.InstanceIds = instanceIds
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.DescribeInstances(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-instances failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().BoolVar(&includeManagedResources, "include-managed-resources", false, "Include managed resources")

	cmd.Flags().StringArrayVar(&instanceIds, "instance-ids", nil, "Instance ids")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeInternetGatewaysCmd() *cobra.Command {
	var dryRun bool
	var filters string
	var internetGatewayIds []string
	var maxResults int32
	var nextToken string

	cmd := &cobra.Command{
		Use:   "describe-internet-gateways",
		Short: "DescribeInternetGateways",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeInternetGatewaysInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("describe-internet-gateways: parse --filters: %w", err)
				}
			}

			if len(internetGatewayIds) > 0 {
				input.InternetGatewayIds = internetGatewayIds
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.DescribeInternetGateways(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-internet-gateways failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().StringArrayVar(&internetGatewayIds, "internet-gateway-ids", nil, "Internet gateway ids")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeKeyPairsCmd() *cobra.Command {
	var dryRun bool
	var filters string
	var includePublicKey bool
	var keyNames []string
	var keyPairIds []string

	cmd := &cobra.Command{
		Use:   "describe-key-pairs",
		Short: "DescribeKeyPairs",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeKeyPairsInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("describe-key-pairs: parse --filters: %w", err)
				}
			}

			if includePublicKey {
				input.IncludePublicKey = aws.Bool(includePublicKey)
			}

			if len(keyNames) > 0 {
				input.KeyNames = keyNames
			}

			if len(keyPairIds) > 0 {
				input.KeyPairIds = keyPairIds
			}

			out, err := client.DescribeKeyPairs(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-key-pairs failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().BoolVar(&includePublicKey, "include-public-key", false, "Include public key")

	cmd.Flags().StringArrayVar(&keyNames, "key-names", nil, "Key names")

	cmd.Flags().StringArrayVar(&keyPairIds, "key-pair-ids", nil, "Key pair ids")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeNatGatewaysCmd() *cobra.Command {
	var dryRun bool
	var filter string
	var maxResults int32
	var natGatewayIds []string
	var nextToken string

	cmd := &cobra.Command{
		Use:   "describe-nat-gateways",
		Short: "DescribeNatGateways",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeNatGatewaysInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if filter != "" {
				if err := json.Unmarshal([]byte(filter), &input.Filter); err != nil {
					return fmt.Errorf("describe-nat-gateways: parse --filter: %w", err)
				}
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if len(natGatewayIds) > 0 {
				input.NatGatewayIds = natGatewayIds
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.DescribeNatGateways(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-nat-gateways failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&filter, "filter", "", "Filter (JSON)")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringArrayVar(&natGatewayIds, "nat-gateway-ids", nil, "Nat gateway ids")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeNetworkInterfacesCmd() *cobra.Command {
	var dryRun bool
	var filters string
	var includeManagedResources bool
	var maxResults int32
	var networkInterfaceIds []string
	var nextToken string

	cmd := &cobra.Command{
		Use:   "describe-network-interfaces",
		Short: "DescribeNetworkInterfaces",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeNetworkInterfacesInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("describe-network-interfaces: parse --filters: %w", err)
				}
			}

			if includeManagedResources {
				input.IncludeManagedResources = aws.Bool(includeManagedResources)
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if len(networkInterfaceIds) > 0 {
				input.NetworkInterfaceIds = networkInterfaceIds
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.DescribeNetworkInterfaces(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-network-interfaces failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().BoolVar(&includeManagedResources, "include-managed-resources", false, "Include managed resources")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringArrayVar(&networkInterfaceIds, "network-interface-ids", nil, "Network interface ids")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeRouteTablesCmd() *cobra.Command {
	var dryRun bool
	var filters string
	var maxResults int32
	var nextToken string
	var routeTableIds []string

	cmd := &cobra.Command{
		Use:   "describe-route-tables",
		Short: "DescribeRouteTables",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeRouteTablesInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("describe-route-tables: parse --filters: %w", err)
				}
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if len(routeTableIds) > 0 {
				input.RouteTableIds = routeTableIds
			}

			out, err := client.DescribeRouteTables(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-route-tables failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringArrayVar(&routeTableIds, "route-table-ids", nil, "Route table ids")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeSecurityGroupsCmd() *cobra.Command {
	var dryRun bool
	var filters string
	var groupIds []string
	var groupNames []string
	var maxResults int32
	var nextToken string

	cmd := &cobra.Command{
		Use:   "describe-security-groups",
		Short: "DescribeSecurityGroups",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeSecurityGroupsInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("describe-security-groups: parse --filters: %w", err)
				}
			}

			if len(groupIds) > 0 {
				input.GroupIds = groupIds
			}

			if len(groupNames) > 0 {
				input.GroupNames = groupNames
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.DescribeSecurityGroups(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-security-groups failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().StringArrayVar(&groupIds, "group-ids", nil, "Group ids")

	cmd.Flags().StringArrayVar(&groupNames, "group-names", nil, "Group names")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeSubnetsCmd() *cobra.Command {
	var dryRun bool
	var filters string
	var maxResults int32
	var nextToken string
	var subnetIds []string

	cmd := &cobra.Command{
		Use:   "describe-subnets",
		Short: "DescribeSubnets",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeSubnetsInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("describe-subnets: parse --filters: %w", err)
				}
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if len(subnetIds) > 0 {
				input.SubnetIds = subnetIds
			}

			out, err := client.DescribeSubnets(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-subnets failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringArrayVar(&subnetIds, "subnet-ids", nil, "Subnet ids")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeTagsCmd() *cobra.Command {
	var dryRun bool
	var filters string
	var maxResults int32
	var nextToken string

	cmd := &cobra.Command{
		Use:   "describe-tags",
		Short: "DescribeTags",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeTagsInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("describe-tags: parse --filters: %w", err)
				}
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.DescribeTags(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-tags failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeVpcAttributeCmd() *cobra.Command {
	var attribute string
	var vpcId string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "describe-vpc-attribute",
		Short: "DescribeVpcAttribute",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeVpcAttributeInput{}

			if attribute != "" {
				input.Attribute = types.VpcAttributeName(attribute)
			}

			if vpcId != "" {
				input.VpcId = aws.String(vpcId)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			out, err := client.DescribeVpcAttribute(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-vpc-attribute failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&attribute, "attribute", "", "Attribute")

	cmd.Flags().StringVar(&vpcId, "vpc-id", "", "Vpc id")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DescribeVpcsCmd() *cobra.Command {
	var dryRun bool
	var filters string
	var maxResults int32
	var nextToken string
	var vpcIds []string

	cmd := &cobra.Command{
		Use:   "describe-vpcs",
		Short: "DescribeVpcs",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DescribeVpcsInput{}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if filters != "" {
				if err := json.Unmarshal([]byte(filters), &input.Filters); err != nil {
					return fmt.Errorf("describe-vpcs: parse --filters: %w", err)
				}
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if len(vpcIds) > 0 {
				input.VpcIds = vpcIds
			}

			out, err := client.DescribeVpcs(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-vpcs failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().StringVar(&filters, "filters", "", "Filters (JSON)")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringArrayVar(&vpcIds, "vpc-ids", nil, "Vpc ids")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2DetachInternetGatewayCmd() *cobra.Command {
	var internetGatewayId string
	var vpcId string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "detach-internet-gateway",
		Short: "DetachInternetGateway",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.DetachInternetGatewayInput{}

			if internetGatewayId != "" {
				input.InternetGatewayId = aws.String(internetGatewayId)
			}

			if vpcId != "" {
				input.VpcId = aws.String(vpcId)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			_, err = client.DetachInternetGateway(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("detach-internet-gateway failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&internetGatewayId, "internet-gateway-id", "", "Internet gateway id")

	cmd.Flags().StringVar(&vpcId, "vpc-id", "", "Vpc id")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2ModifySubnetAttributeCmd() *cobra.Command {
	var subnetId string
	var assignIpv6AddressOnCreation string
	var customerOwnedIpv4Pool string
	var disableLniAtDeviceIndex string
	var enableDns64 string
	var enableLniAtDeviceIndex int32
	var enableResourceNameDnsAAAARecordOnLaunch string
	var enableResourceNameDnsARecordOnLaunch string
	var mapCustomerOwnedIpOnLaunch string
	var mapPublicIpOnLaunch string
	var privateDnsHostnameTypeOnLaunch string

	cmd := &cobra.Command{
		Use:   "modify-subnet-attribute",
		Short: "ModifySubnetAttribute",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.ModifySubnetAttributeInput{}

			if subnetId != "" {
				input.SubnetId = aws.String(subnetId)
			}

			if assignIpv6AddressOnCreation != "" {
				var val types.AttributeBooleanValue
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), assignIpv6AddressOnCreation); err != nil {
					return fmt.Errorf("modify-subnet-attribute: parse --assign-ipv-6-address-on-creation: %w", err)
				}
				input.AssignIpv6AddressOnCreation = &val
			}

			if customerOwnedIpv4Pool != "" {
				input.CustomerOwnedIpv4Pool = aws.String(customerOwnedIpv4Pool)
			}

			if disableLniAtDeviceIndex != "" {
				var val types.AttributeBooleanValue
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), disableLniAtDeviceIndex); err != nil {
					return fmt.Errorf("modify-subnet-attribute: parse --disable-lni-at-device-index: %w", err)
				}
				input.DisableLniAtDeviceIndex = &val
			}

			if enableDns64 != "" {
				var val types.AttributeBooleanValue
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), enableDns64); err != nil {
					return fmt.Errorf("modify-subnet-attribute: parse --enable-dns-64: %w", err)
				}
				input.EnableDns64 = &val
			}

			if enableLniAtDeviceIndex != 0 {
				input.EnableLniAtDeviceIndex = aws.Int32(enableLniAtDeviceIndex)
			}

			if enableResourceNameDnsAAAARecordOnLaunch != "" {
				var val types.AttributeBooleanValue
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), enableResourceNameDnsAAAARecordOnLaunch); err != nil {
					return fmt.Errorf("modify-subnet-attribute: parse --enable-resource-name-dns-a-a-a-a-record-on-launch: %w", err)
				}
				input.EnableResourceNameDnsAAAARecordOnLaunch = &val
			}

			if enableResourceNameDnsARecordOnLaunch != "" {
				var val types.AttributeBooleanValue
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), enableResourceNameDnsARecordOnLaunch); err != nil {
					return fmt.Errorf("modify-subnet-attribute: parse --enable-resource-name-dns-a-record-on-launch: %w", err)
				}
				input.EnableResourceNameDnsARecordOnLaunch = &val
			}

			if mapCustomerOwnedIpOnLaunch != "" {
				var val types.AttributeBooleanValue
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), mapCustomerOwnedIpOnLaunch); err != nil {
					return fmt.Errorf("modify-subnet-attribute: parse --map-customer-owned-ip-on-launch: %w", err)
				}
				input.MapCustomerOwnedIpOnLaunch = &val
			}

			if mapPublicIpOnLaunch != "" {
				var val types.AttributeBooleanValue
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), mapPublicIpOnLaunch); err != nil {
					return fmt.Errorf("modify-subnet-attribute: parse --map-public-ip-on-launch: %w", err)
				}
				input.MapPublicIpOnLaunch = &val
			}

			if privateDnsHostnameTypeOnLaunch != "" {
				input.PrivateDnsHostnameTypeOnLaunch = types.HostnameType(privateDnsHostnameTypeOnLaunch)
			}

			_, err = client.ModifySubnetAttribute(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("modify-subnet-attribute failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&subnetId, "subnet-id", "", "Subnet id")

	cmd.Flags().StringVar(&assignIpv6AddressOnCreation, "assign-ipv-6-address-on-creation", "", "Assign ipv 6 address on creation (key=value,key2=value2)")

	cmd.Flags().StringVar(&customerOwnedIpv4Pool, "customer-owned-ipv-4-pool", "", "Customer owned ipv 4 pool")

	cmd.Flags().StringVar(&disableLniAtDeviceIndex, "disable-lni-at-device-index", "", "Disable lni at device index (key=value,key2=value2)")

	cmd.Flags().StringVar(&enableDns64, "enable-dns-64", "", "Enable dns 64 (key=value,key2=value2)")

	cmd.Flags().Int32Var(&enableLniAtDeviceIndex, "enable-lni-at-device-index", 0, "Enable lni at device index")

	cmd.Flags().StringVar(&enableResourceNameDnsAAAARecordOnLaunch, "enable-resource-name-dns-a-a-a-a-record-on-launch", "", "Enable resource name dns a a a a record on launch (key=value,key2=value2)")

	cmd.Flags().StringVar(&enableResourceNameDnsARecordOnLaunch, "enable-resource-name-dns-a-record-on-launch", "", "Enable resource name dns a record on launch (key=value,key2=value2)")

	cmd.Flags().StringVar(&mapCustomerOwnedIpOnLaunch, "map-customer-owned-ip-on-launch", "", "Map customer owned ip on launch (key=value,key2=value2)")

	cmd.Flags().StringVar(&mapPublicIpOnLaunch, "map-public-ip-on-launch", "", "Map public ip on launch (key=value,key2=value2)")

	cmd.Flags().StringVar(&privateDnsHostnameTypeOnLaunch, "private-dns-hostname-type-on-launch", "", "Private dns hostname type on launch")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2ModifyVpcAttributeCmd() *cobra.Command {
	var vpcId string
	var enableDnsHostnames string
	var enableDnsSupport string
	var enableNetworkAddressUsageMetrics string

	cmd := &cobra.Command{
		Use:   "modify-vpc-attribute",
		Short: "ModifyVpcAttribute",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.ModifyVpcAttributeInput{}

			if vpcId != "" {
				input.VpcId = aws.String(vpcId)
			}

			if enableDnsHostnames != "" {
				var val types.AttributeBooleanValue
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), enableDnsHostnames); err != nil {
					return fmt.Errorf("modify-vpc-attribute: parse --enable-dns-hostnames: %w", err)
				}
				input.EnableDnsHostnames = &val
			}

			if enableDnsSupport != "" {
				var val types.AttributeBooleanValue
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), enableDnsSupport); err != nil {
					return fmt.Errorf("modify-vpc-attribute: parse --enable-dns-support: %w", err)
				}
				input.EnableDnsSupport = &val
			}

			if enableNetworkAddressUsageMetrics != "" {
				var val types.AttributeBooleanValue
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), enableNetworkAddressUsageMetrics); err != nil {
					return fmt.Errorf("modify-vpc-attribute: parse --enable-network-address-usage-metrics: %w", err)
				}
				input.EnableNetworkAddressUsageMetrics = &val
			}

			_, err = client.ModifyVpcAttribute(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("modify-vpc-attribute failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&vpcId, "vpc-id", "", "Vpc id")

	cmd.Flags().StringVar(&enableDnsHostnames, "enable-dns-hostnames", "", "Enable dns hostnames (key=value,key2=value2)")

	cmd.Flags().StringVar(&enableDnsSupport, "enable-dns-support", "", "Enable dns support (key=value,key2=value2)")

	cmd.Flags().StringVar(&enableNetworkAddressUsageMetrics, "enable-network-address-usage-metrics", "", "Enable network address usage metrics (key=value,key2=value2)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2RevokeSecurityGroupEgressCmd() *cobra.Command {
	var groupId string
	var cidrIp string
	var dryRun bool
	var fromPort int32
	var ipPermissions string
	var ipProtocol string
	var securityGroupRuleIds []string
	var sourceSecurityGroupName string
	var sourceSecurityGroupOwnerId string
	var toPort int32

	cmd := &cobra.Command{
		Use:   "revoke-security-group-egress",
		Short: "RevokeSecurityGroupEgress",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.RevokeSecurityGroupEgressInput{}

			if groupId != "" {
				input.GroupId = aws.String(groupId)
			}

			if cidrIp != "" {
				input.CidrIp = aws.String(cidrIp)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if fromPort != 0 {
				input.FromPort = aws.Int32(fromPort)
			}

			if ipPermissions != "" {
				if err := json.Unmarshal([]byte(ipPermissions), &input.IpPermissions); err != nil {
					return fmt.Errorf("revoke-security-group-egress: parse --ip-permissions: %w", err)
				}
			}

			if ipProtocol != "" {
				input.IpProtocol = aws.String(ipProtocol)
			}

			if len(securityGroupRuleIds) > 0 {
				input.SecurityGroupRuleIds = securityGroupRuleIds
			}

			if sourceSecurityGroupName != "" {
				input.SourceSecurityGroupName = aws.String(sourceSecurityGroupName)
			}

			if sourceSecurityGroupOwnerId != "" {
				input.SourceSecurityGroupOwnerId = aws.String(sourceSecurityGroupOwnerId)
			}

			if toPort != 0 {
				input.ToPort = aws.Int32(toPort)
			}

			out, err := client.RevokeSecurityGroupEgress(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("revoke-security-group-egress failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&groupId, "group-id", "", "Group id")

	cmd.Flags().StringVar(&cidrIp, "cidr-ip", "", "Cidr ip")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().Int32Var(&fromPort, "from-port", 0, "From port")

	cmd.Flags().StringVar(&ipPermissions, "ip-permissions", "", "Ip permissions (JSON)")

	cmd.Flags().StringVar(&ipProtocol, "ip-protocol", "", "Ip protocol")

	cmd.Flags().StringArrayVar(&securityGroupRuleIds, "security-group-rule-ids", nil, "Security group rule ids")

	cmd.Flags().StringVar(&sourceSecurityGroupName, "source-security-group-name", "", "Source security group name")

	cmd.Flags().StringVar(&sourceSecurityGroupOwnerId, "source-security-group-owner-id", "", "Source security group owner id")

	cmd.Flags().Int32Var(&toPort, "to-port", 0, "To port")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2RevokeSecurityGroupIngressCmd() *cobra.Command {
	var cidrIp string
	var dryRun bool
	var fromPort int32
	var groupId string
	var groupName string
	var ipPermissions string
	var ipProtocol string
	var securityGroupRuleIds []string
	var sourceSecurityGroupName string
	var sourceSecurityGroupOwnerId string
	var toPort int32

	cmd := &cobra.Command{
		Use:   "revoke-security-group-ingress",
		Short: "RevokeSecurityGroupIngress",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.RevokeSecurityGroupIngressInput{}

			if cidrIp != "" {
				input.CidrIp = aws.String(cidrIp)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if fromPort != 0 {
				input.FromPort = aws.Int32(fromPort)
			}

			if groupId != "" {
				input.GroupId = aws.String(groupId)
			}

			if groupName != "" {
				input.GroupName = aws.String(groupName)
			}

			if ipPermissions != "" {
				if err := json.Unmarshal([]byte(ipPermissions), &input.IpPermissions); err != nil {
					return fmt.Errorf("revoke-security-group-ingress: parse --ip-permissions: %w", err)
				}
			}

			if ipProtocol != "" {
				input.IpProtocol = aws.String(ipProtocol)
			}

			if len(securityGroupRuleIds) > 0 {
				input.SecurityGroupRuleIds = securityGroupRuleIds
			}

			if sourceSecurityGroupName != "" {
				input.SourceSecurityGroupName = aws.String(sourceSecurityGroupName)
			}

			if sourceSecurityGroupOwnerId != "" {
				input.SourceSecurityGroupOwnerId = aws.String(sourceSecurityGroupOwnerId)
			}

			if toPort != 0 {
				input.ToPort = aws.Int32(toPort)
			}

			out, err := client.RevokeSecurityGroupIngress(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("revoke-security-group-ingress failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&cidrIp, "cidr-ip", "", "Cidr ip")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().Int32Var(&fromPort, "from-port", 0, "From port")

	cmd.Flags().StringVar(&groupId, "group-id", "", "Group id")

	cmd.Flags().StringVar(&groupName, "group-name", "", "Group name")

	cmd.Flags().StringVar(&ipPermissions, "ip-permissions", "", "Ip permissions (JSON)")

	cmd.Flags().StringVar(&ipProtocol, "ip-protocol", "", "Ip protocol")

	cmd.Flags().StringArrayVar(&securityGroupRuleIds, "security-group-rule-ids", nil, "Security group rule ids")

	cmd.Flags().StringVar(&sourceSecurityGroupName, "source-security-group-name", "", "Source security group name")

	cmd.Flags().StringVar(&sourceSecurityGroupOwnerId, "source-security-group-owner-id", "", "Source security group owner id")

	cmd.Flags().Int32Var(&toPort, "to-port", 0, "To port")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2RunInstancesCmd() *cobra.Command {
	var maxCount int32
	var minCount int32
	var additionalInfo string
	var blockDeviceMappings string
	var capacityReservationSpecification string
	var clientToken string
	var cpuOptions string
	var creditSpecification string
	var disableApiStop bool
	var disableApiTermination bool
	var dryRun bool
	var ebsOptimized bool
	var elasticGpuSpecification []string
	var elasticInferenceAccelerators []string
	var enablePrimaryIpv6 bool
	var enclaveOptions string
	var hibernationOptions string
	var iamInstanceProfile string
	var imageId string
	var instanceInitiatedShutdownBehavior string
	var instanceMarketOptions string
	var instanceType string
	var ipv6AddressCount int32
	var ipv6Addresses []string
	var kernelId string
	var keyName string
	var launchTemplate string
	var licenseSpecifications []string
	var maintenanceOptions string
	var metadataOptions string
	var monitoring string
	var networkInterfaces string
	var networkPerformanceOptions string
	var operator string
	var placement string
	var privateDnsNameOptions string
	var privateIpAddress string
	var ramdiskId string
	var secondaryInterfaces string
	var securityGroupIds []string
	var securityGroups []string
	var subnetId string
	var tagSpecifications string
	var userData string

	cmd := &cobra.Command{
		Use:   "run-instances",
		Short: "RunInstances",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.RunInstancesInput{}

			if maxCount != 0 {
				input.MaxCount = aws.Int32(maxCount)
			}

			if minCount != 0 {
				input.MinCount = aws.Int32(minCount)
			}

			if additionalInfo != "" {
				input.AdditionalInfo = aws.String(additionalInfo)
			}

			if blockDeviceMappings != "" {
				if err := json.Unmarshal([]byte(blockDeviceMappings), &input.BlockDeviceMappings); err != nil {
					return fmt.Errorf("run-instances: parse --block-device-mappings: %w", err)
				}
			}

			if capacityReservationSpecification != "" {
				if err := json.Unmarshal([]byte(capacityReservationSpecification), &input.CapacityReservationSpecification); err != nil {
					return fmt.Errorf("run-instances: parse --capacity-reservation-specification: %w", err)
				}
			}

			if clientToken != "" {
				input.ClientToken = aws.String(clientToken)
			}

			if cpuOptions != "" {
				var val types.CpuOptionsRequest
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), cpuOptions); err != nil {
					return fmt.Errorf("run-instances: parse --cpu-options: %w", err)
				}
				input.CpuOptions = &val
			}

			if creditSpecification != "" {
				var val types.CreditSpecificationRequest
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), creditSpecification); err != nil {
					return fmt.Errorf("run-instances: parse --credit-specification: %w", err)
				}
				input.CreditSpecification = &val
			}

			if disableApiStop {
				input.DisableApiStop = aws.Bool(disableApiStop)
			}

			if disableApiTermination {
				input.DisableApiTermination = aws.Bool(disableApiTermination)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if ebsOptimized {
				input.EbsOptimized = aws.Bool(ebsOptimized)
			}

			for _, raw := range elasticGpuSpecification {
				var val types.ElasticGpuSpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("run-instances: parse --elastic-gpu-specification: %w", err)
				}
				input.ElasticGpuSpecification = append(input.ElasticGpuSpecification, val)
			}

			for _, raw := range elasticInferenceAccelerators {
				var val types.ElasticInferenceAccelerator
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("run-instances: parse --elastic-inference-accelerators: %w", err)
				}
				input.ElasticInferenceAccelerators = append(input.ElasticInferenceAccelerators, val)
			}

			if enablePrimaryIpv6 {
				input.EnablePrimaryIpv6 = aws.Bool(enablePrimaryIpv6)
			}

			if enclaveOptions != "" {
				var val types.EnclaveOptionsRequest
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), enclaveOptions); err != nil {
					return fmt.Errorf("run-instances: parse --enclave-options: %w", err)
				}
				input.EnclaveOptions = &val
			}

			if hibernationOptions != "" {
				var val types.HibernationOptionsRequest
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), hibernationOptions); err != nil {
					return fmt.Errorf("run-instances: parse --hibernation-options: %w", err)
				}
				input.HibernationOptions = &val
			}

			if iamInstanceProfile != "" {
				var val types.IamInstanceProfileSpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), iamInstanceProfile); err != nil {
					return fmt.Errorf("run-instances: parse --iam-instance-profile: %w", err)
				}
				input.IamInstanceProfile = &val
			}

			if imageId != "" {
				input.ImageId = aws.String(imageId)
			}

			if instanceInitiatedShutdownBehavior != "" {
				input.InstanceInitiatedShutdownBehavior = types.ShutdownBehavior(instanceInitiatedShutdownBehavior)
			}

			if instanceMarketOptions != "" {
				if err := json.Unmarshal([]byte(instanceMarketOptions), &input.InstanceMarketOptions); err != nil {
					return fmt.Errorf("run-instances: parse --instance-market-options: %w", err)
				}
			}

			if instanceType != "" {
				input.InstanceType = types.InstanceType(instanceType)
			}

			if ipv6AddressCount != 0 {
				input.Ipv6AddressCount = aws.Int32(ipv6AddressCount)
			}

			for _, raw := range ipv6Addresses {
				var val types.InstanceIpv6Address
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("run-instances: parse --ipv-6-addresses: %w", err)
				}
				input.Ipv6Addresses = append(input.Ipv6Addresses, val)
			}

			if kernelId != "" {
				input.KernelId = aws.String(kernelId)
			}

			if keyName != "" {
				input.KeyName = aws.String(keyName)
			}

			if launchTemplate != "" {
				var val types.LaunchTemplateSpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), launchTemplate); err != nil {
					return fmt.Errorf("run-instances: parse --launch-template: %w", err)
				}
				input.LaunchTemplate = &val
			}

			for _, raw := range licenseSpecifications {
				var val types.LicenseConfigurationRequest
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("run-instances: parse --license-specifications: %w", err)
				}
				input.LicenseSpecifications = append(input.LicenseSpecifications, val)
			}

			if maintenanceOptions != "" {
				var val types.InstanceMaintenanceOptionsRequest
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), maintenanceOptions); err != nil {
					return fmt.Errorf("run-instances: parse --maintenance-options: %w", err)
				}
				input.MaintenanceOptions = &val
			}

			if metadataOptions != "" {
				var val types.InstanceMetadataOptionsRequest
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), metadataOptions); err != nil {
					return fmt.Errorf("run-instances: parse --metadata-options: %w", err)
				}
				input.MetadataOptions = &val
			}

			if monitoring != "" {
				var val types.RunInstancesMonitoringEnabled
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), monitoring); err != nil {
					return fmt.Errorf("run-instances: parse --monitoring: %w", err)
				}
				input.Monitoring = &val
			}

			if networkInterfaces != "" {
				if err := json.Unmarshal([]byte(networkInterfaces), &input.NetworkInterfaces); err != nil {
					return fmt.Errorf("run-instances: parse --network-interfaces: %w", err)
				}
			}

			if networkPerformanceOptions != "" {
				var val types.InstanceNetworkPerformanceOptionsRequest
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), networkPerformanceOptions); err != nil {
					return fmt.Errorf("run-instances: parse --network-performance-options: %w", err)
				}
				input.NetworkPerformanceOptions = &val
			}

			if operator != "" {
				var val types.OperatorRequest
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), operator); err != nil {
					return fmt.Errorf("run-instances: parse --operator: %w", err)
				}
				input.Operator = &val
			}

			if placement != "" {
				var val types.Placement
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), placement); err != nil {
					return fmt.Errorf("run-instances: parse --placement: %w", err)
				}
				input.Placement = &val
			}

			if privateDnsNameOptions != "" {
				var val types.PrivateDnsNameOptionsRequest
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), privateDnsNameOptions); err != nil {
					return fmt.Errorf("run-instances: parse --private-dns-name-options: %w", err)
				}
				input.PrivateDnsNameOptions = &val
			}

			if privateIpAddress != "" {
				input.PrivateIpAddress = aws.String(privateIpAddress)
			}

			if ramdiskId != "" {
				input.RamdiskId = aws.String(ramdiskId)
			}

			if secondaryInterfaces != "" {
				if err := json.Unmarshal([]byte(secondaryInterfaces), &input.SecondaryInterfaces); err != nil {
					return fmt.Errorf("run-instances: parse --secondary-interfaces: %w", err)
				}
			}

			if len(securityGroupIds) > 0 {
				input.SecurityGroupIds = securityGroupIds
			}

			if len(securityGroups) > 0 {
				input.SecurityGroups = securityGroups
			}

			if subnetId != "" {
				input.SubnetId = aws.String(subnetId)
			}

			if tagSpecifications != "" {
				if err := json.Unmarshal([]byte(tagSpecifications), &input.TagSpecifications); err != nil {
					return fmt.Errorf("run-instances: parse --tag-specifications: %w", err)
				}
			}

			if userData != "" {
				input.UserData = aws.String(userData)
			}

			out, err := client.RunInstances(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("run-instances failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().Int32Var(&maxCount, "max-count", 0, "Max count")

	cmd.Flags().Int32Var(&minCount, "min-count", 0, "Min count")

	cmd.Flags().StringVar(&additionalInfo, "additional-info", "", "Additional info")

	cmd.Flags().StringVar(&blockDeviceMappings, "block-device-mappings", "", "Block device mappings (JSON)")

	cmd.Flags().StringVar(&capacityReservationSpecification, "capacity-reservation-specification", "", "Capacity reservation specification (JSON)")

	cmd.Flags().StringVar(&clientToken, "client-token", "", "Client token")

	cmd.Flags().StringVar(&cpuOptions, "cpu-options", "", "Cpu options (key=value,key2=value2)")

	cmd.Flags().StringVar(&creditSpecification, "credit-specification", "", "Credit specification (key=value,key2=value2)")

	cmd.Flags().BoolVar(&disableApiStop, "disable-api-stop", false, "Disable api stop")

	cmd.Flags().BoolVar(&disableApiTermination, "disable-api-termination", false, "Disable api termination")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().BoolVar(&ebsOptimized, "ebs-optimized", false, "Ebs optimized")

	cmd.Flags().StringArrayVar(&elasticGpuSpecification, "elastic-gpu-specification", nil, "Elastic gpu specification (key=value,key2=value2, repeatable)")

	cmd.Flags().StringArrayVar(&elasticInferenceAccelerators, "elastic-inference-accelerators", nil, "Elastic inference accelerators (key=value,key2=value2, repeatable)")

	cmd.Flags().BoolVar(&enablePrimaryIpv6, "enable-primary-ipv-6", false, "Enable primary ipv 6")

	cmd.Flags().StringVar(&enclaveOptions, "enclave-options", "", "Enclave options (key=value,key2=value2)")

	cmd.Flags().StringVar(&hibernationOptions, "hibernation-options", "", "Hibernation options (key=value,key2=value2)")

	cmd.Flags().StringVar(&iamInstanceProfile, "iam-instance-profile", "", "Iam instance profile (key=value,key2=value2)")

	cmd.Flags().StringVar(&imageId, "image-id", "", "Image id")

	cmd.Flags().StringVar(&instanceInitiatedShutdownBehavior, "instance-initiated-shutdown-behavior", "", "Instance initiated shutdown behavior")

	cmd.Flags().StringVar(&instanceMarketOptions, "instance-market-options", "", "Instance market options (JSON)")

	cmd.Flags().StringVar(&instanceType, "instance-type", "", "Instance type")

	cmd.Flags().Int32Var(&ipv6AddressCount, "ipv-6-address-count", 0, "Ipv 6 address count")

	cmd.Flags().StringArrayVar(&ipv6Addresses, "ipv-6-addresses", nil, "Ipv 6 addresses (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&kernelId, "kernel-id", "", "Kernel id")

	cmd.Flags().StringVar(&keyName, "key-name", "", "Key name")

	cmd.Flags().StringVar(&launchTemplate, "launch-template", "", "Launch template (key=value,key2=value2)")

	cmd.Flags().StringArrayVar(&licenseSpecifications, "license-specifications", nil, "License specifications (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&maintenanceOptions, "maintenance-options", "", "Maintenance options (key=value,key2=value2)")

	cmd.Flags().StringVar(&metadataOptions, "metadata-options", "", "Metadata options (key=value,key2=value2)")

	cmd.Flags().StringVar(&monitoring, "monitoring", "", "Monitoring (key=value,key2=value2)")

	cmd.Flags().StringVar(&networkInterfaces, "network-interfaces", "", "Network interfaces (JSON)")

	cmd.Flags().StringVar(&networkPerformanceOptions, "network-performance-options", "", "Network performance options (key=value,key2=value2)")

	cmd.Flags().StringVar(&operator, "operator", "", "Operator (key=value,key2=value2)")

	cmd.Flags().StringVar(&placement, "placement", "", "Placement (key=value,key2=value2)")

	cmd.Flags().StringVar(&privateDnsNameOptions, "private-dns-name-options", "", "Private dns name options (key=value,key2=value2)")

	cmd.Flags().StringVar(&privateIpAddress, "private-ip-address", "", "Private ip address")

	cmd.Flags().StringVar(&ramdiskId, "ramdisk-id", "", "Ramdisk id")

	cmd.Flags().StringVar(&secondaryInterfaces, "secondary-interfaces", "", "Secondary interfaces (JSON)")

	cmd.Flags().StringArrayVar(&securityGroupIds, "security-group-ids", nil, "Security group ids")

	cmd.Flags().StringArrayVar(&securityGroups, "security-groups", nil, "Security groups")

	cmd.Flags().StringVar(&subnetId, "subnet-id", "", "Subnet id")

	cmd.Flags().StringVar(&tagSpecifications, "tag-specifications", "", "Tag specifications (JSON)")

	cmd.Flags().StringVar(&userData, "user-data", "", "User data")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2StartInstancesCmd() *cobra.Command {
	var instanceIds []string
	var additionalInfo string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "start-instances",
		Short: "StartInstances",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.StartInstancesInput{}

			if len(instanceIds) > 0 {
				input.InstanceIds = instanceIds
			}

			if additionalInfo != "" {
				input.AdditionalInfo = aws.String(additionalInfo)
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			out, err := client.StartInstances(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("start-instances failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&instanceIds, "instance-ids", nil, "Instance ids")

	cmd.Flags().StringVar(&additionalInfo, "additional-info", "", "Additional info")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2StopInstancesCmd() *cobra.Command {
	var instanceIds []string
	var dryRun bool
	var force bool
	var hibernate bool
	var skipOsShutdown bool

	cmd := &cobra.Command{
		Use:   "stop-instances",
		Short: "StopInstances",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.StopInstancesInput{}

			if len(instanceIds) > 0 {
				input.InstanceIds = instanceIds
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if force {
				input.Force = aws.Bool(force)
			}

			if hibernate {
				input.Hibernate = aws.Bool(hibernate)
			}

			if skipOsShutdown {
				input.SkipOsShutdown = aws.Bool(skipOsShutdown)
			}

			out, err := client.StopInstances(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("stop-instances failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&instanceIds, "instance-ids", nil, "Instance ids")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().BoolVar(&force, "force", false, "Force")

	cmd.Flags().BoolVar(&hibernate, "hibernate", false, "Hibernate")

	cmd.Flags().BoolVar(&skipOsShutdown, "skip-os-shutdown", false, "Skip os shutdown")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEC2TerminateInstancesCmd() *cobra.Command {
	var instanceIds []string
	var dryRun bool
	var force bool
	var skipOsShutdown bool

	cmd := &cobra.Command{
		Use:   "terminate-instances",
		Short: "TerminateInstances",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ec2.NewFromConfig(cfg, func(o *ec2.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ec2.TerminateInstancesInput{}

			if len(instanceIds) > 0 {
				input.InstanceIds = instanceIds
			}

			if dryRun {
				input.DryRun = aws.Bool(dryRun)
			}

			if force {
				input.Force = aws.Bool(force)
			}

			if skipOsShutdown {
				input.SkipOsShutdown = aws.Bool(skipOsShutdown)
			}

			out, err := client.TerminateInstances(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("terminate-instances failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&instanceIds, "instance-ids", nil, "Instance ids")

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Dry run")

	cmd.Flags().BoolVar(&force, "force", false, "Force")

	cmd.Flags().BoolVar(&skipOsShutdown, "skip-os-shutdown", false, "Skip os shutdown")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
