// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newDynamoDBCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "dynamodb",
		Short: "DynamoDB commands",
	}

	cmd.AddCommand(
		newDynamoDBBatchGetItemCmd(),
		newDynamoDBBatchWriteItemCmd(),
		newDynamoDBCreateTableCmd(),
		newDynamoDBDeleteItemCmd(),
		newDynamoDBDeleteTableCmd(),
		newDynamoDBDescribeContinuousBackupsCmd(),
		newDynamoDBDescribeTableCmd(),
		newDynamoDBDescribeTimeToLiveCmd(),
		newDynamoDBGetItemCmd(),
		newDynamoDBListTablesCmd(),
		newDynamoDBListTagsOfResourceCmd(),
		newDynamoDBPutItemCmd(),
		newDynamoDBQueryCmd(),
		newDynamoDBScanCmd(),
		newDynamoDBTagResourceCmd(),
		newDynamoDBTransactGetItemsCmd(),
		newDynamoDBTransactWriteItemsCmd(),
		newDynamoDBUntagResourceCmd(),
		newDynamoDBUpdateItemCmd(),
		newDynamoDBUpdateTableCmd(),
		newDynamoDBUpdateTimeToLiveCmd(),
	)

	return cmd
}

func newDynamoDBBatchGetItemCmd() *cobra.Command {
	var requestItems string
	var returnConsumedCapacity string

	cmd := &cobra.Command{
		Use:   "batch-get-item",
		Short: "BatchGetItem",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.BatchGetItemInput{}

			if requestItems != "" {
				if err := json.Unmarshal([]byte(requestItems), &input.RequestItems); err != nil {
					return fmt.Errorf("batch-get-item: parse --request-items: %w", err)
				}
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			out, err := client.BatchGetItem(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("batch-get-item failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&requestItems, "request-items", "", "Request items (JSON)")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBBatchWriteItemCmd() *cobra.Command {
	var requestItems string
	var returnConsumedCapacity string
	var returnItemCollectionMetrics string

	cmd := &cobra.Command{
		Use:   "batch-write-item",
		Short: "BatchWriteItem",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.BatchWriteItemInput{}

			if requestItems != "" {
				if err := json.Unmarshal([]byte(requestItems), &input.RequestItems); err != nil {
					return fmt.Errorf("batch-write-item: parse --request-items: %w", err)
				}
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			if returnItemCollectionMetrics != "" {
				input.ReturnItemCollectionMetrics = types.ReturnItemCollectionMetrics(returnItemCollectionMetrics)
			}

			out, err := client.BatchWriteItem(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("batch-write-item failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&requestItems, "request-items", "", "Request items (JSON)")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().StringVar(&returnItemCollectionMetrics, "return-item-collection-metrics", "", "Return item collection metrics")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBCreateTableCmd() *cobra.Command {
	var tableName string
	var attributeDefinitions []string
	var billingMode string
	var deletionProtectionEnabled bool
	var globalSecondaryIndexes string
	var globalTableSettingsReplicationMode string
	var globalTableSourceArn string
	var keySchema []string
	var localSecondaryIndexes string
	var onDemandThroughput string
	var provisionedThroughput string
	var resourcePolicy string
	var sSESpecification string
	var streamSpecification string
	var tableClass string
	var tags []string
	var warmThroughput string

	cmd := &cobra.Command{
		Use:   "create-table",
		Short: "CreateTable",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.CreateTableInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			for _, raw := range attributeDefinitions {
				var val types.AttributeDefinition
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-table: parse --attribute-definitions: %w", err)
				}
				input.AttributeDefinitions = append(input.AttributeDefinitions, val)
			}

			if billingMode != "" {
				input.BillingMode = types.BillingMode(billingMode)
			}

			if deletionProtectionEnabled {
				input.DeletionProtectionEnabled = aws.Bool(deletionProtectionEnabled)
			}

			if globalSecondaryIndexes != "" {
				if err := json.Unmarshal([]byte(globalSecondaryIndexes), &input.GlobalSecondaryIndexes); err != nil {
					return fmt.Errorf("create-table: parse --global-secondary-indexes: %w", err)
				}
			}

			if globalTableSettingsReplicationMode != "" {
				input.GlobalTableSettingsReplicationMode = types.GlobalTableSettingsReplicationMode(globalTableSettingsReplicationMode)
			}

			if globalTableSourceArn != "" {
				input.GlobalTableSourceArn = aws.String(globalTableSourceArn)
			}

			for _, raw := range keySchema {
				var val types.KeySchemaElement
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-table: parse --key-schema: %w", err)
				}
				input.KeySchema = append(input.KeySchema, val)
			}

			if localSecondaryIndexes != "" {
				if err := json.Unmarshal([]byte(localSecondaryIndexes), &input.LocalSecondaryIndexes); err != nil {
					return fmt.Errorf("create-table: parse --local-secondary-indexes: %w", err)
				}
			}

			if onDemandThroughput != "" {
				var val types.OnDemandThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), onDemandThroughput); err != nil {
					return fmt.Errorf("create-table: parse --on-demand-throughput: %w", err)
				}
				input.OnDemandThroughput = &val
			}

			if provisionedThroughput != "" {
				var val types.ProvisionedThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), provisionedThroughput); err != nil {
					return fmt.Errorf("create-table: parse --provisioned-throughput: %w", err)
				}
				input.ProvisionedThroughput = &val
			}

			if resourcePolicy != "" {
				input.ResourcePolicy = aws.String(resourcePolicy)
			}

			if sSESpecification != "" {
				var val types.SSESpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), sSESpecification); err != nil {
					return fmt.Errorf("create-table: parse --sse-specification: %w", err)
				}
				input.SSESpecification = &val
			}

			if streamSpecification != "" {
				var val types.StreamSpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), streamSpecification); err != nil {
					return fmt.Errorf("create-table: parse --stream-specification: %w", err)
				}
				input.StreamSpecification = &val
			}

			if tableClass != "" {
				input.TableClass = types.TableClass(tableClass)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-table: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			if warmThroughput != "" {
				var val types.WarmThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), warmThroughput); err != nil {
					return fmt.Errorf("create-table: parse --warm-throughput: %w", err)
				}
				input.WarmThroughput = &val
			}

			out, err := client.CreateTable(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-table failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringArrayVar(&attributeDefinitions, "attribute-definitions", nil, "Attribute definitions (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&billingMode, "billing-mode", "", "Billing mode")

	cmd.Flags().BoolVar(&deletionProtectionEnabled, "deletion-protection-enabled", false, "Deletion protection enabled")

	cmd.Flags().StringVar(&globalSecondaryIndexes, "global-secondary-indexes", "", "Global secondary indexes (JSON)")

	cmd.Flags().StringVar(&globalTableSettingsReplicationMode, "global-table-settings-replication-mode", "", "Global table settings replication mode")

	cmd.Flags().StringVar(&globalTableSourceArn, "global-table-source-arn", "", "Global table source arn")

	cmd.Flags().StringArrayVar(&keySchema, "key-schema", nil, "Key schema (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&localSecondaryIndexes, "local-secondary-indexes", "", "Local secondary indexes (JSON)")

	cmd.Flags().StringVar(&onDemandThroughput, "on-demand-throughput", "", "On demand throughput (key=value,key2=value2)")

	cmd.Flags().StringVar(&provisionedThroughput, "provisioned-throughput", "", "Provisioned throughput (key=value,key2=value2)")

	cmd.Flags().StringVar(&resourcePolicy, "resource-policy", "", "Resource policy")

	cmd.Flags().StringVar(&sSESpecification, "sse-specification", "", "Sse specification (key=value,key2=value2)")

	cmd.Flags().StringVar(&streamSpecification, "stream-specification", "", "Stream specification (key=value,key2=value2)")

	cmd.Flags().StringVar(&tableClass, "table-class", "", "Table class")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&warmThroughput, "warm-throughput", "", "Warm throughput (key=value,key2=value2)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBDeleteItemCmd() *cobra.Command {
	var key string
	var tableName string
	var conditionExpression string
	var conditionalOperator string
	var expected string
	var expressionAttributeNames string
	var expressionAttributeValues string
	var returnConsumedCapacity string
	var returnItemCollectionMetrics string
	var returnValues string
	var returnValuesOnConditionCheckFailure string

	cmd := &cobra.Command{
		Use:   "delete-item",
		Short: "DeleteItem",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.DeleteItemInput{}

			if key != "" {
				decoded, err := decodeDynamoDBJSON(key)
				if err != nil {
					return fmt.Errorf("delete-item: parse --key: %w", err)
				}
				input.Key = decoded
			}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			if conditionExpression != "" {
				input.ConditionExpression = aws.String(conditionExpression)
			}

			if conditionalOperator != "" {
				input.ConditionalOperator = types.ConditionalOperator(conditionalOperator)
			}

			if expected != "" {
				if err := json.Unmarshal([]byte(expected), &input.Expected); err != nil {
					return fmt.Errorf("delete-item: parse --expected: %w", err)
				}
			}

			if expressionAttributeNames != "" {
				if err := json.Unmarshal([]byte(expressionAttributeNames), &input.ExpressionAttributeNames); err != nil {
					return fmt.Errorf("delete-item: parse --expression-attribute-names: %w", err)
				}
			}

			if expressionAttributeValues != "" {
				decoded, err := decodeDynamoDBJSON(expressionAttributeValues)
				if err != nil {
					return fmt.Errorf("delete-item: parse --expression-attribute-values: %w", err)
				}
				input.ExpressionAttributeValues = decoded
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			if returnItemCollectionMetrics != "" {
				input.ReturnItemCollectionMetrics = types.ReturnItemCollectionMetrics(returnItemCollectionMetrics)
			}

			if returnValues != "" {
				input.ReturnValues = types.ReturnValue(returnValues)
			}

			if returnValuesOnConditionCheckFailure != "" {
				input.ReturnValuesOnConditionCheckFailure = types.ReturnValuesOnConditionCheckFailure(returnValuesOnConditionCheckFailure)
			}

			out, err := client.DeleteItem(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-item failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&key, "key", "", "Key (JSON)")

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringVar(&conditionExpression, "condition-expression", "", "Condition expression")

	cmd.Flags().StringVar(&conditionalOperator, "conditional-operator", "", "Conditional operator")

	cmd.Flags().StringVar(&expected, "expected", "", "Expected (JSON)")

	cmd.Flags().StringVar(&expressionAttributeNames, "expression-attribute-names", "", "Expression attribute names (JSON)")

	cmd.Flags().StringVar(&expressionAttributeValues, "expression-attribute-values", "", "Expression attribute values (JSON)")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().StringVar(&returnItemCollectionMetrics, "return-item-collection-metrics", "", "Return item collection metrics")

	cmd.Flags().StringVar(&returnValues, "return-values", "", "Return values")

	cmd.Flags().StringVar(&returnValuesOnConditionCheckFailure, "return-values-on-condition-check-failure", "", "Return values on condition check failure")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBDeleteTableCmd() *cobra.Command {
	var tableName string

	cmd := &cobra.Command{
		Use:   "delete-table",
		Short: "DeleteTable",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.DeleteTableInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			out, err := client.DeleteTable(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-table failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBDescribeContinuousBackupsCmd() *cobra.Command {
	var tableName string

	cmd := &cobra.Command{
		Use:   "describe-continuous-backups",
		Short: "DescribeContinuousBackups",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.DescribeContinuousBackupsInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			out, err := client.DescribeContinuousBackups(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-continuous-backups failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBDescribeTableCmd() *cobra.Command {
	var tableName string

	cmd := &cobra.Command{
		Use:   "describe-table",
		Short: "DescribeTable",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.DescribeTableInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			out, err := client.DescribeTable(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-table failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBDescribeTimeToLiveCmd() *cobra.Command {
	var tableName string

	cmd := &cobra.Command{
		Use:   "describe-time-to-live",
		Short: "DescribeTimeToLive",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.DescribeTimeToLiveInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			out, err := client.DescribeTimeToLive(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-time-to-live failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBGetItemCmd() *cobra.Command {
	var key string
	var tableName string
	var attributesToGet []string
	var consistentRead bool
	var expressionAttributeNames string
	var projectionExpression string
	var returnConsumedCapacity string

	cmd := &cobra.Command{
		Use:   "get-item",
		Short: "GetItem",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.GetItemInput{}

			if key != "" {
				decoded, err := decodeDynamoDBJSON(key)
				if err != nil {
					return fmt.Errorf("get-item: parse --key: %w", err)
				}
				input.Key = decoded
			}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			if len(attributesToGet) > 0 {
				input.AttributesToGet = attributesToGet
			}

			if consistentRead {
				input.ConsistentRead = aws.Bool(consistentRead)
			}

			if expressionAttributeNames != "" {
				if err := json.Unmarshal([]byte(expressionAttributeNames), &input.ExpressionAttributeNames); err != nil {
					return fmt.Errorf("get-item: parse --expression-attribute-names: %w", err)
				}
			}

			if projectionExpression != "" {
				input.ProjectionExpression = aws.String(projectionExpression)
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			out, err := client.GetItem(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-item failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&key, "key", "", "Key (JSON)")

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringArrayVar(&attributesToGet, "attributes-to-get", nil, "Attributes to get")

	cmd.Flags().BoolVar(&consistentRead, "consistent-read", false, "Consistent read")

	cmd.Flags().StringVar(&expressionAttributeNames, "expression-attribute-names", "", "Expression attribute names (JSON)")

	cmd.Flags().StringVar(&projectionExpression, "projection-expression", "", "Projection expression")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBListTablesCmd() *cobra.Command {
	var exclusiveStartTableName string
	var limit int32

	cmd := &cobra.Command{
		Use:   "list-tables",
		Short: "ListTables",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.ListTablesInput{}

			if exclusiveStartTableName != "" {
				input.ExclusiveStartTableName = aws.String(exclusiveStartTableName)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			out, err := client.ListTables(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-tables failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&exclusiveStartTableName, "exclusive-start-table-name", "", "Exclusive start table name")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBListTagsOfResourceCmd() *cobra.Command {
	var resourceArn string
	var nextToken string

	cmd := &cobra.Command{
		Use:   "list-tags-of-resource",
		Short: "ListTagsOfResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.ListTagsOfResourceInput{}

			if resourceArn != "" {
				input.ResourceArn = aws.String(resourceArn)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.ListTagsOfResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-tags-of-resource failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceArn, "resource-arn", "", "Resource arn")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBPutItemCmd() *cobra.Command {
	var item string
	var tableName string
	var conditionExpression string
	var conditionalOperator string
	var expected string
	var expressionAttributeNames string
	var expressionAttributeValues string
	var returnConsumedCapacity string
	var returnItemCollectionMetrics string
	var returnValues string
	var returnValuesOnConditionCheckFailure string

	cmd := &cobra.Command{
		Use:   "put-item",
		Short: "PutItem",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.PutItemInput{}

			if item != "" {
				decoded, err := decodeDynamoDBJSON(item)
				if err != nil {
					return fmt.Errorf("put-item: parse --item: %w", err)
				}
				input.Item = decoded
			}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			if conditionExpression != "" {
				input.ConditionExpression = aws.String(conditionExpression)
			}

			if conditionalOperator != "" {
				input.ConditionalOperator = types.ConditionalOperator(conditionalOperator)
			}

			if expected != "" {
				if err := json.Unmarshal([]byte(expected), &input.Expected); err != nil {
					return fmt.Errorf("put-item: parse --expected: %w", err)
				}
			}

			if expressionAttributeNames != "" {
				if err := json.Unmarshal([]byte(expressionAttributeNames), &input.ExpressionAttributeNames); err != nil {
					return fmt.Errorf("put-item: parse --expression-attribute-names: %w", err)
				}
			}

			if expressionAttributeValues != "" {
				decoded, err := decodeDynamoDBJSON(expressionAttributeValues)
				if err != nil {
					return fmt.Errorf("put-item: parse --expression-attribute-values: %w", err)
				}
				input.ExpressionAttributeValues = decoded
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			if returnItemCollectionMetrics != "" {
				input.ReturnItemCollectionMetrics = types.ReturnItemCollectionMetrics(returnItemCollectionMetrics)
			}

			if returnValues != "" {
				input.ReturnValues = types.ReturnValue(returnValues)
			}

			if returnValuesOnConditionCheckFailure != "" {
				input.ReturnValuesOnConditionCheckFailure = types.ReturnValuesOnConditionCheckFailure(returnValuesOnConditionCheckFailure)
			}

			out, err := client.PutItem(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-item failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&item, "item", "", "Item (JSON)")

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringVar(&conditionExpression, "condition-expression", "", "Condition expression")

	cmd.Flags().StringVar(&conditionalOperator, "conditional-operator", "", "Conditional operator")

	cmd.Flags().StringVar(&expected, "expected", "", "Expected (JSON)")

	cmd.Flags().StringVar(&expressionAttributeNames, "expression-attribute-names", "", "Expression attribute names (JSON)")

	cmd.Flags().StringVar(&expressionAttributeValues, "expression-attribute-values", "", "Expression attribute values (JSON)")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().StringVar(&returnItemCollectionMetrics, "return-item-collection-metrics", "", "Return item collection metrics")

	cmd.Flags().StringVar(&returnValues, "return-values", "", "Return values")

	cmd.Flags().StringVar(&returnValuesOnConditionCheckFailure, "return-values-on-condition-check-failure", "", "Return values on condition check failure")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBQueryCmd() *cobra.Command {
	var tableName string
	var attributesToGet []string
	var conditionalOperator string
	var consistentRead bool
	var exclusiveStartKey string
	var expressionAttributeNames string
	var expressionAttributeValues string
	var filterExpression string
	var indexName string
	var keyConditionExpression string
	var keyConditions string
	var limit int32
	var projectionExpression string
	var queryFilter string
	var returnConsumedCapacity string
	var scanIndexForward bool
	var selectValue string

	cmd := &cobra.Command{
		Use:   "query",
		Short: "Query",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.QueryInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			if len(attributesToGet) > 0 {
				input.AttributesToGet = attributesToGet
			}

			if conditionalOperator != "" {
				input.ConditionalOperator = types.ConditionalOperator(conditionalOperator)
			}

			if consistentRead {
				input.ConsistentRead = aws.Bool(consistentRead)
			}

			if exclusiveStartKey != "" {
				decoded, err := decodeDynamoDBJSON(exclusiveStartKey)
				if err != nil {
					return fmt.Errorf("query: parse --exclusive-start-key: %w", err)
				}
				input.ExclusiveStartKey = decoded
			}

			if expressionAttributeNames != "" {
				if err := json.Unmarshal([]byte(expressionAttributeNames), &input.ExpressionAttributeNames); err != nil {
					return fmt.Errorf("query: parse --expression-attribute-names: %w", err)
				}
			}

			if expressionAttributeValues != "" {
				decoded, err := decodeDynamoDBJSON(expressionAttributeValues)
				if err != nil {
					return fmt.Errorf("query: parse --expression-attribute-values: %w", err)
				}
				input.ExpressionAttributeValues = decoded
			}

			if filterExpression != "" {
				input.FilterExpression = aws.String(filterExpression)
			}

			if indexName != "" {
				input.IndexName = aws.String(indexName)
			}

			if keyConditionExpression != "" {
				input.KeyConditionExpression = aws.String(keyConditionExpression)
			}

			if keyConditions != "" {
				if err := json.Unmarshal([]byte(keyConditions), &input.KeyConditions); err != nil {
					return fmt.Errorf("query: parse --key-conditions: %w", err)
				}
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			if projectionExpression != "" {
				input.ProjectionExpression = aws.String(projectionExpression)
			}

			if queryFilter != "" {
				if err := json.Unmarshal([]byte(queryFilter), &input.QueryFilter); err != nil {
					return fmt.Errorf("query: parse --query-filter: %w", err)
				}
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			if scanIndexForward {
				input.ScanIndexForward = aws.Bool(scanIndexForward)
			}

			if selectValue != "" {
				input.Select = types.Select(selectValue)
			}

			out, err := client.Query(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("query failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringArrayVar(&attributesToGet, "attributes-to-get", nil, "Attributes to get")

	cmd.Flags().StringVar(&conditionalOperator, "conditional-operator", "", "Conditional operator")

	cmd.Flags().BoolVar(&consistentRead, "consistent-read", false, "Consistent read")

	cmd.Flags().StringVar(&exclusiveStartKey, "exclusive-start-key", "", "Exclusive start key (JSON)")

	cmd.Flags().StringVar(&expressionAttributeNames, "expression-attribute-names", "", "Expression attribute names (JSON)")

	cmd.Flags().StringVar(&expressionAttributeValues, "expression-attribute-values", "", "Expression attribute values (JSON)")

	cmd.Flags().StringVar(&filterExpression, "filter-expression", "", "Filter expression")

	cmd.Flags().StringVar(&indexName, "index-name", "", "Index name")

	cmd.Flags().StringVar(&keyConditionExpression, "key-condition-expression", "", "Key condition expression")

	cmd.Flags().StringVar(&keyConditions, "key-conditions", "", "Key conditions (JSON)")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().StringVar(&projectionExpression, "projection-expression", "", "Projection expression")

	cmd.Flags().StringVar(&queryFilter, "query-filter", "", "Query filter (JSON)")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().BoolVar(&scanIndexForward, "scan-index-forward", false, "Scan index forward")

	cmd.Flags().StringVar(&selectValue, "select", "", "Select")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBScanCmd() *cobra.Command {
	var tableName string
	var attributesToGet []string
	var conditionalOperator string
	var consistentRead bool
	var exclusiveStartKey string
	var expressionAttributeNames string
	var expressionAttributeValues string
	var filterExpression string
	var indexName string
	var limit int32
	var projectionExpression string
	var returnConsumedCapacity string
	var scanFilter string
	var segment int32
	var selectValue string
	var totalSegments int32

	cmd := &cobra.Command{
		Use:   "scan",
		Short: "Scan",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.ScanInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			if len(attributesToGet) > 0 {
				input.AttributesToGet = attributesToGet
			}

			if conditionalOperator != "" {
				input.ConditionalOperator = types.ConditionalOperator(conditionalOperator)
			}

			if consistentRead {
				input.ConsistentRead = aws.Bool(consistentRead)
			}

			if exclusiveStartKey != "" {
				decoded, err := decodeDynamoDBJSON(exclusiveStartKey)
				if err != nil {
					return fmt.Errorf("scan: parse --exclusive-start-key: %w", err)
				}
				input.ExclusiveStartKey = decoded
			}

			if expressionAttributeNames != "" {
				if err := json.Unmarshal([]byte(expressionAttributeNames), &input.ExpressionAttributeNames); err != nil {
					return fmt.Errorf("scan: parse --expression-attribute-names: %w", err)
				}
			}

			if expressionAttributeValues != "" {
				decoded, err := decodeDynamoDBJSON(expressionAttributeValues)
				if err != nil {
					return fmt.Errorf("scan: parse --expression-attribute-values: %w", err)
				}
				input.ExpressionAttributeValues = decoded
			}

			if filterExpression != "" {
				input.FilterExpression = aws.String(filterExpression)
			}

			if indexName != "" {
				input.IndexName = aws.String(indexName)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			if projectionExpression != "" {
				input.ProjectionExpression = aws.String(projectionExpression)
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			if scanFilter != "" {
				if err := json.Unmarshal([]byte(scanFilter), &input.ScanFilter); err != nil {
					return fmt.Errorf("scan: parse --scan-filter: %w", err)
				}
			}

			if segment != 0 {
				input.Segment = aws.Int32(segment)
			}

			if selectValue != "" {
				input.Select = types.Select(selectValue)
			}

			if totalSegments != 0 {
				input.TotalSegments = aws.Int32(totalSegments)
			}

			out, err := client.Scan(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("scan failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringArrayVar(&attributesToGet, "attributes-to-get", nil, "Attributes to get")

	cmd.Flags().StringVar(&conditionalOperator, "conditional-operator", "", "Conditional operator")

	cmd.Flags().BoolVar(&consistentRead, "consistent-read", false, "Consistent read")

	cmd.Flags().StringVar(&exclusiveStartKey, "exclusive-start-key", "", "Exclusive start key (JSON)")

	cmd.Flags().StringVar(&expressionAttributeNames, "expression-attribute-names", "", "Expression attribute names (JSON)")

	cmd.Flags().StringVar(&expressionAttributeValues, "expression-attribute-values", "", "Expression attribute values (JSON)")

	cmd.Flags().StringVar(&filterExpression, "filter-expression", "", "Filter expression")

	cmd.Flags().StringVar(&indexName, "index-name", "", "Index name")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().StringVar(&projectionExpression, "projection-expression", "", "Projection expression")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().StringVar(&scanFilter, "scan-filter", "", "Scan filter (JSON)")

	cmd.Flags().Int32Var(&segment, "segment", 0, "Segment")

	cmd.Flags().StringVar(&selectValue, "select", "", "Select")

	cmd.Flags().Int32Var(&totalSegments, "total-segments", 0, "Total segments")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBTagResourceCmd() *cobra.Command {
	var resourceArn string
	var tags []string

	cmd := &cobra.Command{
		Use:   "tag-resource",
		Short: "TagResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.TagResourceInput{}

			if resourceArn != "" {
				input.ResourceArn = aws.String(resourceArn)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("tag-resource: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			_, err = client.TagResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("tag-resource failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceArn, "resource-arn", "", "Resource arn")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBTransactGetItemsCmd() *cobra.Command {
	var transactItems string
	var returnConsumedCapacity string

	cmd := &cobra.Command{
		Use:   "transact-get-items",
		Short: "TransactGetItems",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.TransactGetItemsInput{}

			if transactItems != "" {
				if err := json.Unmarshal([]byte(transactItems), &input.TransactItems); err != nil {
					return fmt.Errorf("transact-get-items: parse --transact-items: %w", err)
				}
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			out, err := client.TransactGetItems(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("transact-get-items failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&transactItems, "transact-items", "", "Transact items (JSON)")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBTransactWriteItemsCmd() *cobra.Command {
	var transactItems string
	var clientRequestToken string
	var returnConsumedCapacity string
	var returnItemCollectionMetrics string

	cmd := &cobra.Command{
		Use:   "transact-write-items",
		Short: "TransactWriteItems",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.TransactWriteItemsInput{}

			if transactItems != "" {
				if err := json.Unmarshal([]byte(transactItems), &input.TransactItems); err != nil {
					return fmt.Errorf("transact-write-items: parse --transact-items: %w", err)
				}
			}

			if clientRequestToken != "" {
				input.ClientRequestToken = aws.String(clientRequestToken)
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			if returnItemCollectionMetrics != "" {
				input.ReturnItemCollectionMetrics = types.ReturnItemCollectionMetrics(returnItemCollectionMetrics)
			}

			out, err := client.TransactWriteItems(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("transact-write-items failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&transactItems, "transact-items", "", "Transact items (JSON)")

	cmd.Flags().StringVar(&clientRequestToken, "client-request-token", "", "Client request token")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().StringVar(&returnItemCollectionMetrics, "return-item-collection-metrics", "", "Return item collection metrics")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBUntagResourceCmd() *cobra.Command {
	var resourceArn string
	var tagKeys []string

	cmd := &cobra.Command{
		Use:   "untag-resource",
		Short: "UntagResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.UntagResourceInput{}

			if resourceArn != "" {
				input.ResourceArn = aws.String(resourceArn)
			}

			if len(tagKeys) > 0 {
				input.TagKeys = tagKeys
			}

			_, err = client.UntagResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("untag-resource failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceArn, "resource-arn", "", "Resource arn")

	cmd.Flags().StringArrayVar(&tagKeys, "tag-keys", nil, "Tag keys")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBUpdateItemCmd() *cobra.Command {
	var key string
	var tableName string
	var attributeUpdates string
	var conditionExpression string
	var conditionalOperator string
	var expected string
	var expressionAttributeNames string
	var expressionAttributeValues string
	var returnConsumedCapacity string
	var returnItemCollectionMetrics string
	var returnValues string
	var returnValuesOnConditionCheckFailure string
	var updateExpression string

	cmd := &cobra.Command{
		Use:   "update-item",
		Short: "UpdateItem",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.UpdateItemInput{}

			if key != "" {
				decoded, err := decodeDynamoDBJSON(key)
				if err != nil {
					return fmt.Errorf("update-item: parse --key: %w", err)
				}
				input.Key = decoded
			}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			if attributeUpdates != "" {
				if err := json.Unmarshal([]byte(attributeUpdates), &input.AttributeUpdates); err != nil {
					return fmt.Errorf("update-item: parse --attribute-updates: %w", err)
				}
			}

			if conditionExpression != "" {
				input.ConditionExpression = aws.String(conditionExpression)
			}

			if conditionalOperator != "" {
				input.ConditionalOperator = types.ConditionalOperator(conditionalOperator)
			}

			if expected != "" {
				if err := json.Unmarshal([]byte(expected), &input.Expected); err != nil {
					return fmt.Errorf("update-item: parse --expected: %w", err)
				}
			}

			if expressionAttributeNames != "" {
				if err := json.Unmarshal([]byte(expressionAttributeNames), &input.ExpressionAttributeNames); err != nil {
					return fmt.Errorf("update-item: parse --expression-attribute-names: %w", err)
				}
			}

			if expressionAttributeValues != "" {
				decoded, err := decodeDynamoDBJSON(expressionAttributeValues)
				if err != nil {
					return fmt.Errorf("update-item: parse --expression-attribute-values: %w", err)
				}
				input.ExpressionAttributeValues = decoded
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			if returnItemCollectionMetrics != "" {
				input.ReturnItemCollectionMetrics = types.ReturnItemCollectionMetrics(returnItemCollectionMetrics)
			}

			if returnValues != "" {
				input.ReturnValues = types.ReturnValue(returnValues)
			}

			if returnValuesOnConditionCheckFailure != "" {
				input.ReturnValuesOnConditionCheckFailure = types.ReturnValuesOnConditionCheckFailure(returnValuesOnConditionCheckFailure)
			}

			if updateExpression != "" {
				input.UpdateExpression = aws.String(updateExpression)
			}

			out, err := client.UpdateItem(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-item failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&key, "key", "", "Key (JSON)")

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringVar(&attributeUpdates, "attribute-updates", "", "Attribute updates (JSON)")

	cmd.Flags().StringVar(&conditionExpression, "condition-expression", "", "Condition expression")

	cmd.Flags().StringVar(&conditionalOperator, "conditional-operator", "", "Conditional operator")

	cmd.Flags().StringVar(&expected, "expected", "", "Expected (JSON)")

	cmd.Flags().StringVar(&expressionAttributeNames, "expression-attribute-names", "", "Expression attribute names (JSON)")

	cmd.Flags().StringVar(&expressionAttributeValues, "expression-attribute-values", "", "Expression attribute values (JSON)")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().StringVar(&returnItemCollectionMetrics, "return-item-collection-metrics", "", "Return item collection metrics")

	cmd.Flags().StringVar(&returnValues, "return-values", "", "Return values")

	cmd.Flags().StringVar(&returnValuesOnConditionCheckFailure, "return-values-on-condition-check-failure", "", "Return values on condition check failure")

	cmd.Flags().StringVar(&updateExpression, "update-expression", "", "Update expression")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBUpdateTableCmd() *cobra.Command {
	var tableName string
	var attributeDefinitions []string
	var billingMode string
	var deletionProtectionEnabled bool
	var globalSecondaryIndexUpdates string
	var globalTableSettingsReplicationMode string
	var globalTableWitnessUpdates string
	var multiRegionConsistency string
	var onDemandThroughput string
	var provisionedThroughput string
	var replicaUpdates string
	var sSESpecification string
	var streamSpecification string
	var tableClass string
	var warmThroughput string

	cmd := &cobra.Command{
		Use:   "update-table",
		Short: "UpdateTable",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.UpdateTableInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			for _, raw := range attributeDefinitions {
				var val types.AttributeDefinition
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("update-table: parse --attribute-definitions: %w", err)
				}
				input.AttributeDefinitions = append(input.AttributeDefinitions, val)
			}

			if billingMode != "" {
				input.BillingMode = types.BillingMode(billingMode)
			}

			if deletionProtectionEnabled {
				input.DeletionProtectionEnabled = aws.Bool(deletionProtectionEnabled)
			}

			if globalSecondaryIndexUpdates != "" {
				if err := json.Unmarshal([]byte(globalSecondaryIndexUpdates), &input.GlobalSecondaryIndexUpdates); err != nil {
					return fmt.Errorf("update-table: parse --global-secondary-index-updates: %w", err)
				}
			}

			if globalTableSettingsReplicationMode != "" {
				input.GlobalTableSettingsReplicationMode = types.GlobalTableSettingsReplicationMode(globalTableSettingsReplicationMode)
			}

			if globalTableWitnessUpdates != "" {
				if err := json.Unmarshal([]byte(globalTableWitnessUpdates), &input.GlobalTableWitnessUpdates); err != nil {
					return fmt.Errorf("update-table: parse --global-table-witness-updates: %w", err)
				}
			}

			if multiRegionConsistency != "" {
				input.MultiRegionConsistency = types.MultiRegionConsistency(multiRegionConsistency)
			}

			if onDemandThroughput != "" {
				var val types.OnDemandThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), onDemandThroughput); err != nil {
					return fmt.Errorf("update-table: parse --on-demand-throughput: %w", err)
				}
				input.OnDemandThroughput = &val
			}

			if provisionedThroughput != "" {
				var val types.ProvisionedThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), provisionedThroughput); err != nil {
					return fmt.Errorf("update-table: parse --provisioned-throughput: %w", err)
				}
				input.ProvisionedThroughput = &val
			}

			if replicaUpdates != "" {
				if err := json.Unmarshal([]byte(replicaUpdates), &input.ReplicaUpdates); err != nil {
					return fmt.Errorf("update-table: parse --replica-updates: %w", err)
				}
			}

			if sSESpecification != "" {
				var val types.SSESpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), sSESpecification); err != nil {
					return fmt.Errorf("update-table: parse --sse-specification: %w", err)
				}
				input.SSESpecification = &val
			}

			if streamSpecification != "" {
				var val types.StreamSpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), streamSpecification); err != nil {
					return fmt.Errorf("update-table: parse --stream-specification: %w", err)
				}
				input.StreamSpecification = &val
			}

			if tableClass != "" {
				input.TableClass = types.TableClass(tableClass)
			}

			if warmThroughput != "" {
				var val types.WarmThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), warmThroughput); err != nil {
					return fmt.Errorf("update-table: parse --warm-throughput: %w", err)
				}
				input.WarmThroughput = &val
			}

			out, err := client.UpdateTable(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-table failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringArrayVar(&attributeDefinitions, "attribute-definitions", nil, "Attribute definitions (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&billingMode, "billing-mode", "", "Billing mode")

	cmd.Flags().BoolVar(&deletionProtectionEnabled, "deletion-protection-enabled", false, "Deletion protection enabled")

	cmd.Flags().StringVar(&globalSecondaryIndexUpdates, "global-secondary-index-updates", "", "Global secondary index updates (JSON)")

	cmd.Flags().StringVar(&globalTableSettingsReplicationMode, "global-table-settings-replication-mode", "", "Global table settings replication mode")

	cmd.Flags().StringVar(&globalTableWitnessUpdates, "global-table-witness-updates", "", "Global table witness updates (JSON)")

	cmd.Flags().StringVar(&multiRegionConsistency, "multi-region-consistency", "", "Multi region consistency")

	cmd.Flags().StringVar(&onDemandThroughput, "on-demand-throughput", "", "On demand throughput (key=value,key2=value2)")

	cmd.Flags().StringVar(&provisionedThroughput, "provisioned-throughput", "", "Provisioned throughput (key=value,key2=value2)")

	cmd.Flags().StringVar(&replicaUpdates, "replica-updates", "", "Replica updates (JSON)")

	cmd.Flags().StringVar(&sSESpecification, "sse-specification", "", "Sse specification (key=value,key2=value2)")

	cmd.Flags().StringVar(&streamSpecification, "stream-specification", "", "Stream specification (key=value,key2=value2)")

	cmd.Flags().StringVar(&tableClass, "table-class", "", "Table class")

	cmd.Flags().StringVar(&warmThroughput, "warm-throughput", "", "Warm throughput (key=value,key2=value2)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBUpdateTimeToLiveCmd() *cobra.Command {
	var tableName string
	var timeToLiveSpecification string

	cmd := &cobra.Command{
		Use:   "update-time-to-live",
		Short: "UpdateTimeToLive",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.UpdateTimeToLiveInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			if timeToLiveSpecification != "" {
				var val types.TimeToLiveSpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), timeToLiveSpecification); err != nil {
					return fmt.Errorf("update-time-to-live: parse --time-to-live-specification: %w", err)
				}
				input.TimeToLiveSpecification = &val
			}

			_, err = client.UpdateTimeToLive(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-time-to-live failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringVar(&timeToLiveSpecification, "time-to-live-specification", "", "Time to live specification (key=value,key2=value2)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
