// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/eventbridge"
	"github.com/aws/aws-sdk-go-v2/service/eventbridge/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newEventsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "events",
		Short: "Events commands",
	}

	cmd.AddCommand(
		newEventsCreateApiDestinationCmd(),
		newEventsCreateConnectionCmd(),
		newEventsCreateEventBusCmd(),
		newEventsDeleteApiDestinationCmd(),
		newEventsDeleteConnectionCmd(),
		newEventsDeleteEventBusCmd(),
		newEventsDeleteRuleCmd(),
		newEventsDescribeApiDestinationCmd(),
		newEventsDescribeConnectionCmd(),
		newEventsDescribeEventBusCmd(),
		newEventsDescribeRuleCmd(),
		newEventsListEventBusesCmd(),
		newEventsListRulesCmd(),
		newEventsListTagsForResourceCmd(),
		newEventsListTargetsByRuleCmd(),
		newEventsPutEventsCmd(),
		newEventsPutRuleCmd(),
		newEventsPutTargetsCmd(),
		newEventsRemoveTargetsCmd(),
		newEventsTagResourceCmd(),
		newEventsUntagResourceCmd(),
	)

	return cmd
}

func newEventsCreateApiDestinationCmd() *cobra.Command {
	var connectionArn string
	var httpMethod string
	var invocationEndpoint string
	var name string
	var description string
	var invocationRateLimitPerSecond int32

	cmd := &cobra.Command{
		Use:   "create-api-destination",
		Short: "CreateApiDestination",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.CreateApiDestinationInput{}

			if connectionArn != "" {
				input.ConnectionArn = aws.String(connectionArn)
			}

			if httpMethod != "" {
				input.HttpMethod = types.ApiDestinationHttpMethod(httpMethod)
			}

			if invocationEndpoint != "" {
				input.InvocationEndpoint = aws.String(invocationEndpoint)
			}

			if name != "" {
				input.Name = aws.String(name)
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			if invocationRateLimitPerSecond != 0 {
				input.InvocationRateLimitPerSecond = aws.Int32(invocationRateLimitPerSecond)
			}

			out, err := client.CreateApiDestination(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-api-destination failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&connectionArn, "connection-arn", "", "Connection arn")

	cmd.Flags().StringVar(&httpMethod, "http-method", "", "Http method")

	cmd.Flags().StringVar(&invocationEndpoint, "invocation-endpoint", "", "Invocation endpoint")

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().Int32Var(&invocationRateLimitPerSecond, "invocation-rate-limit-per-second", 0, "Invocation rate limit per second")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsCreateConnectionCmd() *cobra.Command {
	var authParameters string
	var authorizationType string
	var name string
	var description string
	var invocationConnectivityParameters string
	var kmsKeyIdentifier string

	cmd := &cobra.Command{
		Use:   "create-connection",
		Short: "CreateConnection",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.CreateConnectionInput{}

			if authParameters != "" {
				if err := json.Unmarshal([]byte(authParameters), &input.AuthParameters); err != nil {
					return fmt.Errorf("create-connection: parse --auth-parameters: %w", err)
				}
			}

			if authorizationType != "" {
				input.AuthorizationType = types.ConnectionAuthorizationType(authorizationType)
			}

			if name != "" {
				input.Name = aws.String(name)
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			if invocationConnectivityParameters != "" {
				if err := json.Unmarshal([]byte(invocationConnectivityParameters), &input.InvocationConnectivityParameters); err != nil {
					return fmt.Errorf("create-connection: parse --invocation-connectivity-parameters: %w", err)
				}
			}

			if kmsKeyIdentifier != "" {
				input.KmsKeyIdentifier = aws.String(kmsKeyIdentifier)
			}

			out, err := client.CreateConnection(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-connection failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&authParameters, "auth-parameters", "", "Auth parameters (JSON)")

	cmd.Flags().StringVar(&authorizationType, "authorization-type", "", "Authorization type")

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().StringVar(&invocationConnectivityParameters, "invocation-connectivity-parameters", "", "Invocation connectivity parameters (JSON)")

	cmd.Flags().StringVar(&kmsKeyIdentifier, "kms-key-identifier", "", "Kms key identifier")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsCreateEventBusCmd() *cobra.Command {
	var name string
	var deadLetterConfig string
	var description string
	var eventSourceName string
	var kmsKeyIdentifier string
	var logConfig string
	var tags []string

	cmd := &cobra.Command{
		Use:   "create-event-bus",
		Short: "CreateEventBus",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.CreateEventBusInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			if deadLetterConfig != "" {
				var val types.DeadLetterConfig
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), deadLetterConfig); err != nil {
					return fmt.Errorf("create-event-bus: parse --dead-letter-config: %w", err)
				}
				input.DeadLetterConfig = &val
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			if eventSourceName != "" {
				input.EventSourceName = aws.String(eventSourceName)
			}

			if kmsKeyIdentifier != "" {
				input.KmsKeyIdentifier = aws.String(kmsKeyIdentifier)
			}

			if logConfig != "" {
				var val types.LogConfig
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), logConfig); err != nil {
					return fmt.Errorf("create-event-bus: parse --log-config: %w", err)
				}
				input.LogConfig = &val
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-event-bus: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			out, err := client.CreateEventBus(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-event-bus failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().StringVar(&deadLetterConfig, "dead-letter-config", "", "Dead letter config (key=value,key2=value2)")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().StringVar(&eventSourceName, "event-source-name", "", "Event source name")

	cmd.Flags().StringVar(&kmsKeyIdentifier, "kms-key-identifier", "", "Kms key identifier")

	cmd.Flags().StringVar(&logConfig, "log-config", "", "Log config (key=value,key2=value2)")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsDeleteApiDestinationCmd() *cobra.Command {
	var name string

	cmd := &cobra.Command{
		Use:   "delete-api-destination",
		Short: "DeleteApiDestination",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.DeleteApiDestinationInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			_, err = client.DeleteApiDestination(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-api-destination failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsDeleteConnectionCmd() *cobra.Command {
	var name string

	cmd := &cobra.Command{
		Use:   "delete-connection",
		Short: "DeleteConnection",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.DeleteConnectionInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			out, err := client.DeleteConnection(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-connection failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsDeleteEventBusCmd() *cobra.Command {
	var name string

	cmd := &cobra.Command{
		Use:   "delete-event-bus",
		Short: "DeleteEventBus",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.DeleteEventBusInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			_, err = client.DeleteEventBus(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-event-bus failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsDeleteRuleCmd() *cobra.Command {
	var name string
	var eventBusName string
	var force bool

	cmd := &cobra.Command{
		Use:   "delete-rule",
		Short: "DeleteRule",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.DeleteRuleInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			if eventBusName != "" {
				input.EventBusName = aws.String(eventBusName)
			}

			if force {
				input.Force = force
			}

			_, err = client.DeleteRule(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-rule failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().StringVar(&eventBusName, "event-bus-name", "", "Event bus name")

	cmd.Flags().BoolVar(&force, "force", false, "Force")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsDescribeApiDestinationCmd() *cobra.Command {
	var name string

	cmd := &cobra.Command{
		Use:   "describe-api-destination",
		Short: "DescribeApiDestination",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.DescribeApiDestinationInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			out, err := client.DescribeApiDestination(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-api-destination failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsDescribeConnectionCmd() *cobra.Command {
	var name string

	cmd := &cobra.Command{
		Use:   "describe-connection",
		Short: "DescribeConnection",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.DescribeConnectionInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			out, err := client.DescribeConnection(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-connection failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsDescribeEventBusCmd() *cobra.Command {
	var name string

	cmd := &cobra.Command{
		Use:   "describe-event-bus",
		Short: "DescribeEventBus",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.DescribeEventBusInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			out, err := client.DescribeEventBus(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-event-bus failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsDescribeRuleCmd() *cobra.Command {
	var name string
	var eventBusName string

	cmd := &cobra.Command{
		Use:   "describe-rule",
		Short: "DescribeRule",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.DescribeRuleInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			if eventBusName != "" {
				input.EventBusName = aws.String(eventBusName)
			}

			out, err := client.DescribeRule(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-rule failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().StringVar(&eventBusName, "event-bus-name", "", "Event bus name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsListEventBusesCmd() *cobra.Command {
	var limit int32
	var namePrefix string
	var nextToken string

	cmd := &cobra.Command{
		Use:   "list-event-buses",
		Short: "ListEventBuses",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.ListEventBusesInput{}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			if namePrefix != "" {
				input.NamePrefix = aws.String(namePrefix)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.ListEventBuses(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-event-buses failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().StringVar(&namePrefix, "name-prefix", "", "Name prefix")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsListRulesCmd() *cobra.Command {
	var eventBusName string
	var limit int32
	var namePrefix string
	var nextToken string

	cmd := &cobra.Command{
		Use:   "list-rules",
		Short: "ListRules",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.ListRulesInput{}

			if eventBusName != "" {
				input.EventBusName = aws.String(eventBusName)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			if namePrefix != "" {
				input.NamePrefix = aws.String(namePrefix)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.ListRules(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-rules failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&eventBusName, "event-bus-name", "", "Event bus name")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().StringVar(&namePrefix, "name-prefix", "", "Name prefix")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsListTagsForResourceCmd() *cobra.Command {
	var resourceARN string

	cmd := &cobra.Command{
		Use:   "list-tags-for-resource",
		Short: "ListTagsForResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.ListTagsForResourceInput{}

			if resourceARN != "" {
				input.ResourceARN = aws.String(resourceARN)
			}

			out, err := client.ListTagsForResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-tags-for-resource failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceARN, "resource-arn", "", "Resource arn")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsListTargetsByRuleCmd() *cobra.Command {
	var rule string
	var eventBusName string
	var limit int32
	var nextToken string

	cmd := &cobra.Command{
		Use:   "list-targets-by-rule",
		Short: "ListTargetsByRule",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.ListTargetsByRuleInput{}

			if rule != "" {
				input.Rule = aws.String(rule)
			}

			if eventBusName != "" {
				input.EventBusName = aws.String(eventBusName)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.ListTargetsByRule(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-targets-by-rule failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&rule, "rule", "", "Rule")

	cmd.Flags().StringVar(&eventBusName, "event-bus-name", "", "Event bus name")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsPutEventsCmd() *cobra.Command {
	var entries string
	var endpointId string

	cmd := &cobra.Command{
		Use:   "put-events",
		Short: "PutEvents",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.PutEventsInput{}

			if entries != "" {
				if err := json.Unmarshal([]byte(entries), &input.Entries); err != nil {
					return fmt.Errorf("put-events: parse --entries: %w", err)
				}
			}

			if endpointId != "" {
				input.EndpointId = aws.String(endpointId)
			}

			out, err := client.PutEvents(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-events failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&entries, "entries", "", "Entries (JSON)")

	cmd.Flags().StringVar(&endpointId, "endpoint-id", "", "Endpoint id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsPutRuleCmd() *cobra.Command {
	var name string
	var description string
	var eventBusName string
	var eventPattern string
	var roleArn string
	var scheduleExpression string
	var state string
	var tags []string

	cmd := &cobra.Command{
		Use:   "put-rule",
		Short: "PutRule",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.PutRuleInput{}

			if name != "" {
				input.Name = aws.String(name)
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			if eventBusName != "" {
				input.EventBusName = aws.String(eventBusName)
			}

			if eventPattern != "" {
				input.EventPattern = aws.String(eventPattern)
			}

			if roleArn != "" {
				input.RoleArn = aws.String(roleArn)
			}

			if scheduleExpression != "" {
				input.ScheduleExpression = aws.String(scheduleExpression)
			}

			if state != "" {
				input.State = types.RuleState(state)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("put-rule: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			out, err := client.PutRule(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-rule failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Name")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().StringVar(&eventBusName, "event-bus-name", "", "Event bus name")

	cmd.Flags().StringVar(&eventPattern, "event-pattern", "", "Event pattern")

	cmd.Flags().StringVar(&roleArn, "role-arn", "", "Role arn")

	cmd.Flags().StringVar(&scheduleExpression, "schedule-expression", "", "Schedule expression")

	cmd.Flags().StringVar(&state, "state", "", "State")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsPutTargetsCmd() *cobra.Command {
	var rule string
	var targets string
	var eventBusName string

	cmd := &cobra.Command{
		Use:   "put-targets",
		Short: "PutTargets",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.PutTargetsInput{}

			if rule != "" {
				input.Rule = aws.String(rule)
			}

			if targets != "" {
				if err := json.Unmarshal([]byte(targets), &input.Targets); err != nil {
					return fmt.Errorf("put-targets: parse --targets: %w", err)
				}
			}

			if eventBusName != "" {
				input.EventBusName = aws.String(eventBusName)
			}

			out, err := client.PutTargets(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-targets failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&rule, "rule", "", "Rule")

	cmd.Flags().StringVar(&targets, "targets", "", "Targets (JSON)")

	cmd.Flags().StringVar(&eventBusName, "event-bus-name", "", "Event bus name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsRemoveTargetsCmd() *cobra.Command {
	var ids []string
	var rule string
	var eventBusName string
	var force bool

	cmd := &cobra.Command{
		Use:   "remove-targets",
		Short: "RemoveTargets",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.RemoveTargetsInput{}

			if len(ids) > 0 {
				input.Ids = ids
			}

			if rule != "" {
				input.Rule = aws.String(rule)
			}

			if eventBusName != "" {
				input.EventBusName = aws.String(eventBusName)
			}

			if force {
				input.Force = force
			}

			out, err := client.RemoveTargets(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("remove-targets failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&ids, "ids", nil, "Ids")

	cmd.Flags().StringVar(&rule, "rule", "", "Rule")

	cmd.Flags().StringVar(&eventBusName, "event-bus-name", "", "Event bus name")

	cmd.Flags().BoolVar(&force, "force", false, "Force")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsTagResourceCmd() *cobra.Command {
	var resourceARN string
	var tags []string

	cmd := &cobra.Command{
		Use:   "tag-resource",
		Short: "TagResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.TagResourceInput{}

			if resourceARN != "" {
				input.ResourceARN = aws.String(resourceARN)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("tag-resource: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			_, err = client.TagResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("tag-resource failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceARN, "resource-arn", "", "Resource arn")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newEventsUntagResourceCmd() *cobra.Command {
	var resourceARN string
	var tagKeys []string

	cmd := &cobra.Command{
		Use:   "untag-resource",
		Short: "UntagResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := eventbridge.NewFromConfig(cfg, func(o *eventbridge.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &eventbridge.UntagResourceInput{}

			if resourceARN != "" {
				input.ResourceARN = aws.String(resourceARN)
			}

			if len(tagKeys) > 0 {
				input.TagKeys = tagKeys
			}

			_, err = client.UntagResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("untag-resource failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceARN, "resource-arn", "", "Resource arn")

	cmd.Flags().StringArrayVar(&tagKeys, "tag-keys", nil, "Tag keys")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
