// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/aws/aws-sdk-go-v2/service/sqs/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newSQSCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "sqs",
		Short: "SQS commands",
	}

	cmd.AddCommand(
		newSQSAddPermissionCmd(),
		newSQSChangeMessageVisibilityCmd(),
		newSQSChangeMessageVisibilityBatchCmd(),
		newSQSCreateQueueCmd(),
		newSQSDeleteMessageCmd(),
		newSQSDeleteMessageBatchCmd(),
		newSQSDeleteQueueCmd(),
		newSQSGetQueueAttributesCmd(),
		newSQSGetQueueUrlCmd(),
		newSQSListQueueTagsCmd(),
		newSQSListQueuesCmd(),
		newSQSPurgeQueueCmd(),
		newSQSReceiveMessageCmd(),
		newSQSRemovePermissionCmd(),
		newSQSSendMessageCmd(),
		newSQSSendMessageBatchCmd(),
		newSQSSetQueueAttributesCmd(),
		newSQSTagQueueCmd(),
		newSQSUntagQueueCmd(),
	)

	return cmd
}

func newSQSAddPermissionCmd() *cobra.Command {
	var aWSAccountIds []string
	var actions []string
	var label string
	var queueUrl string

	cmd := &cobra.Command{
		Use:   "add-permission",
		Short: "AddPermission",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.AddPermissionInput{}

			if len(aWSAccountIds) > 0 {
				input.AWSAccountIds = aWSAccountIds
			}

			if len(actions) > 0 {
				input.Actions = actions
			}

			if label != "" {
				input.Label = aws.String(label)
			}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			_, err = client.AddPermission(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("add-permission failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&aWSAccountIds, "aws-account-ids", nil, "Aws account ids")

	cmd.Flags().StringArrayVar(&actions, "actions", nil, "Actions")

	cmd.Flags().StringVar(&label, "label", "", "Label")

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSChangeMessageVisibilityCmd() *cobra.Command {
	var queueUrl string
	var receiptHandle string
	var visibilityTimeout int32

	cmd := &cobra.Command{
		Use:   "change-message-visibility",
		Short: "ChangeMessageVisibility",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.ChangeMessageVisibilityInput{}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			if receiptHandle != "" {
				input.ReceiptHandle = aws.String(receiptHandle)
			}

			if visibilityTimeout != 0 {
				input.VisibilityTimeout = visibilityTimeout
			}

			_, err = client.ChangeMessageVisibility(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("change-message-visibility failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().StringVar(&receiptHandle, "receipt-handle", "", "Receipt handle")

	cmd.Flags().Int32Var(&visibilityTimeout, "visibility-timeout", 0, "Visibility timeout")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSChangeMessageVisibilityBatchCmd() *cobra.Command {
	var entries []string
	var queueUrl string

	cmd := &cobra.Command{
		Use:   "change-message-visibility-batch",
		Short: "ChangeMessageVisibilityBatch",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.ChangeMessageVisibilityBatchInput{}

			for _, raw := range entries {
				var val types.ChangeMessageVisibilityBatchRequestEntry
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("change-message-visibility-batch: parse --entries: %w", err)
				}
				input.Entries = append(input.Entries, val)
			}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			out, err := client.ChangeMessageVisibilityBatch(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("change-message-visibility-batch failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&entries, "entries", nil, "Entries (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSCreateQueueCmd() *cobra.Command {
	var queueName string
	var attributes string
	var tags string

	cmd := &cobra.Command{
		Use:   "create-queue",
		Short: "CreateQueue",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.CreateQueueInput{}

			if queueName != "" {
				input.QueueName = aws.String(queueName)
			}

			if attributes != "" {
				if err := json.Unmarshal([]byte(attributes), &input.Attributes); err != nil {
					return fmt.Errorf("create-queue: parse --attributes: %w", err)
				}
			}

			if tags != "" {
				if err := json.Unmarshal([]byte(tags), &input.Tags); err != nil {
					return fmt.Errorf("create-queue: parse --tags: %w", err)
				}
			}

			out, err := client.CreateQueue(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-queue failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueName, "queue-name", "", "Queue name")

	cmd.Flags().StringVar(&attributes, "attributes", "", "Attributes (JSON)")

	cmd.Flags().StringVar(&tags, "tags", "", "Tags (JSON)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSDeleteMessageCmd() *cobra.Command {
	var queueUrl string
	var receiptHandle string

	cmd := &cobra.Command{
		Use:   "delete-message",
		Short: "DeleteMessage",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.DeleteMessageInput{}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			if receiptHandle != "" {
				input.ReceiptHandle = aws.String(receiptHandle)
			}

			_, err = client.DeleteMessage(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-message failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().StringVar(&receiptHandle, "receipt-handle", "", "Receipt handle")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSDeleteMessageBatchCmd() *cobra.Command {
	var entries []string
	var queueUrl string

	cmd := &cobra.Command{
		Use:   "delete-message-batch",
		Short: "DeleteMessageBatch",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.DeleteMessageBatchInput{}

			for _, raw := range entries {
				var val types.DeleteMessageBatchRequestEntry
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("delete-message-batch: parse --entries: %w", err)
				}
				input.Entries = append(input.Entries, val)
			}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			out, err := client.DeleteMessageBatch(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-message-batch failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&entries, "entries", nil, "Entries (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSDeleteQueueCmd() *cobra.Command {
	var queueUrl string

	cmd := &cobra.Command{
		Use:   "delete-queue",
		Short: "DeleteQueue",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.DeleteQueueInput{}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			_, err = client.DeleteQueue(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-queue failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSGetQueueAttributesCmd() *cobra.Command {
	var queueUrl string
	var attributeNames []string

	cmd := &cobra.Command{
		Use:   "get-queue-attributes",
		Short: "GetQueueAttributes",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.GetQueueAttributesInput{}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			for _, s := range attributeNames {
				input.AttributeNames = append(input.AttributeNames, types.QueueAttributeName(s))
			}

			out, err := client.GetQueueAttributes(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-queue-attributes failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().StringArrayVar(&attributeNames, "attribute-names", nil, "Attribute names")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSGetQueueUrlCmd() *cobra.Command {
	var queueName string
	var queueOwnerAWSAccountId string

	cmd := &cobra.Command{
		Use:   "get-queue-url",
		Short: "GetQueueUrl",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.GetQueueUrlInput{}

			if queueName != "" {
				input.QueueName = aws.String(queueName)
			}

			if queueOwnerAWSAccountId != "" {
				input.QueueOwnerAWSAccountId = aws.String(queueOwnerAWSAccountId)
			}

			out, err := client.GetQueueUrl(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-queue-url failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueName, "queue-name", "", "Queue name")

	cmd.Flags().StringVar(&queueOwnerAWSAccountId, "queue-owner-aws-account-id", "", "Queue owner aws account id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSListQueueTagsCmd() *cobra.Command {
	var queueUrl string

	cmd := &cobra.Command{
		Use:   "list-queue-tags",
		Short: "ListQueueTags",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.ListQueueTagsInput{}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			out, err := client.ListQueueTags(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-queue-tags failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSListQueuesCmd() *cobra.Command {
	var maxResults int32
	var nextToken string
	var queueNamePrefix string

	cmd := &cobra.Command{
		Use:   "list-queues",
		Short: "ListQueues",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.ListQueuesInput{}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if queueNamePrefix != "" {
				input.QueueNamePrefix = aws.String(queueNamePrefix)
			}

			out, err := client.ListQueues(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-queues failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&queueNamePrefix, "queue-name-prefix", "", "Queue name prefix")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSPurgeQueueCmd() *cobra.Command {
	var queueUrl string

	cmd := &cobra.Command{
		Use:   "purge-queue",
		Short: "PurgeQueue",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.PurgeQueueInput{}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			_, err = client.PurgeQueue(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("purge-queue failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSReceiveMessageCmd() *cobra.Command {
	var queueUrl string
	var attributeNames []string
	var maxNumberOfMessages int32
	var messageAttributeNames []string
	var messageSystemAttributeNames []string
	var receiveRequestAttemptId string
	var visibilityTimeout int32
	var waitTimeSeconds int32

	cmd := &cobra.Command{
		Use:   "receive-message",
		Short: "ReceiveMessage",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.ReceiveMessageInput{}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			for _, s := range attributeNames {
				input.AttributeNames = append(input.AttributeNames, types.QueueAttributeName(s))
			}

			if maxNumberOfMessages != 0 {
				input.MaxNumberOfMessages = maxNumberOfMessages
			}

			if len(messageAttributeNames) > 0 {
				input.MessageAttributeNames = messageAttributeNames
			}

			for _, s := range messageSystemAttributeNames {
				input.MessageSystemAttributeNames = append(input.MessageSystemAttributeNames, types.MessageSystemAttributeName(s))
			}

			if receiveRequestAttemptId != "" {
				input.ReceiveRequestAttemptId = aws.String(receiveRequestAttemptId)
			}

			if visibilityTimeout != 0 {
				input.VisibilityTimeout = visibilityTimeout
			}

			if waitTimeSeconds != 0 {
				input.WaitTimeSeconds = waitTimeSeconds
			}

			out, err := client.ReceiveMessage(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("receive-message failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().StringArrayVar(&attributeNames, "attribute-names", nil, "Attribute names")

	cmd.Flags().Int32Var(&maxNumberOfMessages, "max-number-of-messages", 0, "Max number of messages")

	cmd.Flags().StringArrayVar(&messageAttributeNames, "message-attribute-names", nil, "Message attribute names")

	cmd.Flags().StringArrayVar(&messageSystemAttributeNames, "message-system-attribute-names", nil, "Message system attribute names")

	cmd.Flags().StringVar(&receiveRequestAttemptId, "receive-request-attempt-id", "", "Receive request attempt id")

	cmd.Flags().Int32Var(&visibilityTimeout, "visibility-timeout", 0, "Visibility timeout")

	cmd.Flags().Int32Var(&waitTimeSeconds, "wait-time-seconds", 0, "Wait time seconds")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSRemovePermissionCmd() *cobra.Command {
	var label string
	var queueUrl string

	cmd := &cobra.Command{
		Use:   "remove-permission",
		Short: "RemovePermission",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.RemovePermissionInput{}

			if label != "" {
				input.Label = aws.String(label)
			}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			_, err = client.RemovePermission(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("remove-permission failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&label, "label", "", "Label")

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSSendMessageCmd() *cobra.Command {
	var messageBody string
	var queueUrl string
	var delaySeconds int32
	var messageAttributes string
	var messageDeduplicationId string
	var messageGroupId string
	var messageSystemAttributes string

	cmd := &cobra.Command{
		Use:   "send-message",
		Short: "SendMessage",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.SendMessageInput{}

			if messageBody != "" {
				input.MessageBody = aws.String(messageBody)
			}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			if delaySeconds != 0 {
				input.DelaySeconds = delaySeconds
			}

			if messageAttributes != "" {
				if err := json.Unmarshal([]byte(messageAttributes), &input.MessageAttributes); err != nil {
					return fmt.Errorf("send-message: parse --message-attributes: %w", err)
				}
			}

			if messageDeduplicationId != "" {
				input.MessageDeduplicationId = aws.String(messageDeduplicationId)
			}

			if messageGroupId != "" {
				input.MessageGroupId = aws.String(messageGroupId)
			}

			if messageSystemAttributes != "" {
				if err := json.Unmarshal([]byte(messageSystemAttributes), &input.MessageSystemAttributes); err != nil {
					return fmt.Errorf("send-message: parse --message-system-attributes: %w", err)
				}
			}

			out, err := client.SendMessage(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("send-message failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&messageBody, "message-body", "", "Message body")

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().Int32Var(&delaySeconds, "delay-seconds", 0, "Delay seconds")

	cmd.Flags().StringVar(&messageAttributes, "message-attributes", "", "Message attributes (JSON)")

	cmd.Flags().StringVar(&messageDeduplicationId, "message-deduplication-id", "", "Message deduplication id")

	cmd.Flags().StringVar(&messageGroupId, "message-group-id", "", "Message group id")

	cmd.Flags().StringVar(&messageSystemAttributes, "message-system-attributes", "", "Message system attributes (JSON)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSSendMessageBatchCmd() *cobra.Command {
	var entries string
	var queueUrl string

	cmd := &cobra.Command{
		Use:   "send-message-batch",
		Short: "SendMessageBatch",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.SendMessageBatchInput{}

			if entries != "" {
				if err := json.Unmarshal([]byte(entries), &input.Entries); err != nil {
					return fmt.Errorf("send-message-batch: parse --entries: %w", err)
				}
			}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			out, err := client.SendMessageBatch(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("send-message-batch failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&entries, "entries", "", "Entries (JSON)")

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSSetQueueAttributesCmd() *cobra.Command {
	var attributes string
	var queueUrl string

	cmd := &cobra.Command{
		Use:   "set-queue-attributes",
		Short: "SetQueueAttributes",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.SetQueueAttributesInput{}

			if attributes != "" {
				if err := json.Unmarshal([]byte(attributes), &input.Attributes); err != nil {
					return fmt.Errorf("set-queue-attributes: parse --attributes: %w", err)
				}
			}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			_, err = client.SetQueueAttributes(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("set-queue-attributes failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&attributes, "attributes", "", "Attributes (JSON)")

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSTagQueueCmd() *cobra.Command {
	var queueUrl string
	var tags string

	cmd := &cobra.Command{
		Use:   "tag-queue",
		Short: "TagQueue",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.TagQueueInput{}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			if tags != "" {
				if err := json.Unmarshal([]byte(tags), &input.Tags); err != nil {
					return fmt.Errorf("tag-queue: parse --tags: %w", err)
				}
			}

			_, err = client.TagQueue(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("tag-queue failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().StringVar(&tags, "tags", "", "Tags (JSON)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newSQSUntagQueueCmd() *cobra.Command {
	var queueUrl string
	var tagKeys []string

	cmd := &cobra.Command{
		Use:   "untag-queue",
		Short: "UntagQueue",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := sqs.NewFromConfig(cfg, func(o *sqs.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &sqs.UntagQueueInput{}

			if queueUrl != "" {
				input.QueueUrl = aws.String(queueUrl)
			}

			if len(tagKeys) > 0 {
				input.TagKeys = tagKeys
			}

			_, err = client.UntagQueue(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("untag-queue failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&queueUrl, "queue-url", "", "Queue url")

	cmd.Flags().StringArrayVar(&tagKeys, "tag-keys", nil, "Tag keys")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
