// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/iam"
	"github.com/aws/aws-sdk-go-v2/service/iam/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newIAMCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "iam",
		Short: "IAM commands",
	}

	cmd.AddCommand(
		newIAMAddRoleToInstanceProfileCmd(),
		newIAMAttachRolePolicyCmd(),
		newIAMAttachUserPolicyCmd(),
		newIAMCreateAccessKeyCmd(),
		newIAMCreateInstanceProfileCmd(),
		newIAMCreateOpenIDConnectProviderCmd(),
		newIAMCreatePolicyCmd(),
		newIAMCreateRoleCmd(),
		newIAMCreateUserCmd(),
		newIAMDeleteAccessKeyCmd(),
		newIAMDeleteInstanceProfileCmd(),
		newIAMDeleteOpenIDConnectProviderCmd(),
		newIAMDeletePolicyCmd(),
		newIAMDeleteRoleCmd(),
		newIAMDeleteRolePolicyCmd(),
		newIAMDeleteUserCmd(),
		newIAMDetachRolePolicyCmd(),
		newIAMDetachUserPolicyCmd(),
		newIAMGetInstanceProfileCmd(),
		newIAMGetOpenIDConnectProviderCmd(),
		newIAMGetPolicyCmd(),
		newIAMGetRoleCmd(),
		newIAMGetRolePolicyCmd(),
		newIAMGetUserCmd(),
		newIAMListAccessKeysCmd(),
		newIAMListAttachedRolePoliciesCmd(),
		newIAMListInstanceProfilesCmd(),
		newIAMListInstanceProfilesForRoleCmd(),
		newIAMListOpenIDConnectProvidersCmd(),
		newIAMListPoliciesCmd(),
		newIAMListRolePoliciesCmd(),
		newIAMListRolesCmd(),
		newIAMListUsersCmd(),
		newIAMPutRolePolicyCmd(),
		newIAMRemoveRoleFromInstanceProfileCmd(),
		newIAMTagRoleCmd(),
		newIAMUpdateAssumeRolePolicyCmd(),
		newIAMUpdateOpenIDConnectProviderThumbprintCmd(),
		newIAMUpdateRoleCmd(),
	)

	return cmd
}

func newIAMAddRoleToInstanceProfileCmd() *cobra.Command {
	var instanceProfileName string
	var roleName string

	cmd := &cobra.Command{
		Use:   "add-role-to-instance-profile",
		Short: "AddRoleToInstanceProfile",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.AddRoleToInstanceProfileInput{}

			if instanceProfileName != "" {
				input.InstanceProfileName = aws.String(instanceProfileName)
			}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			_, err = client.AddRoleToInstanceProfile(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("add-role-to-instance-profile failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&instanceProfileName, "instance-profile-name", "", "Instance profile name")

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMAttachRolePolicyCmd() *cobra.Command {
	var policyArn string
	var roleName string

	cmd := &cobra.Command{
		Use:   "attach-role-policy",
		Short: "AttachRolePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.AttachRolePolicyInput{}

			if policyArn != "" {
				input.PolicyArn = aws.String(policyArn)
			}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			_, err = client.AttachRolePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("attach-role-policy failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyArn, "policy-arn", "", "Policy arn")

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMAttachUserPolicyCmd() *cobra.Command {
	var policyArn string
	var userName string

	cmd := &cobra.Command{
		Use:   "attach-user-policy",
		Short: "AttachUserPolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.AttachUserPolicyInput{}

			if policyArn != "" {
				input.PolicyArn = aws.String(policyArn)
			}

			if userName != "" {
				input.UserName = aws.String(userName)
			}

			_, err = client.AttachUserPolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("attach-user-policy failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyArn, "policy-arn", "", "Policy arn")

	cmd.Flags().StringVar(&userName, "user-name", "", "User name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMCreateAccessKeyCmd() *cobra.Command {
	var userName string

	cmd := &cobra.Command{
		Use:   "create-access-key",
		Short: "CreateAccessKey",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.CreateAccessKeyInput{}

			if userName != "" {
				input.UserName = aws.String(userName)
			}

			out, err := client.CreateAccessKey(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-access-key failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&userName, "user-name", "", "User name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMCreateInstanceProfileCmd() *cobra.Command {
	var instanceProfileName string
	var path string
	var tags []string

	cmd := &cobra.Command{
		Use:   "create-instance-profile",
		Short: "CreateInstanceProfile",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.CreateInstanceProfileInput{}

			if instanceProfileName != "" {
				input.InstanceProfileName = aws.String(instanceProfileName)
			}

			if path != "" {
				input.Path = aws.String(path)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-instance-profile: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			out, err := client.CreateInstanceProfile(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-instance-profile failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&instanceProfileName, "instance-profile-name", "", "Instance profile name")

	cmd.Flags().StringVar(&path, "path", "", "Path")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMCreateOpenIDConnectProviderCmd() *cobra.Command {
	var url string
	var clientIDList []string
	var tags []string
	var thumbprintList []string

	cmd := &cobra.Command{
		Use:   "create-open-id-connect-provider",
		Short: "CreateOpenIDConnectProvider",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.CreateOpenIDConnectProviderInput{}

			if url != "" {
				input.Url = aws.String(url)
			}

			if len(clientIDList) > 0 {
				input.ClientIDList = clientIDList
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-open-id-connect-provider: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			if len(thumbprintList) > 0 {
				input.ThumbprintList = thumbprintList
			}

			out, err := client.CreateOpenIDConnectProvider(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-open-id-connect-provider failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&url, "url", "", "Url")

	cmd.Flags().StringArrayVar(&clientIDList, "client-id-list", nil, "Client id list")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().StringArrayVar(&thumbprintList, "thumbprint-list", nil, "Thumbprint list")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMCreatePolicyCmd() *cobra.Command {
	var policyDocument string
	var policyName string
	var description string
	var path string
	var tags []string

	cmd := &cobra.Command{
		Use:   "create-policy",
		Short: "CreatePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.CreatePolicyInput{}

			if policyDocument != "" {
				input.PolicyDocument = aws.String(policyDocument)
			}

			if policyName != "" {
				input.PolicyName = aws.String(policyName)
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			if path != "" {
				input.Path = aws.String(path)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-policy: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			out, err := client.CreatePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-policy failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyDocument, "policy-document", "", "Policy document")

	cmd.Flags().StringVar(&policyName, "policy-name", "", "Policy name")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().StringVar(&path, "path", "", "Path")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMCreateRoleCmd() *cobra.Command {
	var assumeRolePolicyDocument string
	var roleName string
	var description string
	var maxSessionDuration int32
	var path string
	var permissionsBoundary string
	var tags []string

	cmd := &cobra.Command{
		Use:   "create-role",
		Short: "CreateRole",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.CreateRoleInput{}

			if assumeRolePolicyDocument != "" {
				input.AssumeRolePolicyDocument = aws.String(assumeRolePolicyDocument)
			}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			if maxSessionDuration != 0 {
				input.MaxSessionDuration = aws.Int32(maxSessionDuration)
			}

			if path != "" {
				input.Path = aws.String(path)
			}

			if permissionsBoundary != "" {
				input.PermissionsBoundary = aws.String(permissionsBoundary)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-role: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			out, err := client.CreateRole(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-role failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&assumeRolePolicyDocument, "assume-role-policy-document", "", "Assume role policy document")

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().Int32Var(&maxSessionDuration, "max-session-duration", 0, "Max session duration")

	cmd.Flags().StringVar(&path, "path", "", "Path")

	cmd.Flags().StringVar(&permissionsBoundary, "permissions-boundary", "", "Permissions boundary")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMCreateUserCmd() *cobra.Command {
	var userName string
	var path string
	var permissionsBoundary string
	var tags []string

	cmd := &cobra.Command{
		Use:   "create-user",
		Short: "CreateUser",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.CreateUserInput{}

			if userName != "" {
				input.UserName = aws.String(userName)
			}

			if path != "" {
				input.Path = aws.String(path)
			}

			if permissionsBoundary != "" {
				input.PermissionsBoundary = aws.String(permissionsBoundary)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-user: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			out, err := client.CreateUser(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-user failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&userName, "user-name", "", "User name")

	cmd.Flags().StringVar(&path, "path", "", "Path")

	cmd.Flags().StringVar(&permissionsBoundary, "permissions-boundary", "", "Permissions boundary")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMDeleteAccessKeyCmd() *cobra.Command {
	var accessKeyId string
	var userName string

	cmd := &cobra.Command{
		Use:   "delete-access-key",
		Short: "DeleteAccessKey",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.DeleteAccessKeyInput{}

			if accessKeyId != "" {
				input.AccessKeyId = aws.String(accessKeyId)
			}

			if userName != "" {
				input.UserName = aws.String(userName)
			}

			_, err = client.DeleteAccessKey(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-access-key failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&accessKeyId, "access-key-id", "", "Access key id")

	cmd.Flags().StringVar(&userName, "user-name", "", "User name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMDeleteInstanceProfileCmd() *cobra.Command {
	var instanceProfileName string

	cmd := &cobra.Command{
		Use:   "delete-instance-profile",
		Short: "DeleteInstanceProfile",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.DeleteInstanceProfileInput{}

			if instanceProfileName != "" {
				input.InstanceProfileName = aws.String(instanceProfileName)
			}

			_, err = client.DeleteInstanceProfile(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-instance-profile failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&instanceProfileName, "instance-profile-name", "", "Instance profile name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMDeleteOpenIDConnectProviderCmd() *cobra.Command {
	var openIDConnectProviderArn string

	cmd := &cobra.Command{
		Use:   "delete-open-id-connect-provider",
		Short: "DeleteOpenIDConnectProvider",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.DeleteOpenIDConnectProviderInput{}

			if openIDConnectProviderArn != "" {
				input.OpenIDConnectProviderArn = aws.String(openIDConnectProviderArn)
			}

			_, err = client.DeleteOpenIDConnectProvider(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-open-id-connect-provider failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&openIDConnectProviderArn, "open-id-connect-provider-arn", "", "Open id connect provider arn")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMDeletePolicyCmd() *cobra.Command {
	var policyArn string

	cmd := &cobra.Command{
		Use:   "delete-policy",
		Short: "DeletePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.DeletePolicyInput{}

			if policyArn != "" {
				input.PolicyArn = aws.String(policyArn)
			}

			_, err = client.DeletePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-policy failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyArn, "policy-arn", "", "Policy arn")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMDeleteRoleCmd() *cobra.Command {
	var roleName string

	cmd := &cobra.Command{
		Use:   "delete-role",
		Short: "DeleteRole",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.DeleteRoleInput{}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			_, err = client.DeleteRole(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-role failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMDeleteRolePolicyCmd() *cobra.Command {
	var policyName string
	var roleName string

	cmd := &cobra.Command{
		Use:   "delete-role-policy",
		Short: "DeleteRolePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.DeleteRolePolicyInput{}

			if policyName != "" {
				input.PolicyName = aws.String(policyName)
			}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			_, err = client.DeleteRolePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-role-policy failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyName, "policy-name", "", "Policy name")

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMDeleteUserCmd() *cobra.Command {
	var userName string

	cmd := &cobra.Command{
		Use:   "delete-user",
		Short: "DeleteUser",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.DeleteUserInput{}

			if userName != "" {
				input.UserName = aws.String(userName)
			}

			_, err = client.DeleteUser(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-user failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&userName, "user-name", "", "User name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMDetachRolePolicyCmd() *cobra.Command {
	var policyArn string
	var roleName string

	cmd := &cobra.Command{
		Use:   "detach-role-policy",
		Short: "DetachRolePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.DetachRolePolicyInput{}

			if policyArn != "" {
				input.PolicyArn = aws.String(policyArn)
			}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			_, err = client.DetachRolePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("detach-role-policy failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyArn, "policy-arn", "", "Policy arn")

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMDetachUserPolicyCmd() *cobra.Command {
	var policyArn string
	var userName string

	cmd := &cobra.Command{
		Use:   "detach-user-policy",
		Short: "DetachUserPolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.DetachUserPolicyInput{}

			if policyArn != "" {
				input.PolicyArn = aws.String(policyArn)
			}

			if userName != "" {
				input.UserName = aws.String(userName)
			}

			_, err = client.DetachUserPolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("detach-user-policy failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyArn, "policy-arn", "", "Policy arn")

	cmd.Flags().StringVar(&userName, "user-name", "", "User name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMGetInstanceProfileCmd() *cobra.Command {
	var instanceProfileName string

	cmd := &cobra.Command{
		Use:   "get-instance-profile",
		Short: "GetInstanceProfile",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.GetInstanceProfileInput{}

			if instanceProfileName != "" {
				input.InstanceProfileName = aws.String(instanceProfileName)
			}

			out, err := client.GetInstanceProfile(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-instance-profile failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&instanceProfileName, "instance-profile-name", "", "Instance profile name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMGetOpenIDConnectProviderCmd() *cobra.Command {
	var openIDConnectProviderArn string

	cmd := &cobra.Command{
		Use:   "get-open-id-connect-provider",
		Short: "GetOpenIDConnectProvider",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.GetOpenIDConnectProviderInput{}

			if openIDConnectProviderArn != "" {
				input.OpenIDConnectProviderArn = aws.String(openIDConnectProviderArn)
			}

			out, err := client.GetOpenIDConnectProvider(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-open-id-connect-provider failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&openIDConnectProviderArn, "open-id-connect-provider-arn", "", "Open id connect provider arn")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMGetPolicyCmd() *cobra.Command {
	var policyArn string

	cmd := &cobra.Command{
		Use:   "get-policy",
		Short: "GetPolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.GetPolicyInput{}

			if policyArn != "" {
				input.PolicyArn = aws.String(policyArn)
			}

			out, err := client.GetPolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-policy failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyArn, "policy-arn", "", "Policy arn")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMGetRoleCmd() *cobra.Command {
	var roleName string

	cmd := &cobra.Command{
		Use:   "get-role",
		Short: "GetRole",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.GetRoleInput{}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			out, err := client.GetRole(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-role failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMGetRolePolicyCmd() *cobra.Command {
	var policyName string
	var roleName string

	cmd := &cobra.Command{
		Use:   "get-role-policy",
		Short: "GetRolePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.GetRolePolicyInput{}

			if policyName != "" {
				input.PolicyName = aws.String(policyName)
			}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			out, err := client.GetRolePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-role-policy failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyName, "policy-name", "", "Policy name")

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMGetUserCmd() *cobra.Command {
	var userName string

	cmd := &cobra.Command{
		Use:   "get-user",
		Short: "GetUser",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.GetUserInput{}

			if userName != "" {
				input.UserName = aws.String(userName)
			}

			out, err := client.GetUser(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-user failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&userName, "user-name", "", "User name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMListAccessKeysCmd() *cobra.Command {
	var marker string
	var maxItems int32
	var userName string

	cmd := &cobra.Command{
		Use:   "list-access-keys",
		Short: "ListAccessKeys",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.ListAccessKeysInput{}

			if marker != "" {
				input.Marker = aws.String(marker)
			}

			if maxItems != 0 {
				input.MaxItems = aws.Int32(maxItems)
			}

			if userName != "" {
				input.UserName = aws.String(userName)
			}

			out, err := client.ListAccessKeys(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-access-keys failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&marker, "marker", "", "Marker")

	cmd.Flags().Int32Var(&maxItems, "max-items", 0, "Max items")

	cmd.Flags().StringVar(&userName, "user-name", "", "User name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMListAttachedRolePoliciesCmd() *cobra.Command {
	var roleName string
	var marker string
	var maxItems int32
	var pathPrefix string

	cmd := &cobra.Command{
		Use:   "list-attached-role-policies",
		Short: "ListAttachedRolePolicies",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.ListAttachedRolePoliciesInput{}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			if marker != "" {
				input.Marker = aws.String(marker)
			}

			if maxItems != 0 {
				input.MaxItems = aws.Int32(maxItems)
			}

			if pathPrefix != "" {
				input.PathPrefix = aws.String(pathPrefix)
			}

			out, err := client.ListAttachedRolePolicies(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-attached-role-policies failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().StringVar(&marker, "marker", "", "Marker")

	cmd.Flags().Int32Var(&maxItems, "max-items", 0, "Max items")

	cmd.Flags().StringVar(&pathPrefix, "path-prefix", "", "Path prefix")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMListInstanceProfilesCmd() *cobra.Command {
	var marker string
	var maxItems int32
	var pathPrefix string

	cmd := &cobra.Command{
		Use:   "list-instance-profiles",
		Short: "ListInstanceProfiles",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.ListInstanceProfilesInput{}

			if marker != "" {
				input.Marker = aws.String(marker)
			}

			if maxItems != 0 {
				input.MaxItems = aws.Int32(maxItems)
			}

			if pathPrefix != "" {
				input.PathPrefix = aws.String(pathPrefix)
			}

			out, err := client.ListInstanceProfiles(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-instance-profiles failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&marker, "marker", "", "Marker")

	cmd.Flags().Int32Var(&maxItems, "max-items", 0, "Max items")

	cmd.Flags().StringVar(&pathPrefix, "path-prefix", "", "Path prefix")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMListInstanceProfilesForRoleCmd() *cobra.Command {
	var roleName string
	var marker string
	var maxItems int32

	cmd := &cobra.Command{
		Use:   "list-instance-profiles-for-role",
		Short: "ListInstanceProfilesForRole",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.ListInstanceProfilesForRoleInput{}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			if marker != "" {
				input.Marker = aws.String(marker)
			}

			if maxItems != 0 {
				input.MaxItems = aws.Int32(maxItems)
			}

			out, err := client.ListInstanceProfilesForRole(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-instance-profiles-for-role failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().StringVar(&marker, "marker", "", "Marker")

	cmd.Flags().Int32Var(&maxItems, "max-items", 0, "Max items")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMListOpenIDConnectProvidersCmd() *cobra.Command {

	cmd := &cobra.Command{
		Use:   "list-open-id-connect-providers",
		Short: "ListOpenIDConnectProviders",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.ListOpenIDConnectProvidersInput{}

			out, err := client.ListOpenIDConnectProviders(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-open-id-connect-providers failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMListPoliciesCmd() *cobra.Command {
	var marker string
	var maxItems int32
	var onlyAttached bool
	var pathPrefix string
	var policyUsageFilter string
	var scope string

	cmd := &cobra.Command{
		Use:   "list-policies",
		Short: "ListPolicies",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.ListPoliciesInput{}

			if marker != "" {
				input.Marker = aws.String(marker)
			}

			if maxItems != 0 {
				input.MaxItems = aws.Int32(maxItems)
			}

			if onlyAttached {
				input.OnlyAttached = onlyAttached
			}

			if pathPrefix != "" {
				input.PathPrefix = aws.String(pathPrefix)
			}

			if policyUsageFilter != "" {
				input.PolicyUsageFilter = types.PolicyUsageType(policyUsageFilter)
			}

			if scope != "" {
				input.Scope = types.PolicyScopeType(scope)
			}

			out, err := client.ListPolicies(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-policies failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&marker, "marker", "", "Marker")

	cmd.Flags().Int32Var(&maxItems, "max-items", 0, "Max items")

	cmd.Flags().BoolVar(&onlyAttached, "only-attached", false, "Only attached")

	cmd.Flags().StringVar(&pathPrefix, "path-prefix", "", "Path prefix")

	cmd.Flags().StringVar(&policyUsageFilter, "policy-usage-filter", "", "Policy usage filter")

	cmd.Flags().StringVar(&scope, "scope", "", "Scope")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMListRolePoliciesCmd() *cobra.Command {
	var roleName string
	var marker string
	var maxItems int32

	cmd := &cobra.Command{
		Use:   "list-role-policies",
		Short: "ListRolePolicies",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.ListRolePoliciesInput{}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			if marker != "" {
				input.Marker = aws.String(marker)
			}

			if maxItems != 0 {
				input.MaxItems = aws.Int32(maxItems)
			}

			out, err := client.ListRolePolicies(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-role-policies failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().StringVar(&marker, "marker", "", "Marker")

	cmd.Flags().Int32Var(&maxItems, "max-items", 0, "Max items")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMListRolesCmd() *cobra.Command {
	var marker string
	var maxItems int32
	var pathPrefix string

	cmd := &cobra.Command{
		Use:   "list-roles",
		Short: "ListRoles",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.ListRolesInput{}

			if marker != "" {
				input.Marker = aws.String(marker)
			}

			if maxItems != 0 {
				input.MaxItems = aws.Int32(maxItems)
			}

			if pathPrefix != "" {
				input.PathPrefix = aws.String(pathPrefix)
			}

			out, err := client.ListRoles(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-roles failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&marker, "marker", "", "Marker")

	cmd.Flags().Int32Var(&maxItems, "max-items", 0, "Max items")

	cmd.Flags().StringVar(&pathPrefix, "path-prefix", "", "Path prefix")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMListUsersCmd() *cobra.Command {
	var marker string
	var maxItems int32
	var pathPrefix string

	cmd := &cobra.Command{
		Use:   "list-users",
		Short: "ListUsers",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.ListUsersInput{}

			if marker != "" {
				input.Marker = aws.String(marker)
			}

			if maxItems != 0 {
				input.MaxItems = aws.Int32(maxItems)
			}

			if pathPrefix != "" {
				input.PathPrefix = aws.String(pathPrefix)
			}

			out, err := client.ListUsers(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-users failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&marker, "marker", "", "Marker")

	cmd.Flags().Int32Var(&maxItems, "max-items", 0, "Max items")

	cmd.Flags().StringVar(&pathPrefix, "path-prefix", "", "Path prefix")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMPutRolePolicyCmd() *cobra.Command {
	var policyDocument string
	var policyName string
	var roleName string

	cmd := &cobra.Command{
		Use:   "put-role-policy",
		Short: "PutRolePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.PutRolePolicyInput{}

			if policyDocument != "" {
				input.PolicyDocument = aws.String(policyDocument)
			}

			if policyName != "" {
				input.PolicyName = aws.String(policyName)
			}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			_, err = client.PutRolePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-role-policy failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyDocument, "policy-document", "", "Policy document")

	cmd.Flags().StringVar(&policyName, "policy-name", "", "Policy name")

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMRemoveRoleFromInstanceProfileCmd() *cobra.Command {
	var instanceProfileName string
	var roleName string

	cmd := &cobra.Command{
		Use:   "remove-role-from-instance-profile",
		Short: "RemoveRoleFromInstanceProfile",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.RemoveRoleFromInstanceProfileInput{}

			if instanceProfileName != "" {
				input.InstanceProfileName = aws.String(instanceProfileName)
			}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			_, err = client.RemoveRoleFromInstanceProfile(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("remove-role-from-instance-profile failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&instanceProfileName, "instance-profile-name", "", "Instance profile name")

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMTagRoleCmd() *cobra.Command {
	var roleName string
	var tags []string

	cmd := &cobra.Command{
		Use:   "tag-role",
		Short: "TagRole",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.TagRoleInput{}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("tag-role: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			_, err = client.TagRole(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("tag-role failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMUpdateAssumeRolePolicyCmd() *cobra.Command {
	var policyDocument string
	var roleName string

	cmd := &cobra.Command{
		Use:   "update-assume-role-policy",
		Short: "UpdateAssumeRolePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.UpdateAssumeRolePolicyInput{}

			if policyDocument != "" {
				input.PolicyDocument = aws.String(policyDocument)
			}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			_, err = client.UpdateAssumeRolePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-assume-role-policy failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&policyDocument, "policy-document", "", "Policy document")

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMUpdateOpenIDConnectProviderThumbprintCmd() *cobra.Command {
	var openIDConnectProviderArn string
	var thumbprintList []string

	cmd := &cobra.Command{
		Use:   "update-open-id-connect-provider-thumbprint",
		Short: "UpdateOpenIDConnectProviderThumbprint",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.UpdateOpenIDConnectProviderThumbprintInput{}

			if openIDConnectProviderArn != "" {
				input.OpenIDConnectProviderArn = aws.String(openIDConnectProviderArn)
			}

			if len(thumbprintList) > 0 {
				input.ThumbprintList = thumbprintList
			}

			_, err = client.UpdateOpenIDConnectProviderThumbprint(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-open-id-connect-provider-thumbprint failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&openIDConnectProviderArn, "open-id-connect-provider-arn", "", "Open id connect provider arn")

	cmd.Flags().StringArrayVar(&thumbprintList, "thumbprint-list", nil, "Thumbprint list")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newIAMUpdateRoleCmd() *cobra.Command {
	var roleName string
	var description string
	var maxSessionDuration int32

	cmd := &cobra.Command{
		Use:   "update-role",
		Short: "UpdateRole",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := iam.NewFromConfig(cfg, func(o *iam.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &iam.UpdateRoleInput{}

			if roleName != "" {
				input.RoleName = aws.String(roleName)
			}

			if description != "" {
				input.Description = aws.String(description)
			}

			if maxSessionDuration != 0 {
				input.MaxSessionDuration = aws.Int32(maxSessionDuration)
			}

			_, err = client.UpdateRole(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-role failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&roleName, "role-name", "", "Role name")

	cmd.Flags().StringVar(&description, "description", "", "Description")

	cmd.Flags().Int32Var(&maxSessionDuration, "max-session-duration", 0, "Max session duration")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
