// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/kinesis"
	"github.com/aws/aws-sdk-go-v2/service/kinesis/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
	"time"
)

func newKinesisCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "kinesis",
		Short: "Kinesis commands",
	}

	cmd.AddCommand(
		newKinesisCreateStreamCmd(),
		newKinesisDeleteStreamCmd(),
		newKinesisDescribeStreamCmd(),
		newKinesisDescribeStreamSummaryCmd(),
		newKinesisGetRecordsCmd(),
		newKinesisGetShardIteratorCmd(),
		newKinesisListShardsCmd(),
		newKinesisListStreamsCmd(),
		newKinesisPutRecordCmd(),
		newKinesisPutRecordsCmd(),
	)

	return cmd
}

func newKinesisCreateStreamCmd() *cobra.Command {
	var streamName string
	var maxRecordSizeInKiB int32
	var shardCount int32
	var streamModeDetails string
	var tags string
	var warmThroughputMiBps int32

	cmd := &cobra.Command{
		Use:   "create-stream",
		Short: "CreateStream",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := kinesis.NewFromConfig(cfg, func(o *kinesis.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &kinesis.CreateStreamInput{}

			if streamName != "" {
				input.StreamName = aws.String(streamName)
			}

			if maxRecordSizeInKiB != 0 {
				input.MaxRecordSizeInKiB = aws.Int32(maxRecordSizeInKiB)
			}

			if shardCount != 0 {
				input.ShardCount = aws.Int32(shardCount)
			}

			if streamModeDetails != "" {
				var val types.StreamModeDetails
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), streamModeDetails); err != nil {
					return fmt.Errorf("create-stream: parse --stream-mode-details: %w", err)
				}
				input.StreamModeDetails = &val
			}

			if tags != "" {
				if err := json.Unmarshal([]byte(tags), &input.Tags); err != nil {
					return fmt.Errorf("create-stream: parse --tags: %w", err)
				}
			}

			if warmThroughputMiBps != 0 {
				input.WarmThroughputMiBps = aws.Int32(warmThroughputMiBps)
			}

			_, err = client.CreateStream(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-stream failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&streamName, "stream-name", "", "Stream name")

	cmd.Flags().Int32Var(&maxRecordSizeInKiB, "max-record-size-in-ki-b", 0, "Max record size in ki b")

	cmd.Flags().Int32Var(&shardCount, "shard-count", 0, "Shard count")

	cmd.Flags().StringVar(&streamModeDetails, "stream-mode-details", "", "Stream mode details (key=value,key2=value2)")

	cmd.Flags().StringVar(&tags, "tags", "", "Tags (JSON)")

	cmd.Flags().Int32Var(&warmThroughputMiBps, "warm-throughput-mi-bps", 0, "Warm throughput mi bps")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newKinesisDeleteStreamCmd() *cobra.Command {
	var enforceConsumerDeletion bool
	var streamARN string
	var streamId string
	var streamName string

	cmd := &cobra.Command{
		Use:   "delete-stream",
		Short: "DeleteStream",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := kinesis.NewFromConfig(cfg, func(o *kinesis.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &kinesis.DeleteStreamInput{}

			if enforceConsumerDeletion {
				input.EnforceConsumerDeletion = aws.Bool(enforceConsumerDeletion)
			}

			if streamARN != "" {
				input.StreamARN = aws.String(streamARN)
			}

			if streamId != "" {
				input.StreamId = aws.String(streamId)
			}

			if streamName != "" {
				input.StreamName = aws.String(streamName)
			}

			_, err = client.DeleteStream(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-stream failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&enforceConsumerDeletion, "enforce-consumer-deletion", false, "Enforce consumer deletion")

	cmd.Flags().StringVar(&streamARN, "stream-arn", "", "Stream arn")

	cmd.Flags().StringVar(&streamId, "stream-id", "", "Stream id")

	cmd.Flags().StringVar(&streamName, "stream-name", "", "Stream name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newKinesisDescribeStreamCmd() *cobra.Command {
	var exclusiveStartShardId string
	var limit int32
	var streamARN string
	var streamId string
	var streamName string

	cmd := &cobra.Command{
		Use:   "describe-stream",
		Short: "DescribeStream",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := kinesis.NewFromConfig(cfg, func(o *kinesis.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &kinesis.DescribeStreamInput{}

			if exclusiveStartShardId != "" {
				input.ExclusiveStartShardId = aws.String(exclusiveStartShardId)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			if streamARN != "" {
				input.StreamARN = aws.String(streamARN)
			}

			if streamId != "" {
				input.StreamId = aws.String(streamId)
			}

			if streamName != "" {
				input.StreamName = aws.String(streamName)
			}

			out, err := client.DescribeStream(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-stream failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&exclusiveStartShardId, "exclusive-start-shard-id", "", "Exclusive start shard id")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().StringVar(&streamARN, "stream-arn", "", "Stream arn")

	cmd.Flags().StringVar(&streamId, "stream-id", "", "Stream id")

	cmd.Flags().StringVar(&streamName, "stream-name", "", "Stream name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newKinesisDescribeStreamSummaryCmd() *cobra.Command {
	var streamARN string
	var streamId string
	var streamName string

	cmd := &cobra.Command{
		Use:   "describe-stream-summary",
		Short: "DescribeStreamSummary",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := kinesis.NewFromConfig(cfg, func(o *kinesis.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &kinesis.DescribeStreamSummaryInput{}

			if streamARN != "" {
				input.StreamARN = aws.String(streamARN)
			}

			if streamId != "" {
				input.StreamId = aws.String(streamId)
			}

			if streamName != "" {
				input.StreamName = aws.String(streamName)
			}

			out, err := client.DescribeStreamSummary(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-stream-summary failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&streamARN, "stream-arn", "", "Stream arn")

	cmd.Flags().StringVar(&streamId, "stream-id", "", "Stream id")

	cmd.Flags().StringVar(&streamName, "stream-name", "", "Stream name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newKinesisGetRecordsCmd() *cobra.Command {
	var shardIterator string
	var limit int32
	var streamARN string
	var streamId string

	cmd := &cobra.Command{
		Use:   "get-records",
		Short: "GetRecords",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := kinesis.NewFromConfig(cfg, func(o *kinesis.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &kinesis.GetRecordsInput{}

			if shardIterator != "" {
				input.ShardIterator = aws.String(shardIterator)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			if streamARN != "" {
				input.StreamARN = aws.String(streamARN)
			}

			if streamId != "" {
				input.StreamId = aws.String(streamId)
			}

			out, err := client.GetRecords(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-records failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&shardIterator, "shard-iterator", "", "Shard iterator")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().StringVar(&streamARN, "stream-arn", "", "Stream arn")

	cmd.Flags().StringVar(&streamId, "stream-id", "", "Stream id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newKinesisGetShardIteratorCmd() *cobra.Command {
	var shardId string
	var shardIteratorType string
	var startingSequenceNumber string
	var streamARN string
	var streamId string
	var streamName string
	var timestamp string

	cmd := &cobra.Command{
		Use:   "get-shard-iterator",
		Short: "GetShardIterator",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := kinesis.NewFromConfig(cfg, func(o *kinesis.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &kinesis.GetShardIteratorInput{}

			if shardId != "" {
				input.ShardId = aws.String(shardId)
			}

			if shardIteratorType != "" {
				input.ShardIteratorType = types.ShardIteratorType(shardIteratorType)
			}

			if startingSequenceNumber != "" {
				input.StartingSequenceNumber = aws.String(startingSequenceNumber)
			}

			if streamARN != "" {
				input.StreamARN = aws.String(streamARN)
			}

			if streamId != "" {
				input.StreamId = aws.String(streamId)
			}

			if streamName != "" {
				input.StreamName = aws.String(streamName)
			}

			if timestamp != "" {
				parsed, err := time.Parse(time.RFC3339, timestamp)
				if err != nil {
					return fmt.Errorf("get-shard-iterator: parse --timestamp: %w", err)
				}
				input.Timestamp = &parsed
			}

			out, err := client.GetShardIterator(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-shard-iterator failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&shardId, "shard-id", "", "Shard id")

	cmd.Flags().StringVar(&shardIteratorType, "shard-iterator-type", "", "Shard iterator type")

	cmd.Flags().StringVar(&startingSequenceNumber, "starting-sequence-number", "", "Starting sequence number")

	cmd.Flags().StringVar(&streamARN, "stream-arn", "", "Stream arn")

	cmd.Flags().StringVar(&streamId, "stream-id", "", "Stream id")

	cmd.Flags().StringVar(&streamName, "stream-name", "", "Stream name")

	cmd.Flags().StringVar(&timestamp, "timestamp", "", "Timestamp (RFC3339)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newKinesisListShardsCmd() *cobra.Command {
	var exclusiveStartShardId string
	var maxResults int32
	var nextToken string
	var shardFilter string
	var streamARN string
	var streamCreationTimestamp string
	var streamId string
	var streamName string

	cmd := &cobra.Command{
		Use:   "list-shards",
		Short: "ListShards",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := kinesis.NewFromConfig(cfg, func(o *kinesis.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &kinesis.ListShardsInput{}

			if exclusiveStartShardId != "" {
				input.ExclusiveStartShardId = aws.String(exclusiveStartShardId)
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if shardFilter != "" {
				if err := json.Unmarshal([]byte(shardFilter), &input.ShardFilter); err != nil {
					return fmt.Errorf("list-shards: parse --shard-filter: %w", err)
				}
			}

			if streamARN != "" {
				input.StreamARN = aws.String(streamARN)
			}

			if streamCreationTimestamp != "" {
				parsed, err := time.Parse(time.RFC3339, streamCreationTimestamp)
				if err != nil {
					return fmt.Errorf("list-shards: parse --stream-creation-timestamp: %w", err)
				}
				input.StreamCreationTimestamp = &parsed
			}

			if streamId != "" {
				input.StreamId = aws.String(streamId)
			}

			if streamName != "" {
				input.StreamName = aws.String(streamName)
			}

			out, err := client.ListShards(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-shards failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&exclusiveStartShardId, "exclusive-start-shard-id", "", "Exclusive start shard id")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&shardFilter, "shard-filter", "", "Shard filter (JSON)")

	cmd.Flags().StringVar(&streamARN, "stream-arn", "", "Stream arn")

	cmd.Flags().StringVar(&streamCreationTimestamp, "stream-creation-timestamp", "", "Stream creation timestamp (RFC3339)")

	cmd.Flags().StringVar(&streamId, "stream-id", "", "Stream id")

	cmd.Flags().StringVar(&streamName, "stream-name", "", "Stream name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newKinesisListStreamsCmd() *cobra.Command {
	var exclusiveStartStreamName string
	var limit int32
	var nextToken string

	cmd := &cobra.Command{
		Use:   "list-streams",
		Short: "ListStreams",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := kinesis.NewFromConfig(cfg, func(o *kinesis.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &kinesis.ListStreamsInput{}

			if exclusiveStartStreamName != "" {
				input.ExclusiveStartStreamName = aws.String(exclusiveStartStreamName)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.ListStreams(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-streams failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&exclusiveStartStreamName, "exclusive-start-stream-name", "", "Exclusive start stream name")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newKinesisPutRecordCmd() *cobra.Command {
	var data string
	var partitionKey string
	var explicitHashKey string
	var sequenceNumberForOrdering string
	var streamARN string
	var streamId string
	var streamName string

	cmd := &cobra.Command{
		Use:   "put-record",
		Short: "PutRecord",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := kinesis.NewFromConfig(cfg, func(o *kinesis.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &kinesis.PutRecordInput{}

			if data != "" {
				decoded, err := base64.StdEncoding.DecodeString(data)
				if err != nil {
					return fmt.Errorf("put-record: decode --data: %w", err)
				}
				input.Data = decoded
			}

			if partitionKey != "" {
				input.PartitionKey = aws.String(partitionKey)
			}

			if explicitHashKey != "" {
				input.ExplicitHashKey = aws.String(explicitHashKey)
			}

			if sequenceNumberForOrdering != "" {
				input.SequenceNumberForOrdering = aws.String(sequenceNumberForOrdering)
			}

			if streamARN != "" {
				input.StreamARN = aws.String(streamARN)
			}

			if streamId != "" {
				input.StreamId = aws.String(streamId)
			}

			if streamName != "" {
				input.StreamName = aws.String(streamName)
			}

			out, err := client.PutRecord(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-record failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&data, "data", "", "Data (base64-encoded)")

	cmd.Flags().StringVar(&partitionKey, "partition-key", "", "Partition key")

	cmd.Flags().StringVar(&explicitHashKey, "explicit-hash-key", "", "Explicit hash key")

	cmd.Flags().StringVar(&sequenceNumberForOrdering, "sequence-number-for-ordering", "", "Sequence number for ordering")

	cmd.Flags().StringVar(&streamARN, "stream-arn", "", "Stream arn")

	cmd.Flags().StringVar(&streamId, "stream-id", "", "Stream id")

	cmd.Flags().StringVar(&streamName, "stream-name", "", "Stream name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newKinesisPutRecordsCmd() *cobra.Command {
	var records []string
	var streamARN string
	var streamId string
	var streamName string

	cmd := &cobra.Command{
		Use:   "put-records",
		Short: "PutRecords",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := kinesis.NewFromConfig(cfg, func(o *kinesis.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &kinesis.PutRecordsInput{}

			for _, raw := range records {
				var val types.PutRecordsRequestEntry
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("put-records: parse --records: %w", err)
				}
				input.Records = append(input.Records, val)
			}

			if streamARN != "" {
				input.StreamARN = aws.String(streamARN)
			}

			if streamId != "" {
				input.StreamId = aws.String(streamId)
			}

			if streamName != "" {
				input.StreamName = aws.String(streamName)
			}

			out, err := client.PutRecords(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-records failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&records, "records", nil, "Records (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&streamARN, "stream-arn", "", "Stream arn")

	cmd.Flags().StringVar(&streamId, "stream-id", "", "Stream id")

	cmd.Flags().StringVar(&streamName, "stream-name", "", "Stream name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
