// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/acm"
	"github.com/aws/aws-sdk-go-v2/service/acm/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newACMCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "acm",
		Short: "ACM commands",
	}

	cmd.AddCommand(
		newACMDeleteCertificateCmd(),
		newACMDescribeCertificateCmd(),
		newACMGetCertificateCmd(),
		newACMImportCertificateCmd(),
		newACMListCertificatesCmd(),
		newACMRequestCertificateCmd(),
	)

	return cmd
}

func newACMDeleteCertificateCmd() *cobra.Command {
	var certificateArn string

	cmd := &cobra.Command{
		Use:   "delete-certificate",
		Short: "DeleteCertificate",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := acm.NewFromConfig(cfg, func(o *acm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &acm.DeleteCertificateInput{}

			if certificateArn != "" {
				input.CertificateArn = aws.String(certificateArn)
			}

			_, err = client.DeleteCertificate(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-certificate failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&certificateArn, "certificate-arn", "", "Certificate arn")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newACMDescribeCertificateCmd() *cobra.Command {
	var certificateArn string

	cmd := &cobra.Command{
		Use:   "describe-certificate",
		Short: "DescribeCertificate",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := acm.NewFromConfig(cfg, func(o *acm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &acm.DescribeCertificateInput{}

			if certificateArn != "" {
				input.CertificateArn = aws.String(certificateArn)
			}

			out, err := client.DescribeCertificate(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-certificate failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&certificateArn, "certificate-arn", "", "Certificate arn")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newACMGetCertificateCmd() *cobra.Command {
	var certificateArn string

	cmd := &cobra.Command{
		Use:   "get-certificate",
		Short: "GetCertificate",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := acm.NewFromConfig(cfg, func(o *acm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &acm.GetCertificateInput{}

			if certificateArn != "" {
				input.CertificateArn = aws.String(certificateArn)
			}

			out, err := client.GetCertificate(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-certificate failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&certificateArn, "certificate-arn", "", "Certificate arn")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newACMImportCertificateCmd() *cobra.Command {
	var certificate string
	var privateKey string
	var certificateArn string
	var certificateChain string
	var tags []string

	cmd := &cobra.Command{
		Use:   "import-certificate",
		Short: "ImportCertificate",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := acm.NewFromConfig(cfg, func(o *acm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &acm.ImportCertificateInput{}

			if certificate != "" {
				decoded, err := base64.StdEncoding.DecodeString(certificate)
				if err != nil {
					return fmt.Errorf("import-certificate: decode --certificate: %w", err)
				}
				input.Certificate = decoded
			}

			if privateKey != "" {
				decoded, err := base64.StdEncoding.DecodeString(privateKey)
				if err != nil {
					return fmt.Errorf("import-certificate: decode --private-key: %w", err)
				}
				input.PrivateKey = decoded
			}

			if certificateArn != "" {
				input.CertificateArn = aws.String(certificateArn)
			}

			if certificateChain != "" {
				decoded, err := base64.StdEncoding.DecodeString(certificateChain)
				if err != nil {
					return fmt.Errorf("import-certificate: decode --certificate-chain: %w", err)
				}
				input.CertificateChain = decoded
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("import-certificate: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			out, err := client.ImportCertificate(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("import-certificate failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&certificate, "certificate", "", "Certificate (base64-encoded)")

	cmd.Flags().StringVar(&privateKey, "private-key", "", "Private key (base64-encoded)")

	cmd.Flags().StringVar(&certificateArn, "certificate-arn", "", "Certificate arn")

	cmd.Flags().StringVar(&certificateChain, "certificate-chain", "", "Certificate chain (base64-encoded)")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newACMListCertificatesCmd() *cobra.Command {
	var certificateStatuses []string
	var includes string
	var maxItems int32
	var nextToken string
	var sortBy string
	var sortOrder string

	cmd := &cobra.Command{
		Use:   "list-certificates",
		Short: "ListCertificates",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := acm.NewFromConfig(cfg, func(o *acm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &acm.ListCertificatesInput{}

			for _, s := range certificateStatuses {
				input.CertificateStatuses = append(input.CertificateStatuses, types.CertificateStatus(s))
			}

			if includes != "" {
				if err := json.Unmarshal([]byte(includes), &input.Includes); err != nil {
					return fmt.Errorf("list-certificates: parse --includes: %w", err)
				}
			}

			if maxItems != 0 {
				input.MaxItems = aws.Int32(maxItems)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if sortBy != "" {
				input.SortBy = types.SortBy(sortBy)
			}

			if sortOrder != "" {
				input.SortOrder = types.SortOrder(sortOrder)
			}

			out, err := client.ListCertificates(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-certificates failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&certificateStatuses, "certificate-statuses", nil, "Certificate statuses")

	cmd.Flags().StringVar(&includes, "includes", "", "Includes (JSON)")

	cmd.Flags().Int32Var(&maxItems, "max-items", 0, "Max items")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&sortBy, "sort-by", "", "Sort by")

	cmd.Flags().StringVar(&sortOrder, "sort-order", "", "Sort order")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newACMRequestCertificateCmd() *cobra.Command {
	var domainName string
	var certificateAuthorityArn string
	var domainValidationOptions []string
	var idempotencyToken string
	var keyAlgorithm string
	var managedBy string
	var options string
	var subjectAlternativeNames []string
	var tags []string
	var validationMethod string

	cmd := &cobra.Command{
		Use:   "request-certificate",
		Short: "RequestCertificate",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := acm.NewFromConfig(cfg, func(o *acm.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &acm.RequestCertificateInput{}

			if domainName != "" {
				input.DomainName = aws.String(domainName)
			}

			if certificateAuthorityArn != "" {
				input.CertificateAuthorityArn = aws.String(certificateAuthorityArn)
			}

			for _, raw := range domainValidationOptions {
				var val types.DomainValidationOption
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("request-certificate: parse --domain-validation-options: %w", err)
				}
				input.DomainValidationOptions = append(input.DomainValidationOptions, val)
			}

			if idempotencyToken != "" {
				input.IdempotencyToken = aws.String(idempotencyToken)
			}

			if keyAlgorithm != "" {
				input.KeyAlgorithm = types.KeyAlgorithm(keyAlgorithm)
			}

			if managedBy != "" {
				input.ManagedBy = types.CertificateManagedBy(managedBy)
			}

			if options != "" {
				var val types.CertificateOptions
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), options); err != nil {
					return fmt.Errorf("request-certificate: parse --options: %w", err)
				}
				input.Options = &val
			}

			if len(subjectAlternativeNames) > 0 {
				input.SubjectAlternativeNames = subjectAlternativeNames
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("request-certificate: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			if validationMethod != "" {
				input.ValidationMethod = types.ValidationMethod(validationMethod)
			}

			out, err := client.RequestCertificate(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("request-certificate failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&domainName, "domain-name", "", "Domain name")

	cmd.Flags().StringVar(&certificateAuthorityArn, "certificate-authority-arn", "", "Certificate authority arn")

	cmd.Flags().StringArrayVar(&domainValidationOptions, "domain-validation-options", nil, "Domain validation options (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&idempotencyToken, "idempotency-token", "", "Idempotency token")

	cmd.Flags().StringVar(&keyAlgorithm, "key-algorithm", "", "Key algorithm")

	cmd.Flags().StringVar(&managedBy, "managed-by", "", "Managed by")

	cmd.Flags().StringVar(&options, "options", "", "Options (key=value,key2=value2)")

	cmd.Flags().StringArrayVar(&subjectAlternativeNames, "subject-alternative-names", nil, "Subject alternative names")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&validationMethod, "validation-method", "", "Validation method")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
