// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/ecr"
	"github.com/aws/aws-sdk-go-v2/service/ecr/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newECRCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "ecr",
		Short: "ECR commands",
	}

	cmd.AddCommand(
		newECRBatchDeleteImageCmd(),
		newECRBatchGetImageCmd(),
		newECRCreateRepositoryCmd(),
		newECRDeleteLifecyclePolicyCmd(),
		newECRDeleteRepositoryCmd(),
		newECRDescribeRepositoriesCmd(),
		newECRGetAuthorizationTokenCmd(),
		newECRGetLifecyclePolicyCmd(),
		newECRListImagesCmd(),
		newECRPutImageCmd(),
		newECRPutLifecyclePolicyCmd(),
	)

	return cmd
}

func newECRBatchDeleteImageCmd() *cobra.Command {
	var imageIds []string
	var repositoryName string
	var registryId string

	cmd := &cobra.Command{
		Use:   "batch-delete-image",
		Short: "BatchDeleteImage",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.BatchDeleteImageInput{}

			for _, raw := range imageIds {
				var val types.ImageIdentifier
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("batch-delete-image: parse --image-ids: %w", err)
				}
				input.ImageIds = append(input.ImageIds, val)
			}

			if repositoryName != "" {
				input.RepositoryName = aws.String(repositoryName)
			}

			if registryId != "" {
				input.RegistryId = aws.String(registryId)
			}

			out, err := client.BatchDeleteImage(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("batch-delete-image failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&imageIds, "image-ids", nil, "Image ids (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&repositoryName, "repository-name", "", "Repository name")

	cmd.Flags().StringVar(&registryId, "registry-id", "", "Registry id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newECRBatchGetImageCmd() *cobra.Command {
	var imageIds []string
	var repositoryName string
	var acceptedMediaTypes []string
	var registryId string

	cmd := &cobra.Command{
		Use:   "batch-get-image",
		Short: "BatchGetImage",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.BatchGetImageInput{}

			for _, raw := range imageIds {
				var val types.ImageIdentifier
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("batch-get-image: parse --image-ids: %w", err)
				}
				input.ImageIds = append(input.ImageIds, val)
			}

			if repositoryName != "" {
				input.RepositoryName = aws.String(repositoryName)
			}

			if len(acceptedMediaTypes) > 0 {
				input.AcceptedMediaTypes = acceptedMediaTypes
			}

			if registryId != "" {
				input.RegistryId = aws.String(registryId)
			}

			out, err := client.BatchGetImage(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("batch-get-image failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&imageIds, "image-ids", nil, "Image ids (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&repositoryName, "repository-name", "", "Repository name")

	cmd.Flags().StringArrayVar(&acceptedMediaTypes, "accepted-media-types", nil, "Accepted media types")

	cmd.Flags().StringVar(&registryId, "registry-id", "", "Registry id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newECRCreateRepositoryCmd() *cobra.Command {
	var repositoryName string
	var encryptionConfiguration string
	var imageScanningConfiguration string
	var imageTagMutability string
	var imageTagMutabilityExclusionFilters []string
	var registryId string
	var tags []string

	cmd := &cobra.Command{
		Use:   "create-repository",
		Short: "CreateRepository",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.CreateRepositoryInput{}

			if repositoryName != "" {
				input.RepositoryName = aws.String(repositoryName)
			}

			if encryptionConfiguration != "" {
				var val types.EncryptionConfiguration
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), encryptionConfiguration); err != nil {
					return fmt.Errorf("create-repository: parse --encryption-configuration: %w", err)
				}
				input.EncryptionConfiguration = &val
			}

			if imageScanningConfiguration != "" {
				var val types.ImageScanningConfiguration
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), imageScanningConfiguration); err != nil {
					return fmt.Errorf("create-repository: parse --image-scanning-configuration: %w", err)
				}
				input.ImageScanningConfiguration = &val
			}

			if imageTagMutability != "" {
				input.ImageTagMutability = types.ImageTagMutability(imageTagMutability)
			}

			for _, raw := range imageTagMutabilityExclusionFilters {
				var val types.ImageTagMutabilityExclusionFilter
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-repository: parse --image-tag-mutability-exclusion-filters: %w", err)
				}
				input.ImageTagMutabilityExclusionFilters = append(input.ImageTagMutabilityExclusionFilters, val)
			}

			if registryId != "" {
				input.RegistryId = aws.String(registryId)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-repository: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			out, err := client.CreateRepository(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-repository failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&repositoryName, "repository-name", "", "Repository name")

	cmd.Flags().StringVar(&encryptionConfiguration, "encryption-configuration", "", "Encryption configuration (key=value,key2=value2)")

	cmd.Flags().StringVar(&imageScanningConfiguration, "image-scanning-configuration", "", "Image scanning configuration (key=value,key2=value2)")

	cmd.Flags().StringVar(&imageTagMutability, "image-tag-mutability", "", "Image tag mutability")

	cmd.Flags().StringArrayVar(&imageTagMutabilityExclusionFilters, "image-tag-mutability-exclusion-filters", nil, "Image tag mutability exclusion filters (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&registryId, "registry-id", "", "Registry id")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newECRDeleteLifecyclePolicyCmd() *cobra.Command {
	var repositoryName string
	var registryId string

	cmd := &cobra.Command{
		Use:   "delete-lifecycle-policy",
		Short: "DeleteLifecyclePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.DeleteLifecyclePolicyInput{}

			if repositoryName != "" {
				input.RepositoryName = aws.String(repositoryName)
			}

			if registryId != "" {
				input.RegistryId = aws.String(registryId)
			}

			out, err := client.DeleteLifecyclePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-lifecycle-policy failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&repositoryName, "repository-name", "", "Repository name")

	cmd.Flags().StringVar(&registryId, "registry-id", "", "Registry id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newECRDeleteRepositoryCmd() *cobra.Command {
	var repositoryName string
	var force bool
	var registryId string

	cmd := &cobra.Command{
		Use:   "delete-repository",
		Short: "DeleteRepository",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.DeleteRepositoryInput{}

			if repositoryName != "" {
				input.RepositoryName = aws.String(repositoryName)
			}

			if force {
				input.Force = force
			}

			if registryId != "" {
				input.RegistryId = aws.String(registryId)
			}

			out, err := client.DeleteRepository(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-repository failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&repositoryName, "repository-name", "", "Repository name")

	cmd.Flags().BoolVar(&force, "force", false, "Force")

	cmd.Flags().StringVar(&registryId, "registry-id", "", "Registry id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newECRDescribeRepositoriesCmd() *cobra.Command {
	var maxResults int32
	var nextToken string
	var registryId string
	var repositoryNames []string

	cmd := &cobra.Command{
		Use:   "describe-repositories",
		Short: "DescribeRepositories",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.DescribeRepositoriesInput{}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if registryId != "" {
				input.RegistryId = aws.String(registryId)
			}

			if len(repositoryNames) > 0 {
				input.RepositoryNames = repositoryNames
			}

			out, err := client.DescribeRepositories(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-repositories failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&registryId, "registry-id", "", "Registry id")

	cmd.Flags().StringArrayVar(&repositoryNames, "repository-names", nil, "Repository names")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newECRGetAuthorizationTokenCmd() *cobra.Command {
	var registryIds []string

	cmd := &cobra.Command{
		Use:   "get-authorization-token",
		Short: "GetAuthorizationToken",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.GetAuthorizationTokenInput{}

			if len(registryIds) > 0 {
				input.RegistryIds = registryIds
			}

			out, err := client.GetAuthorizationToken(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-authorization-token failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringArrayVar(&registryIds, "registry-ids", nil, "Registry ids")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newECRGetLifecyclePolicyCmd() *cobra.Command {
	var repositoryName string
	var registryId string

	cmd := &cobra.Command{
		Use:   "get-lifecycle-policy",
		Short: "GetLifecyclePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.GetLifecyclePolicyInput{}

			if repositoryName != "" {
				input.RepositoryName = aws.String(repositoryName)
			}

			if registryId != "" {
				input.RegistryId = aws.String(registryId)
			}

			out, err := client.GetLifecyclePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("get-lifecycle-policy failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&repositoryName, "repository-name", "", "Repository name")

	cmd.Flags().StringVar(&registryId, "registry-id", "", "Registry id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newECRListImagesCmd() *cobra.Command {
	var repositoryName string
	var filter string
	var maxResults int32
	var nextToken string
	var registryId string

	cmd := &cobra.Command{
		Use:   "list-images",
		Short: "ListImages",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.ListImagesInput{}

			if repositoryName != "" {
				input.RepositoryName = aws.String(repositoryName)
			}

			if filter != "" {
				var val types.ListImagesFilter
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), filter); err != nil {
					return fmt.Errorf("list-images: parse --filter: %w", err)
				}
				input.Filter = &val
			}

			if maxResults != 0 {
				input.MaxResults = aws.Int32(maxResults)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			if registryId != "" {
				input.RegistryId = aws.String(registryId)
			}

			out, err := client.ListImages(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-images failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&repositoryName, "repository-name", "", "Repository name")

	cmd.Flags().StringVar(&filter, "filter", "", "Filter (key=value,key2=value2)")

	cmd.Flags().Int32Var(&maxResults, "max-results", 0, "Max results")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().StringVar(&registryId, "registry-id", "", "Registry id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newECRPutImageCmd() *cobra.Command {
	var imageManifest string
	var repositoryName string
	var imageDigest string
	var imageManifestMediaType string
	var imageTag string
	var registryId string

	cmd := &cobra.Command{
		Use:   "put-image",
		Short: "PutImage",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.PutImageInput{}

			if imageManifest != "" {
				input.ImageManifest = aws.String(imageManifest)
			}

			if repositoryName != "" {
				input.RepositoryName = aws.String(repositoryName)
			}

			if imageDigest != "" {
				input.ImageDigest = aws.String(imageDigest)
			}

			if imageManifestMediaType != "" {
				input.ImageManifestMediaType = aws.String(imageManifestMediaType)
			}

			if imageTag != "" {
				input.ImageTag = aws.String(imageTag)
			}

			if registryId != "" {
				input.RegistryId = aws.String(registryId)
			}

			out, err := client.PutImage(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-image failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&imageManifest, "image-manifest", "", "Image manifest")

	cmd.Flags().StringVar(&repositoryName, "repository-name", "", "Repository name")

	cmd.Flags().StringVar(&imageDigest, "image-digest", "", "Image digest")

	cmd.Flags().StringVar(&imageManifestMediaType, "image-manifest-media-type", "", "Image manifest media type")

	cmd.Flags().StringVar(&imageTag, "image-tag", "", "Image tag")

	cmd.Flags().StringVar(&registryId, "registry-id", "", "Registry id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newECRPutLifecyclePolicyCmd() *cobra.Command {
	var lifecyclePolicyText string
	var repositoryName string
	var registryId string

	cmd := &cobra.Command{
		Use:   "put-lifecycle-policy",
		Short: "PutLifecyclePolicy",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := ecr.NewFromConfig(cfg, func(o *ecr.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &ecr.PutLifecyclePolicyInput{}

			if lifecyclePolicyText != "" {
				input.LifecyclePolicyText = aws.String(lifecyclePolicyText)
			}

			if repositoryName != "" {
				input.RepositoryName = aws.String(repositoryName)
			}

			if registryId != "" {
				input.RegistryId = aws.String(registryId)
			}

			out, err := client.PutLifecyclePolicy(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-lifecycle-policy failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&lifecyclePolicyText, "lifecycle-policy-text", "", "Lifecycle policy text")

	cmd.Flags().StringVar(&repositoryName, "repository-name", "", "Repository name")

	cmd.Flags().StringVar(&registryId, "registry-id", "", "Registry id")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
