// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/firehose"
	"github.com/aws/aws-sdk-go-v2/service/firehose/types"
	"github.com/spf13/cobra"
	"github.com/thomasf/kumo/internal/cligen"
	"reflect"
)

func newFirehoseCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "firehose",
		Short: "Firehose commands",
	}

	cmd.AddCommand(
		newFirehoseCreateDeliveryStreamCmd(),
		newFirehoseDeleteDeliveryStreamCmd(),
		newFirehoseDescribeDeliveryStreamCmd(),
		newFirehoseListDeliveryStreamsCmd(),
		newFirehosePutRecordCmd(),
		newFirehosePutRecordBatchCmd(),
		newFirehoseUpdateDestinationCmd(),
	)

	return cmd
}

func newFirehoseCreateDeliveryStreamCmd() *cobra.Command {
	var deliveryStreamName string
	var amazonOpenSearchServerlessDestinationConfiguration string
	var amazonopensearchserviceDestinationConfiguration string
	var databaseSourceConfiguration string
	var deliveryStreamEncryptionConfigurationInput string
	var deliveryStreamType string
	var directPutSourceConfiguration string
	var elasticsearchDestinationConfiguration string
	var extendedS3DestinationConfiguration string
	var httpEndpointDestinationConfiguration string
	var icebergDestinationConfiguration string
	var kinesisStreamSourceConfiguration string
	var mSKSourceConfiguration string
	var redshiftDestinationConfiguration string
	var s3DestinationConfiguration string
	var snowflakeDestinationConfiguration string
	var splunkDestinationConfiguration string
	var tags []string

	cmd := &cobra.Command{
		Use:   "create-delivery-stream",
		Short: "CreateDeliveryStream",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := firehose.NewFromConfig(cfg, func(o *firehose.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &firehose.CreateDeliveryStreamInput{}

			if deliveryStreamName != "" {
				input.DeliveryStreamName = aws.String(deliveryStreamName)
			}

			if amazonOpenSearchServerlessDestinationConfiguration != "" {
				if err := json.Unmarshal([]byte(amazonOpenSearchServerlessDestinationConfiguration), &input.AmazonOpenSearchServerlessDestinationConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --amazon-open-search-serverless-destination-configuration: %w", err)
				}
			}

			if amazonopensearchserviceDestinationConfiguration != "" {
				if err := json.Unmarshal([]byte(amazonopensearchserviceDestinationConfiguration), &input.AmazonopensearchserviceDestinationConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --amazonopensearchservice-destination-configuration: %w", err)
				}
			}

			if databaseSourceConfiguration != "" {
				if err := json.Unmarshal([]byte(databaseSourceConfiguration), &input.DatabaseSourceConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --database-source-configuration: %w", err)
				}
			}

			if deliveryStreamEncryptionConfigurationInput != "" {
				var val types.DeliveryStreamEncryptionConfigurationInput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), deliveryStreamEncryptionConfigurationInput); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --delivery-stream-encryption-configuration-input: %w", err)
				}
				input.DeliveryStreamEncryptionConfigurationInput = &val
			}

			if deliveryStreamType != "" {
				input.DeliveryStreamType = types.DeliveryStreamType(deliveryStreamType)
			}

			if directPutSourceConfiguration != "" {
				var val types.DirectPutSourceConfiguration
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), directPutSourceConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --direct-put-source-configuration: %w", err)
				}
				input.DirectPutSourceConfiguration = &val
			}

			if elasticsearchDestinationConfiguration != "" {
				if err := json.Unmarshal([]byte(elasticsearchDestinationConfiguration), &input.ElasticsearchDestinationConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --elasticsearch-destination-configuration: %w", err)
				}
			}

			if extendedS3DestinationConfiguration != "" {
				if err := json.Unmarshal([]byte(extendedS3DestinationConfiguration), &input.ExtendedS3DestinationConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --extended-s-3-destination-configuration: %w", err)
				}
			}

			if httpEndpointDestinationConfiguration != "" {
				if err := json.Unmarshal([]byte(httpEndpointDestinationConfiguration), &input.HttpEndpointDestinationConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --http-endpoint-destination-configuration: %w", err)
				}
			}

			if icebergDestinationConfiguration != "" {
				if err := json.Unmarshal([]byte(icebergDestinationConfiguration), &input.IcebergDestinationConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --iceberg-destination-configuration: %w", err)
				}
			}

			if kinesisStreamSourceConfiguration != "" {
				var val types.KinesisStreamSourceConfiguration
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), kinesisStreamSourceConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --kinesis-stream-source-configuration: %w", err)
				}
				input.KinesisStreamSourceConfiguration = &val
			}

			if mSKSourceConfiguration != "" {
				if err := json.Unmarshal([]byte(mSKSourceConfiguration), &input.MSKSourceConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --m-s-k-source-configuration: %w", err)
				}
			}

			if redshiftDestinationConfiguration != "" {
				if err := json.Unmarshal([]byte(redshiftDestinationConfiguration), &input.RedshiftDestinationConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --redshift-destination-configuration: %w", err)
				}
			}

			if s3DestinationConfiguration != "" {
				if err := json.Unmarshal([]byte(s3DestinationConfiguration), &input.S3DestinationConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --s-3-destination-configuration: %w", err)
				}
			}

			if snowflakeDestinationConfiguration != "" {
				if err := json.Unmarshal([]byte(snowflakeDestinationConfiguration), &input.SnowflakeDestinationConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --snowflake-destination-configuration: %w", err)
				}
			}

			if splunkDestinationConfiguration != "" {
				if err := json.Unmarshal([]byte(splunkDestinationConfiguration), &input.SplunkDestinationConfiguration); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --splunk-destination-configuration: %w", err)
				}
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-delivery-stream: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			out, err := client.CreateDeliveryStream(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-delivery-stream failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&deliveryStreamName, "delivery-stream-name", "", "Delivery stream name")

	cmd.Flags().StringVar(&amazonOpenSearchServerlessDestinationConfiguration, "amazon-open-search-serverless-destination-configuration", "", "Amazon open search serverless destination configuration (JSON)")

	cmd.Flags().StringVar(&amazonopensearchserviceDestinationConfiguration, "amazonopensearchservice-destination-configuration", "", "Amazonopensearchservice destination configuration (JSON)")

	cmd.Flags().StringVar(&databaseSourceConfiguration, "database-source-configuration", "", "Database source configuration (JSON)")

	cmd.Flags().StringVar(&deliveryStreamEncryptionConfigurationInput, "delivery-stream-encryption-configuration-input", "", "Delivery stream encryption configuration input (key=value,key2=value2)")

	cmd.Flags().StringVar(&deliveryStreamType, "delivery-stream-type", "", "Delivery stream type")

	cmd.Flags().StringVar(&directPutSourceConfiguration, "direct-put-source-configuration", "", "Direct put source configuration (key=value,key2=value2)")

	cmd.Flags().StringVar(&elasticsearchDestinationConfiguration, "elasticsearch-destination-configuration", "", "Elasticsearch destination configuration (JSON)")

	cmd.Flags().StringVar(&extendedS3DestinationConfiguration, "extended-s-3-destination-configuration", "", "Extended s 3 destination configuration (JSON)")

	cmd.Flags().StringVar(&httpEndpointDestinationConfiguration, "http-endpoint-destination-configuration", "", "Http endpoint destination configuration (JSON)")

	cmd.Flags().StringVar(&icebergDestinationConfiguration, "iceberg-destination-configuration", "", "Iceberg destination configuration (JSON)")

	cmd.Flags().StringVar(&kinesisStreamSourceConfiguration, "kinesis-stream-source-configuration", "", "Kinesis stream source configuration (key=value,key2=value2)")

	cmd.Flags().StringVar(&mSKSourceConfiguration, "m-s-k-source-configuration", "", "M s k source configuration (JSON)")

	cmd.Flags().StringVar(&redshiftDestinationConfiguration, "redshift-destination-configuration", "", "Redshift destination configuration (JSON)")

	cmd.Flags().StringVar(&s3DestinationConfiguration, "s-3-destination-configuration", "", "S 3 destination configuration (JSON)")

	cmd.Flags().StringVar(&snowflakeDestinationConfiguration, "snowflake-destination-configuration", "", "Snowflake destination configuration (JSON)")

	cmd.Flags().StringVar(&splunkDestinationConfiguration, "splunk-destination-configuration", "", "Splunk destination configuration (JSON)")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newFirehoseDeleteDeliveryStreamCmd() *cobra.Command {
	var deliveryStreamName string
	var allowForceDelete bool

	cmd := &cobra.Command{
		Use:   "delete-delivery-stream",
		Short: "DeleteDeliveryStream",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := firehose.NewFromConfig(cfg, func(o *firehose.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &firehose.DeleteDeliveryStreamInput{}

			if deliveryStreamName != "" {
				input.DeliveryStreamName = aws.String(deliveryStreamName)
			}

			if allowForceDelete {
				input.AllowForceDelete = aws.Bool(allowForceDelete)
			}

			_, err = client.DeleteDeliveryStream(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-delivery-stream failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&deliveryStreamName, "delivery-stream-name", "", "Delivery stream name")

	cmd.Flags().BoolVar(&allowForceDelete, "allow-force-delete", false, "Allow force delete")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newFirehoseDescribeDeliveryStreamCmd() *cobra.Command {
	var deliveryStreamName string
	var exclusiveStartDestinationId string
	var limit int32

	cmd := &cobra.Command{
		Use:   "describe-delivery-stream",
		Short: "DescribeDeliveryStream",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := firehose.NewFromConfig(cfg, func(o *firehose.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &firehose.DescribeDeliveryStreamInput{}

			if deliveryStreamName != "" {
				input.DeliveryStreamName = aws.String(deliveryStreamName)
			}

			if exclusiveStartDestinationId != "" {
				input.ExclusiveStartDestinationId = aws.String(exclusiveStartDestinationId)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			out, err := client.DescribeDeliveryStream(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-delivery-stream failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&deliveryStreamName, "delivery-stream-name", "", "Delivery stream name")

	cmd.Flags().StringVar(&exclusiveStartDestinationId, "exclusive-start-destination-id", "", "Exclusive start destination id")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newFirehoseListDeliveryStreamsCmd() *cobra.Command {
	var deliveryStreamType string
	var exclusiveStartDeliveryStreamName string
	var limit int32

	cmd := &cobra.Command{
		Use:   "list-delivery-streams",
		Short: "ListDeliveryStreams",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := firehose.NewFromConfig(cfg, func(o *firehose.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &firehose.ListDeliveryStreamsInput{}

			if deliveryStreamType != "" {
				input.DeliveryStreamType = types.DeliveryStreamType(deliveryStreamType)
			}

			if exclusiveStartDeliveryStreamName != "" {
				input.ExclusiveStartDeliveryStreamName = aws.String(exclusiveStartDeliveryStreamName)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			out, err := client.ListDeliveryStreams(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-delivery-streams failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&deliveryStreamType, "delivery-stream-type", "", "Delivery stream type")

	cmd.Flags().StringVar(&exclusiveStartDeliveryStreamName, "exclusive-start-delivery-stream-name", "", "Exclusive start delivery stream name")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newFirehosePutRecordCmd() *cobra.Command {
	var deliveryStreamName string
	var record string

	cmd := &cobra.Command{
		Use:   "put-record",
		Short: "PutRecord",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := firehose.NewFromConfig(cfg, func(o *firehose.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &firehose.PutRecordInput{}

			if deliveryStreamName != "" {
				input.DeliveryStreamName = aws.String(deliveryStreamName)
			}

			if record != "" {
				var val types.Record
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), record); err != nil {
					return fmt.Errorf("put-record: parse --record: %w", err)
				}
				input.Record = &val
			}

			out, err := client.PutRecord(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-record failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&deliveryStreamName, "delivery-stream-name", "", "Delivery stream name")

	cmd.Flags().StringVar(&record, "record", "", "Record (key=value,key2=value2)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newFirehosePutRecordBatchCmd() *cobra.Command {
	var deliveryStreamName string
	var records []string

	cmd := &cobra.Command{
		Use:   "put-record-batch",
		Short: "PutRecordBatch",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := firehose.NewFromConfig(cfg, func(o *firehose.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &firehose.PutRecordBatchInput{}

			if deliveryStreamName != "" {
				input.DeliveryStreamName = aws.String(deliveryStreamName)
			}

			for _, raw := range records {
				var val types.Record
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("put-record-batch: parse --records: %w", err)
				}
				input.Records = append(input.Records, val)
			}

			out, err := client.PutRecordBatch(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("put-record-batch failed: %w", err)
			}

			if err := writeOutput(out); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&deliveryStreamName, "delivery-stream-name", "", "Delivery stream name")

	cmd.Flags().StringArrayVar(&records, "records", nil, "Records (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newFirehoseUpdateDestinationCmd() *cobra.Command {
	var currentDeliveryStreamVersionId string
	var deliveryStreamName string
	var destinationId string
	var amazonOpenSearchServerlessDestinationUpdate string
	var amazonopensearchserviceDestinationUpdate string
	var elasticsearchDestinationUpdate string
	var extendedS3DestinationUpdate string
	var httpEndpointDestinationUpdate string
	var icebergDestinationUpdate string
	var redshiftDestinationUpdate string
	var s3DestinationUpdate string
	var snowflakeDestinationUpdate string
	var splunkDestinationUpdate string

	cmd := &cobra.Command{
		Use:   "update-destination",
		Short: "UpdateDestination",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := firehose.NewFromConfig(cfg, func(o *firehose.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &firehose.UpdateDestinationInput{}

			if currentDeliveryStreamVersionId != "" {
				input.CurrentDeliveryStreamVersionId = aws.String(currentDeliveryStreamVersionId)
			}

			if deliveryStreamName != "" {
				input.DeliveryStreamName = aws.String(deliveryStreamName)
			}

			if destinationId != "" {
				input.DestinationId = aws.String(destinationId)
			}

			if amazonOpenSearchServerlessDestinationUpdate != "" {
				if err := json.Unmarshal([]byte(amazonOpenSearchServerlessDestinationUpdate), &input.AmazonOpenSearchServerlessDestinationUpdate); err != nil {
					return fmt.Errorf("update-destination: parse --amazon-open-search-serverless-destination-update: %w", err)
				}
			}

			if amazonopensearchserviceDestinationUpdate != "" {
				if err := json.Unmarshal([]byte(amazonopensearchserviceDestinationUpdate), &input.AmazonopensearchserviceDestinationUpdate); err != nil {
					return fmt.Errorf("update-destination: parse --amazonopensearchservice-destination-update: %w", err)
				}
			}

			if elasticsearchDestinationUpdate != "" {
				if err := json.Unmarshal([]byte(elasticsearchDestinationUpdate), &input.ElasticsearchDestinationUpdate); err != nil {
					return fmt.Errorf("update-destination: parse --elasticsearch-destination-update: %w", err)
				}
			}

			if extendedS3DestinationUpdate != "" {
				if err := json.Unmarshal([]byte(extendedS3DestinationUpdate), &input.ExtendedS3DestinationUpdate); err != nil {
					return fmt.Errorf("update-destination: parse --extended-s-3-destination-update: %w", err)
				}
			}

			if httpEndpointDestinationUpdate != "" {
				if err := json.Unmarshal([]byte(httpEndpointDestinationUpdate), &input.HttpEndpointDestinationUpdate); err != nil {
					return fmt.Errorf("update-destination: parse --http-endpoint-destination-update: %w", err)
				}
			}

			if icebergDestinationUpdate != "" {
				if err := json.Unmarshal([]byte(icebergDestinationUpdate), &input.IcebergDestinationUpdate); err != nil {
					return fmt.Errorf("update-destination: parse --iceberg-destination-update: %w", err)
				}
			}

			if redshiftDestinationUpdate != "" {
				if err := json.Unmarshal([]byte(redshiftDestinationUpdate), &input.RedshiftDestinationUpdate); err != nil {
					return fmt.Errorf("update-destination: parse --redshift-destination-update: %w", err)
				}
			}

			if s3DestinationUpdate != "" {
				if err := json.Unmarshal([]byte(s3DestinationUpdate), &input.S3DestinationUpdate); err != nil {
					return fmt.Errorf("update-destination: parse --s-3-destination-update: %w", err)
				}
			}

			if snowflakeDestinationUpdate != "" {
				if err := json.Unmarshal([]byte(snowflakeDestinationUpdate), &input.SnowflakeDestinationUpdate); err != nil {
					return fmt.Errorf("update-destination: parse --snowflake-destination-update: %w", err)
				}
			}

			if splunkDestinationUpdate != "" {
				if err := json.Unmarshal([]byte(splunkDestinationUpdate), &input.SplunkDestinationUpdate); err != nil {
					return fmt.Errorf("update-destination: parse --splunk-destination-update: %w", err)
				}
			}

			_, err = client.UpdateDestination(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-destination failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&currentDeliveryStreamVersionId, "current-delivery-stream-version-id", "", "Current delivery stream version id")

	cmd.Flags().StringVar(&deliveryStreamName, "delivery-stream-name", "", "Delivery stream name")

	cmd.Flags().StringVar(&destinationId, "destination-id", "", "Destination id")

	cmd.Flags().StringVar(&amazonOpenSearchServerlessDestinationUpdate, "amazon-open-search-serverless-destination-update", "", "Amazon open search serverless destination update (JSON)")

	cmd.Flags().StringVar(&amazonopensearchserviceDestinationUpdate, "amazonopensearchservice-destination-update", "", "Amazonopensearchservice destination update (JSON)")

	cmd.Flags().StringVar(&elasticsearchDestinationUpdate, "elasticsearch-destination-update", "", "Elasticsearch destination update (JSON)")

	cmd.Flags().StringVar(&extendedS3DestinationUpdate, "extended-s-3-destination-update", "", "Extended s 3 destination update (JSON)")

	cmd.Flags().StringVar(&httpEndpointDestinationUpdate, "http-endpoint-destination-update", "", "Http endpoint destination update (JSON)")

	cmd.Flags().StringVar(&icebergDestinationUpdate, "iceberg-destination-update", "", "Iceberg destination update (JSON)")

	cmd.Flags().StringVar(&redshiftDestinationUpdate, "redshift-destination-update", "", "Redshift destination update (JSON)")

	cmd.Flags().StringVar(&s3DestinationUpdate, "s-3-destination-update", "", "S 3 destination update (JSON)")

	cmd.Flags().StringVar(&snowflakeDestinationUpdate, "snowflake-destination-update", "", "Snowflake destination update (JSON)")

	cmd.Flags().StringVar(&splunkDestinationUpdate, "splunk-destination-update", "", "Splunk destination update (JSON)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
